// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: opentrawl/photos/card/card.proto

package cardwire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpticalCharacterRecognitionLegibility int32

const (
	OpticalCharacterRecognitionLegibility_OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_UNSPECIFIED OpticalCharacterRecognitionLegibility = 0
	OpticalCharacterRecognitionLegibility_OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_CLEAR       OpticalCharacterRecognitionLegibility = 1
	OpticalCharacterRecognitionLegibility_OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_PARTIAL     OpticalCharacterRecognitionLegibility = 2
	OpticalCharacterRecognitionLegibility_OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_UNCLEAR     OpticalCharacterRecognitionLegibility = 3
)

// Enum value maps for OpticalCharacterRecognitionLegibility.
var (
	OpticalCharacterRecognitionLegibility_name = map[int32]string{
		0: "OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_UNSPECIFIED",
		1: "OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_CLEAR",
		2: "OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_PARTIAL",
		3: "OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_UNCLEAR",
	}
	OpticalCharacterRecognitionLegibility_value = map[string]int32{
		"OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_UNSPECIFIED": 0,
		"OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_CLEAR":       1,
		"OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_PARTIAL":     2,
		"OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_UNCLEAR":     3,
	}
)

func (x OpticalCharacterRecognitionLegibility) Enum() *OpticalCharacterRecognitionLegibility {
	p := new(OpticalCharacterRecognitionLegibility)
	*p = x
	return p
}

func (x OpticalCharacterRecognitionLegibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpticalCharacterRecognitionLegibility) Descriptor() protoreflect.EnumDescriptor {
	return file_opentrawl_photos_card_card_proto_enumTypes[0].Descriptor()
}

func (OpticalCharacterRecognitionLegibility) Type() protoreflect.EnumType {
	return &file_opentrawl_photos_card_card_proto_enumTypes[0]
}

func (x OpticalCharacterRecognitionLegibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpticalCharacterRecognitionLegibility.Descriptor instead.
func (OpticalCharacterRecognitionLegibility) EnumDescriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{0}
}

type PhotographedPlaceCertainty int32

const (
	PhotographedPlaceCertainty_PHOTOGRAPHED_PLACE_CERTAINTY_UNSPECIFIED PhotographedPlaceCertainty = 0
	PhotographedPlaceCertainty_PHOTOGRAPHED_PLACE_CERTAINTY_IDENTIFIED  PhotographedPlaceCertainty = 1
	PhotographedPlaceCertainty_PHOTOGRAPHED_PLACE_CERTAINTY_POSSIBLE    PhotographedPlaceCertainty = 2
	PhotographedPlaceCertainty_PHOTOGRAPHED_PLACE_CERTAINTY_UNKNOWN     PhotographedPlaceCertainty = 3
)

// Enum value maps for PhotographedPlaceCertainty.
var (
	PhotographedPlaceCertainty_name = map[int32]string{
		0: "PHOTOGRAPHED_PLACE_CERTAINTY_UNSPECIFIED",
		1: "PHOTOGRAPHED_PLACE_CERTAINTY_IDENTIFIED",
		2: "PHOTOGRAPHED_PLACE_CERTAINTY_POSSIBLE",
		3: "PHOTOGRAPHED_PLACE_CERTAINTY_UNKNOWN",
	}
	PhotographedPlaceCertainty_value = map[string]int32{
		"PHOTOGRAPHED_PLACE_CERTAINTY_UNSPECIFIED": 0,
		"PHOTOGRAPHED_PLACE_CERTAINTY_IDENTIFIED":  1,
		"PHOTOGRAPHED_PLACE_CERTAINTY_POSSIBLE":    2,
		"PHOTOGRAPHED_PLACE_CERTAINTY_UNKNOWN":     3,
	}
)

func (x PhotographedPlaceCertainty) Enum() *PhotographedPlaceCertainty {
	p := new(PhotographedPlaceCertainty)
	*p = x
	return p
}

func (x PhotographedPlaceCertainty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhotographedPlaceCertainty) Descriptor() protoreflect.EnumDescriptor {
	return file_opentrawl_photos_card_card_proto_enumTypes[1].Descriptor()
}

func (PhotographedPlaceCertainty) Type() protoreflect.EnumType {
	return &file_opentrawl_photos_card_card_proto_enumTypes[1]
}

func (x PhotographedPlaceCertainty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhotographedPlaceCertainty.Descriptor instead.
func (PhotographedPlaceCertainty) EnumDescriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{1}
}

type PhotoCardUncertaintyScope int32

const (
	PhotoCardUncertaintyScope_PHOTO_CARD_UNCERTAINTY_SCOPE_UNSPECIFIED                   PhotoCardUncertaintyScope = 0
	PhotoCardUncertaintyScope_PHOTO_CARD_UNCERTAINTY_SCOPE_DESCRIPTION                   PhotoCardUncertaintyScope = 1
	PhotoCardUncertaintyScope_PHOTO_CARD_UNCERTAINTY_SCOPE_VISIBLE_CONTENT               PhotoCardUncertaintyScope = 2
	PhotoCardUncertaintyScope_PHOTO_CARD_UNCERTAINTY_SCOPE_OPTICAL_CHARACTER_RECOGNITION PhotoCardUncertaintyScope = 3
	PhotoCardUncertaintyScope_PHOTO_CARD_UNCERTAINTY_SCOPE_PHOTOGRAPHED_PLACE            PhotoCardUncertaintyScope = 4
)

// Enum value maps for PhotoCardUncertaintyScope.
var (
	PhotoCardUncertaintyScope_name = map[int32]string{
		0: "PHOTO_CARD_UNCERTAINTY_SCOPE_UNSPECIFIED",
		1: "PHOTO_CARD_UNCERTAINTY_SCOPE_DESCRIPTION",
		2: "PHOTO_CARD_UNCERTAINTY_SCOPE_VISIBLE_CONTENT",
		3: "PHOTO_CARD_UNCERTAINTY_SCOPE_OPTICAL_CHARACTER_RECOGNITION",
		4: "PHOTO_CARD_UNCERTAINTY_SCOPE_PHOTOGRAPHED_PLACE",
	}
	PhotoCardUncertaintyScope_value = map[string]int32{
		"PHOTO_CARD_UNCERTAINTY_SCOPE_UNSPECIFIED":                   0,
		"PHOTO_CARD_UNCERTAINTY_SCOPE_DESCRIPTION":                   1,
		"PHOTO_CARD_UNCERTAINTY_SCOPE_VISIBLE_CONTENT":               2,
		"PHOTO_CARD_UNCERTAINTY_SCOPE_OPTICAL_CHARACTER_RECOGNITION": 3,
		"PHOTO_CARD_UNCERTAINTY_SCOPE_PHOTOGRAPHED_PLACE":            4,
	}
)

func (x PhotoCardUncertaintyScope) Enum() *PhotoCardUncertaintyScope {
	p := new(PhotoCardUncertaintyScope)
	*p = x
	return p
}

func (x PhotoCardUncertaintyScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhotoCardUncertaintyScope) Descriptor() protoreflect.EnumDescriptor {
	return file_opentrawl_photos_card_card_proto_enumTypes[2].Descriptor()
}

func (PhotoCardUncertaintyScope) Type() protoreflect.EnumType {
	return &file_opentrawl_photos_card_card_proto_enumTypes[2]
}

func (x PhotoCardUncertaintyScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhotoCardUncertaintyScope.Descriptor instead.
func (PhotoCardUncertaintyScope) EnumDescriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{2}
}

// PhotoCard is OpenTrawl's typed account of the current rendered photo.
// Code composes it from Luna's typed OCR and semantic responses. Capture facts
// and provider location evidence remain independent stored inputs.
type PhotoCard struct {
	state                       protoimpl.MessageState            `protogen:"open.v1"`
	Descriptions                *PhotoDescriptions                `protobuf:"bytes,1,opt,name=descriptions,proto3" json:"descriptions,omitempty"`
	PrimaryDepictedSubject      *PrimaryDepictedSubject           `protobuf:"bytes,2,opt,name=primary_depicted_subject,json=primaryDepictedSubject,proto3" json:"primary_depicted_subject,omitempty"`
	VisibleContent              *VisiblePhotoContent              `protobuf:"bytes,3,opt,name=visible_content,json=visibleContent,proto3" json:"visible_content,omitempty"`
	OpticalCharacterRecognition *PhotoOpticalCharacterRecognition `protobuf:"bytes,4,opt,name=optical_character_recognition,json=opticalCharacterRecognition,proto3" json:"optical_character_recognition,omitempty"`
	PhotographedPlace           *PhotographedPlaceJudgement       `protobuf:"bytes,5,opt,name=photographed_place,json=photographedPlace,proto3" json:"photographed_place,omitempty"`
	SearchableFacts             []string                          `protobuf:"bytes,6,rep,name=searchable_facts,json=searchableFacts,proto3" json:"searchable_facts,omitempty"`
	Uncertainties               []*PhotoCardUncertainty           `protobuf:"bytes,7,rep,name=uncertainties,proto3" json:"uncertainties,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *PhotoCard) Reset() {
	*x = PhotoCard{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoCard) ProtoMessage() {}

func (x *PhotoCard) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoCard.ProtoReflect.Descriptor instead.
func (*PhotoCard) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{0}
}

func (x *PhotoCard) GetDescriptions() *PhotoDescriptions {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

func (x *PhotoCard) GetPrimaryDepictedSubject() *PrimaryDepictedSubject {
	if x != nil {
		return x.PrimaryDepictedSubject
	}
	return nil
}

func (x *PhotoCard) GetVisibleContent() *VisiblePhotoContent {
	if x != nil {
		return x.VisibleContent
	}
	return nil
}

func (x *PhotoCard) GetOpticalCharacterRecognition() *PhotoOpticalCharacterRecognition {
	if x != nil {
		return x.OpticalCharacterRecognition
	}
	return nil
}

func (x *PhotoCard) GetPhotographedPlace() *PhotographedPlaceJudgement {
	if x != nil {
		return x.PhotographedPlace
	}
	return nil
}

func (x *PhotoCard) GetSearchableFacts() []string {
	if x != nil {
		return x.SearchableFacts
	}
	return nil
}

func (x *PhotoCard) GetUncertainties() []*PhotoCardUncertainty {
	if x != nil {
		return x.Uncertainties
	}
	return nil
}

// PhotoCardSemanticSections is Luna's second-stage judgement after literal
// visible text has already been extracted. OpenTrawl mechanically combines
// these fields with the retained OCR result to form one PhotoCard.
type PhotoCardSemanticSections struct {
	state                  protoimpl.MessageState      `protogen:"open.v1"`
	Descriptions           *PhotoDescriptions          `protobuf:"bytes,1,opt,name=descriptions,proto3" json:"descriptions,omitempty"`
	PrimaryDepictedSubject *PrimaryDepictedSubject     `protobuf:"bytes,2,opt,name=primary_depicted_subject,json=primaryDepictedSubject,proto3" json:"primary_depicted_subject,omitempty"`
	VisibleContent         *VisiblePhotoContent        `protobuf:"bytes,3,opt,name=visible_content,json=visibleContent,proto3" json:"visible_content,omitempty"`
	PhotographedPlace      *PhotographedPlaceJudgement `protobuf:"bytes,4,opt,name=photographed_place,json=photographedPlace,proto3" json:"photographed_place,omitempty"`
	SearchableFacts        []string                    `protobuf:"bytes,5,rep,name=searchable_facts,json=searchableFacts,proto3" json:"searchable_facts,omitempty"`
	Uncertainties          []*PhotoCardUncertainty     `protobuf:"bytes,6,rep,name=uncertainties,proto3" json:"uncertainties,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PhotoCardSemanticSections) Reset() {
	*x = PhotoCardSemanticSections{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoCardSemanticSections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoCardSemanticSections) ProtoMessage() {}

func (x *PhotoCardSemanticSections) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoCardSemanticSections.ProtoReflect.Descriptor instead.
func (*PhotoCardSemanticSections) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{1}
}

func (x *PhotoCardSemanticSections) GetDescriptions() *PhotoDescriptions {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

func (x *PhotoCardSemanticSections) GetPrimaryDepictedSubject() *PrimaryDepictedSubject {
	if x != nil {
		return x.PrimaryDepictedSubject
	}
	return nil
}

func (x *PhotoCardSemanticSections) GetVisibleContent() *VisiblePhotoContent {
	if x != nil {
		return x.VisibleContent
	}
	return nil
}

func (x *PhotoCardSemanticSections) GetPhotographedPlace() *PhotographedPlaceJudgement {
	if x != nil {
		return x.PhotographedPlace
	}
	return nil
}

func (x *PhotoCardSemanticSections) GetSearchableFacts() []string {
	if x != nil {
		return x.SearchableFacts
	}
	return nil
}

func (x *PhotoCardSemanticSections) GetUncertainties() []*PhotoCardUncertainty {
	if x != nil {
		return x.Uncertainties
	}
	return nil
}

type PhotoDescriptions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ConciseDescription  string                 `protobuf:"bytes,1,opt,name=concise_description,json=conciseDescription,proto3" json:"concise_description,omitempty"`
	DetailedDescription string                 `protobuf:"bytes,2,opt,name=detailed_description,json=detailedDescription,proto3" json:"detailed_description,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PhotoDescriptions) Reset() {
	*x = PhotoDescriptions{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoDescriptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoDescriptions) ProtoMessage() {}

func (x *PhotoDescriptions) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoDescriptions.ProtoReflect.Descriptor instead.
func (*PhotoDescriptions) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{2}
}

func (x *PhotoDescriptions) GetConciseDescription() string {
	if x != nil {
		return x.ConciseDescription
	}
	return ""
}

func (x *PhotoDescriptions) GetDetailedDescription() string {
	if x != nil {
		return x.DetailedDescription
	}
	return ""
}

// PrimaryDepictedSubject stores the subject a person would say the photo is of.
// It deliberately uses human language instead of a closed subject ontology.
type PrimaryDepictedSubject struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HumanName      string                 `protobuf:"bytes,1,opt,name=human_name,json=humanName,proto3" json:"human_name,omitempty"`
	VisualEvidence string                 `protobuf:"bytes,2,opt,name=visual_evidence,json=visualEvidence,proto3" json:"visual_evidence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrimaryDepictedSubject) Reset() {
	*x = PrimaryDepictedSubject{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryDepictedSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryDepictedSubject) ProtoMessage() {}

func (x *PrimaryDepictedSubject) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryDepictedSubject.ProtoReflect.Descriptor instead.
func (*PrimaryDepictedSubject) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{3}
}

func (x *PrimaryDepictedSubject) GetHumanName() string {
	if x != nil {
		return x.HumanName
	}
	return ""
}

func (x *PrimaryDepictedSubject) GetVisualEvidence() string {
	if x != nil {
		return x.VisualEvidence
	}
	return ""
}

type VisiblePhotoContent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Scene            string                 `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	People           []*VisiblePerson       `protobuf:"bytes,2,rep,name=people,proto3" json:"people,omitempty"`
	ImportantObjects []string               `protobuf:"bytes,3,rep,name=important_objects,json=importantObjects,proto3" json:"important_objects,omitempty"`
	VisibleActions   []string               `protobuf:"bytes,4,rep,name=visible_actions,json=visibleActions,proto3" json:"visible_actions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VisiblePhotoContent) Reset() {
	*x = VisiblePhotoContent{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisiblePhotoContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisiblePhotoContent) ProtoMessage() {}

func (x *VisiblePhotoContent) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisiblePhotoContent.ProtoReflect.Descriptor instead.
func (*VisiblePhotoContent) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{4}
}

func (x *VisiblePhotoContent) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *VisiblePhotoContent) GetPeople() []*VisiblePerson {
	if x != nil {
		return x.People
	}
	return nil
}

func (x *VisiblePhotoContent) GetImportantObjects() []string {
	if x != nil {
		return x.ImportantObjects
	}
	return nil
}

func (x *VisiblePhotoContent) GetVisibleActions() []string {
	if x != nil {
		return x.VisibleActions
	}
	return nil
}

type VisiblePerson struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	VisiblePositionOrRole string                 `protobuf:"bytes,1,opt,name=visible_position_or_role,json=visiblePositionOrRole,proto3" json:"visible_position_or_role,omitempty"`
	VisibleAppearance     string                 `protobuf:"bytes,2,opt,name=visible_appearance,json=visibleAppearance,proto3" json:"visible_appearance,omitempty"`
	VisibleActionOrPose   string                 `protobuf:"bytes,3,opt,name=visible_action_or_pose,json=visibleActionOrPose,proto3" json:"visible_action_or_pose,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VisiblePerson) Reset() {
	*x = VisiblePerson{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisiblePerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisiblePerson) ProtoMessage() {}

func (x *VisiblePerson) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisiblePerson.ProtoReflect.Descriptor instead.
func (*VisiblePerson) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{5}
}

func (x *VisiblePerson) GetVisiblePositionOrRole() string {
	if x != nil {
		return x.VisiblePositionOrRole
	}
	return ""
}

func (x *VisiblePerson) GetVisibleAppearance() string {
	if x != nil {
		return x.VisibleAppearance
	}
	return ""
}

func (x *VisiblePerson) GetVisibleActionOrPose() string {
	if x != nil {
		return x.VisibleActionOrPose
	}
	return ""
}

type PhotoOpticalCharacterRecognition struct {
	state                 protoimpl.MessageState                    `protogen:"open.v1"`
	RegionsInReadingOrder []*OpticalCharacterRecognitionRegion      `protobuf:"bytes,1,rep,name=regions_in_reading_order,json=regionsInReadingOrder,proto3" json:"regions_in_reading_order,omitempty"`
	KeyValueFields        []*OpticalCharacterRecognitionKeyValue    `protobuf:"bytes,2,rep,name=key_value_fields,json=keyValueFields,proto3" json:"key_value_fields,omitempty"`
	Tables                []*OpticalCharacterRecognitionTable       `protobuf:"bytes,3,rep,name=tables,proto3" json:"tables,omitempty"`
	Uncertainties         []*OpticalCharacterRecognitionUncertainty `protobuf:"bytes,4,rep,name=uncertainties,proto3" json:"uncertainties,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PhotoOpticalCharacterRecognition) Reset() {
	*x = PhotoOpticalCharacterRecognition{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoOpticalCharacterRecognition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoOpticalCharacterRecognition) ProtoMessage() {}

func (x *PhotoOpticalCharacterRecognition) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoOpticalCharacterRecognition.ProtoReflect.Descriptor instead.
func (*PhotoOpticalCharacterRecognition) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{6}
}

func (x *PhotoOpticalCharacterRecognition) GetRegionsInReadingOrder() []*OpticalCharacterRecognitionRegion {
	if x != nil {
		return x.RegionsInReadingOrder
	}
	return nil
}

func (x *PhotoOpticalCharacterRecognition) GetKeyValueFields() []*OpticalCharacterRecognitionKeyValue {
	if x != nil {
		return x.KeyValueFields
	}
	return nil
}

func (x *PhotoOpticalCharacterRecognition) GetTables() []*OpticalCharacterRecognitionTable {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *PhotoOpticalCharacterRecognition) GetUncertainties() []*OpticalCharacterRecognitionUncertainty {
	if x != nil {
		return x.Uncertainties
	}
	return nil
}

type OpticalCharacterRecognitionRegion struct {
	state               protoimpl.MessageState             `protogen:"open.v1"`
	VisibleSource       string                             `protobuf:"bytes,1,opt,name=visible_source,json=visibleSource,proto3" json:"visible_source,omitempty"`
	LinesInReadingOrder []*OpticalCharacterRecognitionLine `protobuf:"bytes,2,rep,name=lines_in_reading_order,json=linesInReadingOrder,proto3" json:"lines_in_reading_order,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OpticalCharacterRecognitionRegion) Reset() {
	*x = OpticalCharacterRecognitionRegion{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpticalCharacterRecognitionRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpticalCharacterRecognitionRegion) ProtoMessage() {}

func (x *OpticalCharacterRecognitionRegion) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpticalCharacterRecognitionRegion.ProtoReflect.Descriptor instead.
func (*OpticalCharacterRecognitionRegion) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{7}
}

func (x *OpticalCharacterRecognitionRegion) GetVisibleSource() string {
	if x != nil {
		return x.VisibleSource
	}
	return ""
}

func (x *OpticalCharacterRecognitionRegion) GetLinesInReadingOrder() []*OpticalCharacterRecognitionLine {
	if x != nil {
		return x.LinesInReadingOrder
	}
	return nil
}

type OpticalCharacterRecognitionLine struct {
	state           protoimpl.MessageState                `protogen:"open.v1"`
	TranscribedText string                                `protobuf:"bytes,1,opt,name=transcribed_text,json=transcribedText,proto3" json:"transcribed_text,omitempty"`
	Languages       []string                              `protobuf:"bytes,2,rep,name=languages,proto3" json:"languages,omitempty"`
	Legibility      OpticalCharacterRecognitionLegibility `protobuf:"varint,3,opt,name=legibility,proto3,enum=opentrawl.photos.card.OpticalCharacterRecognitionLegibility" json:"legibility,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OpticalCharacterRecognitionLine) Reset() {
	*x = OpticalCharacterRecognitionLine{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpticalCharacterRecognitionLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpticalCharacterRecognitionLine) ProtoMessage() {}

func (x *OpticalCharacterRecognitionLine) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpticalCharacterRecognitionLine.ProtoReflect.Descriptor instead.
func (*OpticalCharacterRecognitionLine) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{8}
}

func (x *OpticalCharacterRecognitionLine) GetTranscribedText() string {
	if x != nil {
		return x.TranscribedText
	}
	return ""
}

func (x *OpticalCharacterRecognitionLine) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *OpticalCharacterRecognitionLine) GetLegibility() OpticalCharacterRecognitionLegibility {
	if x != nil {
		return x.Legibility
	}
	return OpticalCharacterRecognitionLegibility_OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_UNSPECIFIED
}

type OpticalCharacterRecognitionKeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	VisibleSource string                 `protobuf:"bytes,3,opt,name=visible_source,json=visibleSource,proto3" json:"visible_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpticalCharacterRecognitionKeyValue) Reset() {
	*x = OpticalCharacterRecognitionKeyValue{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpticalCharacterRecognitionKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpticalCharacterRecognitionKeyValue) ProtoMessage() {}

func (x *OpticalCharacterRecognitionKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpticalCharacterRecognitionKeyValue.ProtoReflect.Descriptor instead.
func (*OpticalCharacterRecognitionKeyValue) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{9}
}

func (x *OpticalCharacterRecognitionKeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OpticalCharacterRecognitionKeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OpticalCharacterRecognitionKeyValue) GetVisibleSource() string {
	if x != nil {
		return x.VisibleSource
	}
	return ""
}

type OpticalCharacterRecognitionTable struct {
	state              protoimpl.MessageState                 `protogen:"open.v1"`
	VisibleSource      string                                 `protobuf:"bytes,1,opt,name=visible_source,json=visibleSource,proto3" json:"visible_source,omitempty"`
	RowsInReadingOrder []*OpticalCharacterRecognitionTableRow `protobuf:"bytes,2,rep,name=rows_in_reading_order,json=rowsInReadingOrder,proto3" json:"rows_in_reading_order,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OpticalCharacterRecognitionTable) Reset() {
	*x = OpticalCharacterRecognitionTable{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpticalCharacterRecognitionTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpticalCharacterRecognitionTable) ProtoMessage() {}

func (x *OpticalCharacterRecognitionTable) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpticalCharacterRecognitionTable.ProtoReflect.Descriptor instead.
func (*OpticalCharacterRecognitionTable) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{10}
}

func (x *OpticalCharacterRecognitionTable) GetVisibleSource() string {
	if x != nil {
		return x.VisibleSource
	}
	return ""
}

func (x *OpticalCharacterRecognitionTable) GetRowsInReadingOrder() []*OpticalCharacterRecognitionTableRow {
	if x != nil {
		return x.RowsInReadingOrder
	}
	return nil
}

type OpticalCharacterRecognitionTableRow struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CellsInReadingOrder []string               `protobuf:"bytes,1,rep,name=cells_in_reading_order,json=cellsInReadingOrder,proto3" json:"cells_in_reading_order,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OpticalCharacterRecognitionTableRow) Reset() {
	*x = OpticalCharacterRecognitionTableRow{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpticalCharacterRecognitionTableRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpticalCharacterRecognitionTableRow) ProtoMessage() {}

func (x *OpticalCharacterRecognitionTableRow) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpticalCharacterRecognitionTableRow.ProtoReflect.Descriptor instead.
func (*OpticalCharacterRecognitionTableRow) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{11}
}

func (x *OpticalCharacterRecognitionTableRow) GetCellsInReadingOrder() []string {
	if x != nil {
		return x.CellsInReadingOrder
	}
	return nil
}

type OpticalCharacterRecognitionUncertainty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisibleSource string                 `protobuf:"bytes,1,opt,name=visible_source,json=visibleSource,proto3" json:"visible_source,omitempty"`
	Explanation   string                 `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpticalCharacterRecognitionUncertainty) Reset() {
	*x = OpticalCharacterRecognitionUncertainty{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpticalCharacterRecognitionUncertainty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpticalCharacterRecognitionUncertainty) ProtoMessage() {}

func (x *OpticalCharacterRecognitionUncertainty) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpticalCharacterRecognitionUncertainty.ProtoReflect.Descriptor instead.
func (*OpticalCharacterRecognitionUncertainty) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{12}
}

func (x *OpticalCharacterRecognitionUncertainty) GetVisibleSource() string {
	if x != nil {
		return x.VisibleSource
	}
	return ""
}

func (x *OpticalCharacterRecognitionUncertainty) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type PhotographedPlaceJudgement struct {
	state                      protoimpl.MessageState                `protogen:"open.v1"`
	Certainty                  PhotographedPlaceCertainty            `protobuf:"varint,1,opt,name=certainty,proto3,enum=opentrawl.photos.card.PhotographedPlaceCertainty" json:"certainty,omitempty"`
	SelectedSuppliedCandidates []*SuppliedPhotographedPlaceCandidate `protobuf:"bytes,2,rep,name=selected_supplied_candidates,json=selectedSuppliedCandidates,proto3" json:"selected_supplied_candidates,omitempty"`
	ImageInferredPlaces        []*ImageInferredPhotographedPlace     `protobuf:"bytes,3,rep,name=image_inferred_places,json=imageInferredPlaces,proto3" json:"image_inferred_places,omitempty"`
	Explanation                string                                `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *PhotographedPlaceJudgement) Reset() {
	*x = PhotographedPlaceJudgement{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotographedPlaceJudgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotographedPlaceJudgement) ProtoMessage() {}

func (x *PhotographedPlaceJudgement) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotographedPlaceJudgement.ProtoReflect.Descriptor instead.
func (*PhotographedPlaceJudgement) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{13}
}

func (x *PhotographedPlaceJudgement) GetCertainty() PhotographedPlaceCertainty {
	if x != nil {
		return x.Certainty
	}
	return PhotographedPlaceCertainty_PHOTOGRAPHED_PLACE_CERTAINTY_UNSPECIFIED
}

func (x *PhotographedPlaceJudgement) GetSelectedSuppliedCandidates() []*SuppliedPhotographedPlaceCandidate {
	if x != nil {
		return x.SelectedSuppliedCandidates
	}
	return nil
}

func (x *PhotographedPlaceJudgement) GetImageInferredPlaces() []*ImageInferredPhotographedPlace {
	if x != nil {
		return x.ImageInferredPlaces
	}
	return nil
}

func (x *PhotographedPlaceJudgement) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type SuppliedPhotographedPlaceCandidate struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	SuppliedCandidateIdentifier string                 `protobuf:"bytes,1,opt,name=supplied_candidate_identifier,json=suppliedCandidateIdentifier,proto3" json:"supplied_candidate_identifier,omitempty"`
	HumanName                   string                 `protobuf:"bytes,2,opt,name=human_name,json=humanName,proto3" json:"human_name,omitempty"`
	Evidence                    string                 `protobuf:"bytes,3,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SuppliedPhotographedPlaceCandidate) Reset() {
	*x = SuppliedPhotographedPlaceCandidate{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuppliedPhotographedPlaceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuppliedPhotographedPlaceCandidate) ProtoMessage() {}

func (x *SuppliedPhotographedPlaceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuppliedPhotographedPlaceCandidate.ProtoReflect.Descriptor instead.
func (*SuppliedPhotographedPlaceCandidate) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{14}
}

func (x *SuppliedPhotographedPlaceCandidate) GetSuppliedCandidateIdentifier() string {
	if x != nil {
		return x.SuppliedCandidateIdentifier
	}
	return ""
}

func (x *SuppliedPhotographedPlaceCandidate) GetHumanName() string {
	if x != nil {
		return x.HumanName
	}
	return ""
}

func (x *SuppliedPhotographedPlaceCandidate) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

type ImageInferredPhotographedPlace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HumanName     string                 `protobuf:"bytes,1,opt,name=human_name,json=humanName,proto3" json:"human_name,omitempty"`
	Evidence      string                 `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInferredPhotographedPlace) Reset() {
	*x = ImageInferredPhotographedPlace{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInferredPhotographedPlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInferredPhotographedPlace) ProtoMessage() {}

func (x *ImageInferredPhotographedPlace) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInferredPhotographedPlace.ProtoReflect.Descriptor instead.
func (*ImageInferredPhotographedPlace) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{15}
}

func (x *ImageInferredPhotographedPlace) GetHumanName() string {
	if x != nil {
		return x.HumanName
	}
	return ""
}

func (x *ImageInferredPhotographedPlace) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

type PhotoCardUncertainty struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Scope         PhotoCardUncertaintyScope `protobuf:"varint,1,opt,name=scope,proto3,enum=opentrawl.photos.card.PhotoCardUncertaintyScope" json:"scope,omitempty"`
	Subject       string                    `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Explanation   string                    `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoCardUncertainty) Reset() {
	*x = PhotoCardUncertainty{}
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoCardUncertainty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoCardUncertainty) ProtoMessage() {}

func (x *PhotoCardUncertainty) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_card_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoCardUncertainty.ProtoReflect.Descriptor instead.
func (*PhotoCardUncertainty) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_card_proto_rawDescGZIP(), []int{16}
}

func (x *PhotoCardUncertainty) GetScope() PhotoCardUncertaintyScope {
	if x != nil {
		return x.Scope
	}
	return PhotoCardUncertaintyScope_PHOTO_CARD_UNCERTAINTY_SCOPE_UNSPECIFIED
}

func (x *PhotoCardUncertainty) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PhotoCardUncertainty) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_opentrawl_photos_card_card_proto protoreflect.FileDescriptor

const file_opentrawl_photos_card_card_proto_rawDesc = "" +
	"\n" +
	" opentrawl/photos/card/card.proto\x12\x15opentrawl.photos.card\"\xf4\x04\n" +
	"\tPhotoCard\x12L\n" +
	"\fdescriptions\x18\x01 \x01(\v2(.opentrawl.photos.card.PhotoDescriptionsR\fdescriptions\x12g\n" +
	"\x18primary_depicted_subject\x18\x02 \x01(\v2-.opentrawl.photos.card.PrimaryDepictedSubjectR\x16primaryDepictedSubject\x12S\n" +
	"\x0fvisible_content\x18\x03 \x01(\v2*.opentrawl.photos.card.VisiblePhotoContentR\x0evisibleContent\x12{\n" +
	"\x1doptical_character_recognition\x18\x04 \x01(\v27.opentrawl.photos.card.PhotoOpticalCharacterRecognitionR\x1bopticalCharacterRecognition\x12`\n" +
	"\x12photographed_place\x18\x05 \x01(\v21.opentrawl.photos.card.PhotographedPlaceJudgementR\x11photographedPlace\x12)\n" +
	"\x10searchable_facts\x18\x06 \x03(\tR\x0fsearchableFacts\x12Q\n" +
	"\runcertainties\x18\a \x03(\v2+.opentrawl.photos.card.PhotoCardUncertaintyR\runcertainties\"\x87\x04\n" +
	"\x19PhotoCardSemanticSections\x12L\n" +
	"\fdescriptions\x18\x01 \x01(\v2(.opentrawl.photos.card.PhotoDescriptionsR\fdescriptions\x12g\n" +
	"\x18primary_depicted_subject\x18\x02 \x01(\v2-.opentrawl.photos.card.PrimaryDepictedSubjectR\x16primaryDepictedSubject\x12S\n" +
	"\x0fvisible_content\x18\x03 \x01(\v2*.opentrawl.photos.card.VisiblePhotoContentR\x0evisibleContent\x12`\n" +
	"\x12photographed_place\x18\x04 \x01(\v21.opentrawl.photos.card.PhotographedPlaceJudgementR\x11photographedPlace\x12)\n" +
	"\x10searchable_facts\x18\x05 \x03(\tR\x0fsearchableFacts\x12Q\n" +
	"\runcertainties\x18\x06 \x03(\v2+.opentrawl.photos.card.PhotoCardUncertaintyR\runcertainties\"w\n" +
	"\x11PhotoDescriptions\x12/\n" +
	"\x13concise_description\x18\x01 \x01(\tR\x12conciseDescription\x121\n" +
	"\x14detailed_description\x18\x02 \x01(\tR\x13detailedDescription\"`\n" +
	"\x16PrimaryDepictedSubject\x12\x1d\n" +
	"\n" +
	"human_name\x18\x01 \x01(\tR\thumanName\x12'\n" +
	"\x0fvisual_evidence\x18\x02 \x01(\tR\x0evisualEvidence\"\xbf\x01\n" +
	"\x13VisiblePhotoContent\x12\x14\n" +
	"\x05scene\x18\x01 \x01(\tR\x05scene\x12<\n" +
	"\x06people\x18\x02 \x03(\v2$.opentrawl.photos.card.VisiblePersonR\x06people\x12+\n" +
	"\x11important_objects\x18\x03 \x03(\tR\x10importantObjects\x12'\n" +
	"\x0fvisible_actions\x18\x04 \x03(\tR\x0evisibleActions\"\xac\x01\n" +
	"\rVisiblePerson\x127\n" +
	"\x18visible_position_or_role\x18\x01 \x01(\tR\x15visiblePositionOrRole\x12-\n" +
	"\x12visible_appearance\x18\x02 \x01(\tR\x11visibleAppearance\x123\n" +
	"\x16visible_action_or_pose\x18\x03 \x01(\tR\x13visibleActionOrPose\"\xb1\x03\n" +
	" PhotoOpticalCharacterRecognition\x12q\n" +
	"\x18regions_in_reading_order\x18\x01 \x03(\v28.opentrawl.photos.card.OpticalCharacterRecognitionRegionR\x15regionsInReadingOrder\x12d\n" +
	"\x10key_value_fields\x18\x02 \x03(\v2:.opentrawl.photos.card.OpticalCharacterRecognitionKeyValueR\x0ekeyValueFields\x12O\n" +
	"\x06tables\x18\x03 \x03(\v27.opentrawl.photos.card.OpticalCharacterRecognitionTableR\x06tables\x12c\n" +
	"\runcertainties\x18\x04 \x03(\v2=.opentrawl.photos.card.OpticalCharacterRecognitionUncertaintyR\runcertainties\"\xb7\x01\n" +
	"!OpticalCharacterRecognitionRegion\x12%\n" +
	"\x0evisible_source\x18\x01 \x01(\tR\rvisibleSource\x12k\n" +
	"\x16lines_in_reading_order\x18\x02 \x03(\v26.opentrawl.photos.card.OpticalCharacterRecognitionLineR\x13linesInReadingOrder\"\xc8\x01\n" +
	"\x1fOpticalCharacterRecognitionLine\x12)\n" +
	"\x10transcribed_text\x18\x01 \x01(\tR\x0ftranscribedText\x12\x1c\n" +
	"\tlanguages\x18\x02 \x03(\tR\tlanguages\x12\\\n" +
	"\n" +
	"legibility\x18\x03 \x01(\x0e2<.opentrawl.photos.card.OpticalCharacterRecognitionLegibilityR\n" +
	"legibility\"t\n" +
	"#OpticalCharacterRecognitionKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12%\n" +
	"\x0evisible_source\x18\x03 \x01(\tR\rvisibleSource\"\xb8\x01\n" +
	" OpticalCharacterRecognitionTable\x12%\n" +
	"\x0evisible_source\x18\x01 \x01(\tR\rvisibleSource\x12m\n" +
	"\x15rows_in_reading_order\x18\x02 \x03(\v2:.opentrawl.photos.card.OpticalCharacterRecognitionTableRowR\x12rowsInReadingOrder\"Z\n" +
	"#OpticalCharacterRecognitionTableRow\x123\n" +
	"\x16cells_in_reading_order\x18\x01 \x03(\tR\x13cellsInReadingOrder\"q\n" +
	"&OpticalCharacterRecognitionUncertainty\x12%\n" +
	"\x0evisible_source\x18\x01 \x01(\tR\rvisibleSource\x12 \n" +
	"\vexplanation\x18\x02 \x01(\tR\vexplanation\"\xf7\x02\n" +
	"\x1aPhotographedPlaceJudgement\x12O\n" +
	"\tcertainty\x18\x01 \x01(\x0e21.opentrawl.photos.card.PhotographedPlaceCertaintyR\tcertainty\x12{\n" +
	"\x1cselected_supplied_candidates\x18\x02 \x03(\v29.opentrawl.photos.card.SuppliedPhotographedPlaceCandidateR\x1aselectedSuppliedCandidates\x12i\n" +
	"\x15image_inferred_places\x18\x03 \x03(\v25.opentrawl.photos.card.ImageInferredPhotographedPlaceR\x13imageInferredPlaces\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\"\xa3\x01\n" +
	"\"SuppliedPhotographedPlaceCandidate\x12B\n" +
	"\x1dsupplied_candidate_identifier\x18\x01 \x01(\tR\x1bsuppliedCandidateIdentifier\x12\x1d\n" +
	"\n" +
	"human_name\x18\x02 \x01(\tR\thumanName\x12\x1a\n" +
	"\bevidence\x18\x03 \x01(\tR\bevidence\"[\n" +
	"\x1eImageInferredPhotographedPlace\x12\x1d\n" +
	"\n" +
	"human_name\x18\x01 \x01(\tR\thumanName\x12\x1a\n" +
	"\bevidence\x18\x02 \x01(\tR\bevidence\"\x9a\x01\n" +
	"\x14PhotoCardUncertainty\x12F\n" +
	"\x05scope\x18\x01 \x01(\x0e20.opentrawl.photos.card.PhotoCardUncertaintyScopeR\x05scope\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation*\x81\x02\n" +
	"%OpticalCharacterRecognitionLegibility\x128\n" +
	"4OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_UNSPECIFIED\x10\x00\x122\n" +
	".OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_CLEAR\x10\x01\x124\n" +
	"0OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_PARTIAL\x10\x02\x124\n" +
	"0OPTICAL_CHARACTER_RECOGNITION_LEGIBILITY_UNCLEAR\x10\x03*\xcc\x01\n" +
	"\x1aPhotographedPlaceCertainty\x12,\n" +
	"(PHOTOGRAPHED_PLACE_CERTAINTY_UNSPECIFIED\x10\x00\x12+\n" +
	"'PHOTOGRAPHED_PLACE_CERTAINTY_IDENTIFIED\x10\x01\x12)\n" +
	"%PHOTOGRAPHED_PLACE_CERTAINTY_POSSIBLE\x10\x02\x12(\n" +
	"$PHOTOGRAPHED_PLACE_CERTAINTY_UNKNOWN\x10\x03*\x9e\x02\n" +
	"\x19PhotoCardUncertaintyScope\x12,\n" +
	"(PHOTO_CARD_UNCERTAINTY_SCOPE_UNSPECIFIED\x10\x00\x12,\n" +
	"(PHOTO_CARD_UNCERTAINTY_SCOPE_DESCRIPTION\x10\x01\x120\n" +
	",PHOTO_CARD_UNCERTAINTY_SCOPE_VISIBLE_CONTENT\x10\x02\x12>\n" +
	":PHOTO_CARD_UNCERTAINTY_SCOPE_OPTICAL_CHARACTER_RECOGNITION\x10\x03\x123\n" +
	"/PHOTO_CARD_UNCERTAINTY_SCOPE_PHOTOGRAPHED_PLACE\x10\x04BUZSgithub.com/opentrawl/opentrawl/trawlers/photos/proto/opentrawl/photos/card;cardwireb\x06proto3"

var (
	file_opentrawl_photos_card_card_proto_rawDescOnce sync.Once
	file_opentrawl_photos_card_card_proto_rawDescData []byte
)

func file_opentrawl_photos_card_card_proto_rawDescGZIP() []byte {
	file_opentrawl_photos_card_card_proto_rawDescOnce.Do(func() {
		file_opentrawl_photos_card_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opentrawl_photos_card_card_proto_rawDesc), len(file_opentrawl_photos_card_card_proto_rawDesc)))
	})
	return file_opentrawl_photos_card_card_proto_rawDescData
}

var file_opentrawl_photos_card_card_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_opentrawl_photos_card_card_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_opentrawl_photos_card_card_proto_goTypes = []any{
	(OpticalCharacterRecognitionLegibility)(0),     // 0: opentrawl.photos.card.OpticalCharacterRecognitionLegibility
	(PhotographedPlaceCertainty)(0),                // 1: opentrawl.photos.card.PhotographedPlaceCertainty
	(PhotoCardUncertaintyScope)(0),                 // 2: opentrawl.photos.card.PhotoCardUncertaintyScope
	(*PhotoCard)(nil),                              // 3: opentrawl.photos.card.PhotoCard
	(*PhotoCardSemanticSections)(nil),              // 4: opentrawl.photos.card.PhotoCardSemanticSections
	(*PhotoDescriptions)(nil),                      // 5: opentrawl.photos.card.PhotoDescriptions
	(*PrimaryDepictedSubject)(nil),                 // 6: opentrawl.photos.card.PrimaryDepictedSubject
	(*VisiblePhotoContent)(nil),                    // 7: opentrawl.photos.card.VisiblePhotoContent
	(*VisiblePerson)(nil),                          // 8: opentrawl.photos.card.VisiblePerson
	(*PhotoOpticalCharacterRecognition)(nil),       // 9: opentrawl.photos.card.PhotoOpticalCharacterRecognition
	(*OpticalCharacterRecognitionRegion)(nil),      // 10: opentrawl.photos.card.OpticalCharacterRecognitionRegion
	(*OpticalCharacterRecognitionLine)(nil),        // 11: opentrawl.photos.card.OpticalCharacterRecognitionLine
	(*OpticalCharacterRecognitionKeyValue)(nil),    // 12: opentrawl.photos.card.OpticalCharacterRecognitionKeyValue
	(*OpticalCharacterRecognitionTable)(nil),       // 13: opentrawl.photos.card.OpticalCharacterRecognitionTable
	(*OpticalCharacterRecognitionTableRow)(nil),    // 14: opentrawl.photos.card.OpticalCharacterRecognitionTableRow
	(*OpticalCharacterRecognitionUncertainty)(nil), // 15: opentrawl.photos.card.OpticalCharacterRecognitionUncertainty
	(*PhotographedPlaceJudgement)(nil),             // 16: opentrawl.photos.card.PhotographedPlaceJudgement
	(*SuppliedPhotographedPlaceCandidate)(nil),     // 17: opentrawl.photos.card.SuppliedPhotographedPlaceCandidate
	(*ImageInferredPhotographedPlace)(nil),         // 18: opentrawl.photos.card.ImageInferredPhotographedPlace
	(*PhotoCardUncertainty)(nil),                   // 19: opentrawl.photos.card.PhotoCardUncertainty
}
var file_opentrawl_photos_card_card_proto_depIdxs = []int32{
	5,  // 0: opentrawl.photos.card.PhotoCard.descriptions:type_name -> opentrawl.photos.card.PhotoDescriptions
	6,  // 1: opentrawl.photos.card.PhotoCard.primary_depicted_subject:type_name -> opentrawl.photos.card.PrimaryDepictedSubject
	7,  // 2: opentrawl.photos.card.PhotoCard.visible_content:type_name -> opentrawl.photos.card.VisiblePhotoContent
	9,  // 3: opentrawl.photos.card.PhotoCard.optical_character_recognition:type_name -> opentrawl.photos.card.PhotoOpticalCharacterRecognition
	16, // 4: opentrawl.photos.card.PhotoCard.photographed_place:type_name -> opentrawl.photos.card.PhotographedPlaceJudgement
	19, // 5: opentrawl.photos.card.PhotoCard.uncertainties:type_name -> opentrawl.photos.card.PhotoCardUncertainty
	5,  // 6: opentrawl.photos.card.PhotoCardSemanticSections.descriptions:type_name -> opentrawl.photos.card.PhotoDescriptions
	6,  // 7: opentrawl.photos.card.PhotoCardSemanticSections.primary_depicted_subject:type_name -> opentrawl.photos.card.PrimaryDepictedSubject
	7,  // 8: opentrawl.photos.card.PhotoCardSemanticSections.visible_content:type_name -> opentrawl.photos.card.VisiblePhotoContent
	16, // 9: opentrawl.photos.card.PhotoCardSemanticSections.photographed_place:type_name -> opentrawl.photos.card.PhotographedPlaceJudgement
	19, // 10: opentrawl.photos.card.PhotoCardSemanticSections.uncertainties:type_name -> opentrawl.photos.card.PhotoCardUncertainty
	8,  // 11: opentrawl.photos.card.VisiblePhotoContent.people:type_name -> opentrawl.photos.card.VisiblePerson
	10, // 12: opentrawl.photos.card.PhotoOpticalCharacterRecognition.regions_in_reading_order:type_name -> opentrawl.photos.card.OpticalCharacterRecognitionRegion
	12, // 13: opentrawl.photos.card.PhotoOpticalCharacterRecognition.key_value_fields:type_name -> opentrawl.photos.card.OpticalCharacterRecognitionKeyValue
	13, // 14: opentrawl.photos.card.PhotoOpticalCharacterRecognition.tables:type_name -> opentrawl.photos.card.OpticalCharacterRecognitionTable
	15, // 15: opentrawl.photos.card.PhotoOpticalCharacterRecognition.uncertainties:type_name -> opentrawl.photos.card.OpticalCharacterRecognitionUncertainty
	11, // 16: opentrawl.photos.card.OpticalCharacterRecognitionRegion.lines_in_reading_order:type_name -> opentrawl.photos.card.OpticalCharacterRecognitionLine
	0,  // 17: opentrawl.photos.card.OpticalCharacterRecognitionLine.legibility:type_name -> opentrawl.photos.card.OpticalCharacterRecognitionLegibility
	14, // 18: opentrawl.photos.card.OpticalCharacterRecognitionTable.rows_in_reading_order:type_name -> opentrawl.photos.card.OpticalCharacterRecognitionTableRow
	1,  // 19: opentrawl.photos.card.PhotographedPlaceJudgement.certainty:type_name -> opentrawl.photos.card.PhotographedPlaceCertainty
	17, // 20: opentrawl.photos.card.PhotographedPlaceJudgement.selected_supplied_candidates:type_name -> opentrawl.photos.card.SuppliedPhotographedPlaceCandidate
	18, // 21: opentrawl.photos.card.PhotographedPlaceJudgement.image_inferred_places:type_name -> opentrawl.photos.card.ImageInferredPhotographedPlace
	2,  // 22: opentrawl.photos.card.PhotoCardUncertainty.scope:type_name -> opentrawl.photos.card.PhotoCardUncertaintyScope
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_opentrawl_photos_card_card_proto_init() }
func file_opentrawl_photos_card_card_proto_init() {
	if File_opentrawl_photos_card_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opentrawl_photos_card_card_proto_rawDesc), len(file_opentrawl_photos_card_card_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opentrawl_photos_card_card_proto_goTypes,
		DependencyIndexes: file_opentrawl_photos_card_card_proto_depIdxs,
		EnumInfos:         file_opentrawl_photos_card_card_proto_enumTypes,
		MessageInfos:      file_opentrawl_photos_card_card_proto_msgTypes,
	}.Build()
	File_opentrawl_photos_card_card_proto = out.File
	file_opentrawl_photos_card_card_proto_goTypes = nil
	file_opentrawl_photos_card_card_proto_depIdxs = nil
}
