// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: opentrawl/photos/card/v1/card.proto

package cardwire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CardInput contains only checked facts consumed by the photo-card model.
// Custody, source and execution fields belong outside this content identity.
type CardInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion     uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CaptureTime       string                 `protobuf:"bytes,2,opt,name=capture_time,json=captureTime,proto3" json:"capture_time,omitempty"`
	Timezone          *string                `protobuf:"bytes,3,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	MediaType         string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	MediaSubtypes     []string               `protobuf:"bytes,5,rep,name=media_subtypes,json=mediaSubtypes,proto3" json:"media_subtypes,omitempty"`
	PixelWidth        int64                  `protobuf:"varint,6,opt,name=pixel_width,json=pixelWidth,proto3" json:"pixel_width,omitempty"`
	PixelHeight       int64                  `protobuf:"varint,7,opt,name=pixel_height,json=pixelHeight,proto3" json:"pixel_height,omitempty"`
	DurationSeconds   float64                `protobuf:"fixed64,8,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	ImmutableOriginal *ImmutableOriginal     `protobuf:"bytes,9,opt,name=immutable_original,json=immutableOriginal,proto3" json:"immutable_original,omitempty"`
	Favorite          bool                   `protobuf:"varint,10,opt,name=favorite,proto3" json:"favorite,omitempty"`
	Hidden            bool                   `protobuf:"varint,11,opt,name=hidden,proto3" json:"hidden,omitempty"`
	BurstMember       bool                   `protobuf:"varint,12,opt,name=burst_member,json=burstMember,proto3" json:"burst_member,omitempty"`
	Albums            []*Album               `protobuf:"bytes,13,rep,name=albums,proto3" json:"albums,omitempty"`
	Location          *Location              `protobuf:"bytes,14,opt,name=location,proto3" json:"location,omitempty"`
	KnownPlace        *KnownPlace            `protobuf:"bytes,15,opt,name=known_place,json=knownPlace,proto3" json:"known_place,omitempty"`
	Camera            *Camera                `protobuf:"bytes,16,opt,name=camera,proto3" json:"camera,omitempty"`
	Metadata          *Metadata              `protobuf:"bytes,17,opt,name=metadata,proto3" json:"metadata,omitempty"`
	FullCurrent       *FullCurrent           `protobuf:"bytes,18,opt,name=full_current,json=fullCurrent,proto3" json:"full_current,omitempty"`
	Places            []*PlaceProjection     `protobuf:"bytes,19,rep,name=places,proto3" json:"places,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CardInput) Reset() {
	*x = CardInput{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInput) ProtoMessage() {}

func (x *CardInput) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInput.ProtoReflect.Descriptor instead.
func (*CardInput) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{0}
}

func (x *CardInput) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *CardInput) GetCaptureTime() string {
	if x != nil {
		return x.CaptureTime
	}
	return ""
}

func (x *CardInput) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *CardInput) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *CardInput) GetMediaSubtypes() []string {
	if x != nil {
		return x.MediaSubtypes
	}
	return nil
}

func (x *CardInput) GetPixelWidth() int64 {
	if x != nil {
		return x.PixelWidth
	}
	return 0
}

func (x *CardInput) GetPixelHeight() int64 {
	if x != nil {
		return x.PixelHeight
	}
	return 0
}

func (x *CardInput) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *CardInput) GetImmutableOriginal() *ImmutableOriginal {
	if x != nil {
		return x.ImmutableOriginal
	}
	return nil
}

func (x *CardInput) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

func (x *CardInput) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *CardInput) GetBurstMember() bool {
	if x != nil {
		return x.BurstMember
	}
	return false
}

func (x *CardInput) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

func (x *CardInput) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CardInput) GetKnownPlace() *KnownPlace {
	if x != nil {
		return x.KnownPlace
	}
	return nil
}

func (x *CardInput) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

func (x *CardInput) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CardInput) GetFullCurrent() *FullCurrent {
	if x != nil {
		return x.FullCurrent
	}
	return nil
}

func (x *CardInput) GetPlaces() []*PlaceProjection {
	if x != nil {
		return x.Places
	}
	return nil
}

type ImmutableOriginal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Uti           string                 `protobuf:"bytes,2,opt,name=uti,proto3" json:"uti,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Availability  string                 `protobuf:"bytes,4,opt,name=availability,proto3" json:"availability,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImmutableOriginal) Reset() {
	*x = ImmutableOriginal{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImmutableOriginal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImmutableOriginal) ProtoMessage() {}

func (x *ImmutableOriginal) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImmutableOriginal.ProtoReflect.Descriptor instead.
func (*ImmutableOriginal) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{1}
}

func (x *ImmutableOriginal) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ImmutableOriginal) GetUti() string {
	if x != nil {
		return x.Uti
	}
	return ""
}

func (x *ImmutableOriginal) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImmutableOriginal) GetAvailability() string {
	if x != nil {
		return x.Availability
	}
	return ""
}

func (x *ImmutableOriginal) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ImmutableOriginal) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{2}
}

func (x *Album) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Album) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Location struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Latitude                 float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude                float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	HorizontalAccuracyMeters *float64               `protobuf:"fixed64,3,opt,name=horizontal_accuracy_meters,json=horizontalAccuracyMeters,proto3,oneof" json:"horizontal_accuracy_meters,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetHorizontalAccuracyMeters() float64 {
	if x != nil && x.HorizontalAccuracyMeters != nil {
		return *x.HorizontalAccuracyMeters
	}
	return 0
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{4}
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type KnownPlace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Relationship  string                 `protobuf:"bytes,2,opt,name=relationship,proto3" json:"relationship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownPlace) Reset() {
	*x = KnownPlace{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownPlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownPlace) ProtoMessage() {}

func (x *KnownPlace) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownPlace.ProtoReflect.Descriptor instead.
func (*KnownPlace) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{5}
}

func (x *KnownPlace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KnownPlace) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

type Camera struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Make             string                 `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	Model            string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	LensModel        string                 `protobuf:"bytes,3,opt,name=lens_model,json=lensModel,proto3" json:"lens_model,omitempty"`
	FocalLengthMm    *float64               `protobuf:"fixed64,4,opt,name=focal_length_mm,json=focalLengthMm,proto3,oneof" json:"focal_length_mm,omitempty"`
	FocalLength_35Mm *float64               `protobuf:"fixed64,5,opt,name=focal_length_35mm,json=focalLength35mm,proto3,oneof" json:"focal_length_35mm,omitempty"`
	Aperture         *float64               `protobuf:"fixed64,6,opt,name=aperture,proto3,oneof" json:"aperture,omitempty"`
	ShutterSpeed     *float64               `protobuf:"fixed64,7,opt,name=shutter_speed,json=shutterSpeed,proto3,oneof" json:"shutter_speed,omitempty"`
	Iso              *int64                 `protobuf:"varint,8,opt,name=iso,proto3,oneof" json:"iso,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Camera) Reset() {
	*x = Camera{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera) ProtoMessage() {}

func (x *Camera) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera.ProtoReflect.Descriptor instead.
func (*Camera) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{6}
}

func (x *Camera) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Camera) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Camera) GetLensModel() string {
	if x != nil {
		return x.LensModel
	}
	return ""
}

func (x *Camera) GetFocalLengthMm() float64 {
	if x != nil && x.FocalLengthMm != nil {
		return *x.FocalLengthMm
	}
	return 0
}

func (x *Camera) GetFocalLength_35Mm() float64 {
	if x != nil && x.FocalLength_35Mm != nil {
		return *x.FocalLength_35Mm
	}
	return 0
}

func (x *Camera) GetAperture() float64 {
	if x != nil && x.Aperture != nil {
		return *x.Aperture
	}
	return 0
}

func (x *Camera) GetShutterSpeed() float64 {
	if x != nil && x.ShutterSpeed != nil {
		return *x.ShutterSpeed
	}
	return 0
}

func (x *Camera) GetIso() int64 {
	if x != nil && x.Iso != nil {
		return *x.Iso
	}
	return 0
}

type Metadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecordSha256     string                 `protobuf:"bytes,1,opt,name=record_sha256,json=recordSha256,proto3" json:"record_sha256,omitempty"`
	ProjectionSha256 string                 `protobuf:"bytes,2,opt,name=projection_sha256,json=projectionSha256,proto3" json:"projection_sha256,omitempty"`
	ProjectionLines  []string               `protobuf:"bytes,3,rep,name=projection_lines,json=projectionLines,proto3" json:"projection_lines,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{7}
}

func (x *Metadata) GetRecordSha256() string {
	if x != nil {
		return x.RecordSha256
	}
	return ""
}

func (x *Metadata) GetProjectionSha256() string {
	if x != nil {
		return x.ProjectionSha256
	}
	return ""
}

func (x *Metadata) GetProjectionLines() []string {
	if x != nil {
		return x.ProjectionLines
	}
	return nil
}

type FullCurrent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Orientation   int32                  `protobuf:"varint,3,opt,name=orientation,proto3" json:"orientation,omitempty"`
	PixelWidth    int64                  `protobuf:"varint,4,opt,name=pixel_width,json=pixelWidth,proto3" json:"pixel_width,omitempty"`
	PixelHeight   int64                  `protobuf:"varint,5,opt,name=pixel_height,json=pixelHeight,proto3" json:"pixel_height,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullCurrent) Reset() {
	*x = FullCurrent{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullCurrent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullCurrent) ProtoMessage() {}

func (x *FullCurrent) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullCurrent.ProtoReflect.Descriptor instead.
func (*FullCurrent) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{8}
}

func (x *FullCurrent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *FullCurrent) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *FullCurrent) GetOrientation() int32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

func (x *FullCurrent) GetPixelWidth() int64 {
	if x != nil {
		return x.PixelWidth
	}
	return 0
}

func (x *FullCurrent) GetPixelHeight() int64 {
	if x != nil {
		return x.PixelHeight
	}
	return 0
}

func (x *FullCurrent) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FullCurrent) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type PlaceProjection struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProviderIdentity     string                 `protobuf:"bytes,1,opt,name=provider_identity,json=providerIdentity,proto3" json:"provider_identity,omitempty"`
	Operation            string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	CoordinateVariant    string                 `protobuf:"bytes,3,opt,name=coordinate_variant,json=coordinateVariant,proto3" json:"coordinate_variant,omitempty"`
	ParserVersion        string                 `protobuf:"bytes,4,opt,name=parser_version,json=parserVersion,proto3" json:"parser_version,omitempty"`
	PreAuthRequestSha256 string                 `protobuf:"bytes,5,opt,name=pre_auth_request_sha256,json=preAuthRequestSha256,proto3" json:"pre_auth_request_sha256,omitempty"`
	RawResponseSha256    string                 `protobuf:"bytes,6,opt,name=raw_response_sha256,json=rawResponseSha256,proto3" json:"raw_response_sha256,omitempty"`
	Address              *Address               `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Candidates           []*PlaceCandidate      `protobuf:"bytes,8,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlaceProjection) Reset() {
	*x = PlaceProjection{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceProjection) ProtoMessage() {}

func (x *PlaceProjection) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceProjection.ProtoReflect.Descriptor instead.
func (*PlaceProjection) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{9}
}

func (x *PlaceProjection) GetProviderIdentity() string {
	if x != nil {
		return x.ProviderIdentity
	}
	return ""
}

func (x *PlaceProjection) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *PlaceProjection) GetCoordinateVariant() string {
	if x != nil {
		return x.CoordinateVariant
	}
	return ""
}

func (x *PlaceProjection) GetParserVersion() string {
	if x != nil {
		return x.ParserVersion
	}
	return ""
}

func (x *PlaceProjection) GetPreAuthRequestSha256() string {
	if x != nil {
		return x.PreAuthRequestSha256
	}
	return ""
}

func (x *PlaceProjection) GetRawResponseSha256() string {
	if x != nil {
		return x.RawResponseSha256
	}
	return ""
}

func (x *PlaceProjection) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PlaceProjection) GetCandidates() []*PlaceCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type PlaceCandidate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProviderIndex  int32                  `protobuf:"varint,1,opt,name=provider_index,json=providerIndex,proto3" json:"provider_index,omitempty"`
	ProviderId     string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Categories     []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	Coordinate     *Coordinate            `protobuf:"bytes,5,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	DistanceMeters float64                `protobuf:"fixed64,6,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	Address        *Address               `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Source         string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlaceCandidate) Reset() {
	*x = PlaceCandidate{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceCandidate) ProtoMessage() {}

func (x *PlaceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceCandidate.ProtoReflect.Descriptor instead.
func (*PlaceCandidate) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{10}
}

func (x *PlaceCandidate) GetProviderIndex() int32 {
	if x != nil {
		return x.ProviderIndex
	}
	return 0
}

func (x *PlaceCandidate) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *PlaceCandidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlaceCandidate) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *PlaceCandidate) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *PlaceCandidate) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *PlaceCandidate) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PlaceCandidate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Address struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Thoroughfare          string                 `protobuf:"bytes,2,opt,name=thoroughfare,proto3" json:"thoroughfare,omitempty"`
	SubThoroughfare       string                 `protobuf:"bytes,3,opt,name=sub_thoroughfare,json=subThoroughfare,proto3" json:"sub_thoroughfare,omitempty"`
	Locality              string                 `protobuf:"bytes,4,opt,name=locality,proto3" json:"locality,omitempty"`
	SubLocality           string                 `protobuf:"bytes,5,opt,name=sub_locality,json=subLocality,proto3" json:"sub_locality,omitempty"`
	AdministrativeArea    string                 `protobuf:"bytes,6,opt,name=administrative_area,json=administrativeArea,proto3" json:"administrative_area,omitempty"`
	SubAdministrativeArea string                 `protobuf:"bytes,7,opt,name=sub_administrative_area,json=subAdministrativeArea,proto3" json:"sub_administrative_area,omitempty"`
	PostalCode            string                 `protobuf:"bytes,8,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country               string                 `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	IsoCountryCode        string                 `protobuf:"bytes,10,opt,name=iso_country_code,json=isoCountryCode,proto3" json:"iso_country_code,omitempty"`
	TimeZone              string                 `protobuf:"bytes,11,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	AreasOfInterest       []string               `protobuf:"bytes,12,rep,name=areas_of_interest,json=areasOfInterest,proto3" json:"areas_of_interest,omitempty"`
	Formatted             string                 `protobuf:"bytes,13,opt,name=formatted,proto3" json:"formatted,omitempty"`
	Source                string                 `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{11}
}

func (x *Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Address) GetThoroughfare() string {
	if x != nil {
		return x.Thoroughfare
	}
	return ""
}

func (x *Address) GetSubThoroughfare() string {
	if x != nil {
		return x.SubThoroughfare
	}
	return ""
}

func (x *Address) GetLocality() string {
	if x != nil {
		return x.Locality
	}
	return ""
}

func (x *Address) GetSubLocality() string {
	if x != nil {
		return x.SubLocality
	}
	return ""
}

func (x *Address) GetAdministrativeArea() string {
	if x != nil {
		return x.AdministrativeArea
	}
	return ""
}

func (x *Address) GetSubAdministrativeArea() string {
	if x != nil {
		return x.SubAdministrativeArea
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetIsoCountryCode() string {
	if x != nil {
		return x.IsoCountryCode
	}
	return ""
}

func (x *Address) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *Address) GetAreasOfInterest() []string {
	if x != nil {
		return x.AreasOfInterest
	}
	return nil
}

func (x *Address) GetFormatted() string {
	if x != nil {
		return x.Formatted
	}
	return ""
}

func (x *Address) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// FixtureResponse crosses the deterministic fixture boundary. It retains the
// same raw provider fields that production parsing consumes.
type FixtureResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Response            []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Failure             []byte                 `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	Status              string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode          int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ProviderRequestId   string                 `protobuf:"bytes,5,opt,name=provider_request_id,json=providerRequestId,proto3" json:"provider_request_id,omitempty"`
	TransmissionStarted bool                   `protobuf:"varint,6,opt,name=transmission_started,json=transmissionStarted,proto3" json:"transmission_started,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FixtureResponse) Reset() {
	*x = FixtureResponse{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureResponse) ProtoMessage() {}

func (x *FixtureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureResponse.ProtoReflect.Descriptor instead.
func (*FixtureResponse) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{12}
}

func (x *FixtureResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FixtureResponse) GetFailure() []byte {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *FixtureResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FixtureResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FixtureResponse) GetProviderRequestId() string {
	if x != nil {
		return x.ProviderRequestId
	}
	return ""
}

func (x *FixtureResponse) GetTransmissionStarted() bool {
	if x != nil {
		return x.TransmissionStarted
	}
	return false
}

type CardExecutionCustody struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	SourceId                    string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	AssetId                     string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	ImmutableOriginalResourceId string                 `protobuf:"bytes,3,opt,name=immutable_original_resource_id,json=immutableOriginalResourceId,proto3" json:"immutable_original_resource_id,omitempty"`
	MetadataRecordId            string                 `protobuf:"bytes,4,opt,name=metadata_record_id,json=metadataRecordId,proto3" json:"metadata_record_id,omitempty"`
	MetadataProjectionId        string                 `protobuf:"bytes,5,opt,name=metadata_projection_id,json=metadataProjectionId,proto3" json:"metadata_projection_id,omitempty"`
	FullCurrentProofSha256      string                 `protobuf:"bytes,6,opt,name=full_current_proof_sha256,json=fullCurrentProofSha256,proto3" json:"full_current_proof_sha256,omitempty"`
	Evidence                    []*EvidenceLink        `protobuf:"bytes,7,rep,name=evidence,proto3" json:"evidence,omitempty"`
	CardInputSha256             string                 `protobuf:"bytes,8,opt,name=card_input_sha256,json=cardInputSha256,proto3" json:"card_input_sha256,omitempty"`
	RequestSha256               string                 `protobuf:"bytes,9,opt,name=request_sha256,json=requestSha256,proto3" json:"request_sha256,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CardExecutionCustody) Reset() {
	*x = CardExecutionCustody{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardExecutionCustody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardExecutionCustody) ProtoMessage() {}

func (x *CardExecutionCustody) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardExecutionCustody.ProtoReflect.Descriptor instead.
func (*CardExecutionCustody) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{13}
}

func (x *CardExecutionCustody) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CardExecutionCustody) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CardExecutionCustody) GetImmutableOriginalResourceId() string {
	if x != nil {
		return x.ImmutableOriginalResourceId
	}
	return ""
}

func (x *CardExecutionCustody) GetMetadataRecordId() string {
	if x != nil {
		return x.MetadataRecordId
	}
	return ""
}

func (x *CardExecutionCustody) GetMetadataProjectionId() string {
	if x != nil {
		return x.MetadataProjectionId
	}
	return ""
}

func (x *CardExecutionCustody) GetFullCurrentProofSha256() string {
	if x != nil {
		return x.FullCurrentProofSha256
	}
	return ""
}

func (x *CardExecutionCustody) GetEvidence() []*EvidenceLink {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *CardExecutionCustody) GetCardInputSha256() string {
	if x != nil {
		return x.CardInputSha256
	}
	return ""
}

func (x *CardExecutionCustody) GetRequestSha256() string {
	if x != nil {
		return x.RequestSha256
	}
	return ""
}

type EvidenceLink struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProviderIdentity  string                 `protobuf:"bytes,1,opt,name=provider_identity,json=providerIdentity,proto3" json:"provider_identity,omitempty"`
	Operation         string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	RawResponseSha256 string                 `protobuf:"bytes,3,opt,name=raw_response_sha256,json=rawResponseSha256,proto3" json:"raw_response_sha256,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EvidenceLink) Reset() {
	*x = EvidenceLink{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceLink) ProtoMessage() {}

func (x *EvidenceLink) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceLink.ProtoReflect.Descriptor instead.
func (*EvidenceLink) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{14}
}

func (x *EvidenceLink) GetProviderIdentity() string {
	if x != nil {
		return x.ProviderIdentity
	}
	return ""
}

func (x *EvidenceLink) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *EvidenceLink) GetRawResponseSha256() string {
	if x != nil {
		return x.RawResponseSha256
	}
	return ""
}

// ApprovedCardBundle is the complete credential-free boundary between local
// preparation and the explicit local send action.
type ApprovedCardBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purpose       string                 `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	CallCap       uint32                 `protobuf:"varint,2,opt,name=call_cap,json=callCap,proto3" json:"call_cap,omitempty"`
	Items         []*ApprovedCardItem    `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovedCardBundle) Reset() {
	*x = ApprovedCardBundle{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovedCardBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovedCardBundle) ProtoMessage() {}

func (x *ApprovedCardBundle) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovedCardBundle.ProtoReflect.Descriptor instead.
func (*ApprovedCardBundle) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{15}
}

func (x *ApprovedCardBundle) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ApprovedCardBundle) GetCallCap() uint32 {
	if x != nil {
		return x.CallCap
	}
	return 0
}

func (x *ApprovedCardBundle) GetItems() []*ApprovedCardItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ApprovedCardItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Position          uint32                 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	AssetId           string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	CardInputId       string                 `protobuf:"bytes,3,opt,name=card_input_id,json=cardInputId,proto3" json:"card_input_id,omitempty"`
	CardInput         []byte                 `protobuf:"bytes,4,opt,name=card_input,json=cardInput,proto3" json:"card_input,omitempty"`
	Custody           []byte                 `protobuf:"bytes,5,opt,name=custody,proto3" json:"custody,omitempty"`
	CustodySha256     string                 `protobuf:"bytes,6,opt,name=custody_sha256,json=custodySha256,proto3" json:"custody_sha256,omitempty"`
	FullCurrentSha256 string                 `protobuf:"bytes,7,opt,name=full_current_sha256,json=fullCurrentSha256,proto3" json:"full_current_sha256,omitempty"`
	RequestRoute      string                 `protobuf:"bytes,8,opt,name=request_route,json=requestRoute,proto3" json:"request_route,omitempty"`
	ModelId           string                 `protobuf:"bytes,9,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	RequestBody       []byte                 `protobuf:"bytes,10,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	RequestBodyLength uint64                 `protobuf:"varint,11,opt,name=request_body_length,json=requestBodyLength,proto3" json:"request_body_length,omitempty"`
	RequestSha256     string                 `protobuf:"bytes,12,opt,name=request_sha256,json=requestSha256,proto3" json:"request_sha256,omitempty"`
	PromptVersion     string                 `protobuf:"bytes,13,opt,name=prompt_version,json=promptVersion,proto3" json:"prompt_version,omitempty"`
	ParserVersion     string                 `protobuf:"bytes,14,opt,name=parser_version,json=parserVersion,proto3" json:"parser_version,omitempty"`
	ExecutionId       string                 `protobuf:"bytes,15,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApprovedCardItem) Reset() {
	*x = ApprovedCardItem{}
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovedCardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovedCardItem) ProtoMessage() {}

func (x *ApprovedCardItem) ProtoReflect() protoreflect.Message {
	mi := &file_opentrawl_photos_card_v1_card_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovedCardItem.ProtoReflect.Descriptor instead.
func (*ApprovedCardItem) Descriptor() ([]byte, []int) {
	return file_opentrawl_photos_card_v1_card_proto_rawDescGZIP(), []int{16}
}

func (x *ApprovedCardItem) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ApprovedCardItem) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ApprovedCardItem) GetCardInputId() string {
	if x != nil {
		return x.CardInputId
	}
	return ""
}

func (x *ApprovedCardItem) GetCardInput() []byte {
	if x != nil {
		return x.CardInput
	}
	return nil
}

func (x *ApprovedCardItem) GetCustody() []byte {
	if x != nil {
		return x.Custody
	}
	return nil
}

func (x *ApprovedCardItem) GetCustodySha256() string {
	if x != nil {
		return x.CustodySha256
	}
	return ""
}

func (x *ApprovedCardItem) GetFullCurrentSha256() string {
	if x != nil {
		return x.FullCurrentSha256
	}
	return ""
}

func (x *ApprovedCardItem) GetRequestRoute() string {
	if x != nil {
		return x.RequestRoute
	}
	return ""
}

func (x *ApprovedCardItem) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ApprovedCardItem) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *ApprovedCardItem) GetRequestBodyLength() uint64 {
	if x != nil {
		return x.RequestBodyLength
	}
	return 0
}

func (x *ApprovedCardItem) GetRequestSha256() string {
	if x != nil {
		return x.RequestSha256
	}
	return ""
}

func (x *ApprovedCardItem) GetPromptVersion() string {
	if x != nil {
		return x.PromptVersion
	}
	return ""
}

func (x *ApprovedCardItem) GetParserVersion() string {
	if x != nil {
		return x.ParserVersion
	}
	return ""
}

func (x *ApprovedCardItem) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

var File_opentrawl_photos_card_v1_card_proto protoreflect.FileDescriptor

const file_opentrawl_photos_card_v1_card_proto_rawDesc = "" +
	"\n" +
	"#opentrawl/photos/card/v1/card.proto\x12\x18opentrawl.photos.card.v1\"\xb2\a\n" +
	"\tCardInput\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12!\n" +
	"\fcapture_time\x18\x02 \x01(\tR\vcaptureTime\x12\x1f\n" +
	"\btimezone\x18\x03 \x01(\tH\x00R\btimezone\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\x12%\n" +
	"\x0emedia_subtypes\x18\x05 \x03(\tR\rmediaSubtypes\x12\x1f\n" +
	"\vpixel_width\x18\x06 \x01(\x03R\n" +
	"pixelWidth\x12!\n" +
	"\fpixel_height\x18\a \x01(\x03R\vpixelHeight\x12)\n" +
	"\x10duration_seconds\x18\b \x01(\x01R\x0fdurationSeconds\x12Z\n" +
	"\x12immutable_original\x18\t \x01(\v2+.opentrawl.photos.card.v1.ImmutableOriginalR\x11immutableOriginal\x12\x1a\n" +
	"\bfavorite\x18\n" +
	" \x01(\bR\bfavorite\x12\x16\n" +
	"\x06hidden\x18\v \x01(\bR\x06hidden\x12!\n" +
	"\fburst_member\x18\f \x01(\bR\vburstMember\x127\n" +
	"\x06albums\x18\r \x03(\v2\x1f.opentrawl.photos.card.v1.AlbumR\x06albums\x12>\n" +
	"\blocation\x18\x0e \x01(\v2\".opentrawl.photos.card.v1.LocationR\blocation\x12E\n" +
	"\vknown_place\x18\x0f \x01(\v2$.opentrawl.photos.card.v1.KnownPlaceR\n" +
	"knownPlace\x128\n" +
	"\x06camera\x18\x10 \x01(\v2 .opentrawl.photos.card.v1.CameraR\x06camera\x12>\n" +
	"\bmetadata\x18\x11 \x01(\v2\".opentrawl.photos.card.v1.MetadataR\bmetadata\x12H\n" +
	"\ffull_current\x18\x12 \x01(\v2%.opentrawl.photos.card.v1.FullCurrentR\vfullCurrent\x12A\n" +
	"\x06places\x18\x13 \x03(\v2).opentrawl.photos.card.v1.PlaceProjectionR\x06placesB\v\n" +
	"\t_timezone\"\xc1\x01\n" +
	"\x11ImmutableOriginal\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x10\n" +
	"\x03uti\x18\x02 \x01(\tR\x03uti\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\"\n" +
	"\favailability\x18\x04 \x01(\tR\favailability\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\"1\n" +
	"\x05Album\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"\xa6\x01\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12A\n" +
	"\x1ahorizontal_accuracy_meters\x18\x03 \x01(\x01H\x00R\x18horizontalAccuracyMeters\x88\x01\x01B\x1d\n" +
	"\x1b_horizontal_accuracy_meters\"F\n" +
	"\n" +
	"Coordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"D\n" +
	"\n" +
	"KnownPlace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\frelationship\x18\x02 \x01(\tR\frelationship\"\xe2\x02\n" +
	"\x06Camera\x12\x12\n" +
	"\x04make\x18\x01 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"lens_model\x18\x03 \x01(\tR\tlensModel\x12+\n" +
	"\x0ffocal_length_mm\x18\x04 \x01(\x01H\x00R\rfocalLengthMm\x88\x01\x01\x12/\n" +
	"\x11focal_length_35mm\x18\x05 \x01(\x01H\x01R\x0ffocalLength35mm\x88\x01\x01\x12\x1f\n" +
	"\baperture\x18\x06 \x01(\x01H\x02R\baperture\x88\x01\x01\x12(\n" +
	"\rshutter_speed\x18\a \x01(\x01H\x03R\fshutterSpeed\x88\x01\x01\x12\x15\n" +
	"\x03iso\x18\b \x01(\x03H\x04R\x03iso\x88\x01\x01B\x12\n" +
	"\x10_focal_length_mmB\x14\n" +
	"\x12_focal_length_35mmB\v\n" +
	"\t_apertureB\x10\n" +
	"\x0e_shutter_speedB\x06\n" +
	"\x04_iso\"\x87\x01\n" +
	"\bMetadata\x12#\n" +
	"\rrecord_sha256\x18\x01 \x01(\tR\frecordSha256\x12+\n" +
	"\x11projection_sha256\x18\x02 \x01(\tR\x10projectionSha256\x12)\n" +
	"\x10projection_lines\x18\x03 \x03(\tR\x0fprojectionLines\"\xdd\x01\n" +
	"\vFullCurrent\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12 \n" +
	"\vorientation\x18\x03 \x01(\x05R\vorientation\x12\x1f\n" +
	"\vpixel_width\x18\x04 \x01(\x03R\n" +
	"pixelWidth\x12!\n" +
	"\fpixel_height\x18\x05 \x01(\x03R\vpixelHeight\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\a \x01(\tR\x06sha256\"\xa0\x03\n" +
	"\x0fPlaceProjection\x12+\n" +
	"\x11provider_identity\x18\x01 \x01(\tR\x10providerIdentity\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12-\n" +
	"\x12coordinate_variant\x18\x03 \x01(\tR\x11coordinateVariant\x12%\n" +
	"\x0eparser_version\x18\x04 \x01(\tR\rparserVersion\x125\n" +
	"\x17pre_auth_request_sha256\x18\x05 \x01(\tR\x14preAuthRequestSha256\x12.\n" +
	"\x13raw_response_sha256\x18\x06 \x01(\tR\x11rawResponseSha256\x12;\n" +
	"\aaddress\x18\a \x01(\v2!.opentrawl.photos.card.v1.AddressR\aaddress\x12H\n" +
	"\n" +
	"candidates\x18\b \x03(\v2(.opentrawl.photos.card.v1.PlaceCandidateR\n" +
	"candidates\"\xd0\x02\n" +
	"\x0ePlaceCandidate\x12%\n" +
	"\x0eprovider_index\x18\x01 \x01(\x05R\rproviderIndex\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x12D\n" +
	"\n" +
	"coordinate\x18\x05 \x01(\v2$.opentrawl.photos.card.v1.CoordinateR\n" +
	"coordinate\x12'\n" +
	"\x0fdistance_meters\x18\x06 \x01(\x01R\x0edistanceMeters\x12;\n" +
	"\aaddress\x18\a \x01(\v2!.opentrawl.photos.card.v1.AddressR\aaddress\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\"\xf8\x03\n" +
	"\aAddress\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fthoroughfare\x18\x02 \x01(\tR\fthoroughfare\x12)\n" +
	"\x10sub_thoroughfare\x18\x03 \x01(\tR\x0fsubThoroughfare\x12\x1a\n" +
	"\blocality\x18\x04 \x01(\tR\blocality\x12!\n" +
	"\fsub_locality\x18\x05 \x01(\tR\vsubLocality\x12/\n" +
	"\x13administrative_area\x18\x06 \x01(\tR\x12administrativeArea\x126\n" +
	"\x17sub_administrative_area\x18\a \x01(\tR\x15subAdministrativeArea\x12\x1f\n" +
	"\vpostal_code\x18\b \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\t \x01(\tR\acountry\x12(\n" +
	"\x10iso_country_code\x18\n" +
	" \x01(\tR\x0eisoCountryCode\x12\x1b\n" +
	"\ttime_zone\x18\v \x01(\tR\btimeZone\x12*\n" +
	"\x11areas_of_interest\x18\f \x03(\tR\x0fareasOfInterest\x12\x1c\n" +
	"\tformatted\x18\r \x01(\tR\tformatted\x12\x16\n" +
	"\x06source\x18\x0e \x01(\tR\x06source\"\xe3\x01\n" +
	"\x0fFixtureResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\x12\x18\n" +
	"\afailure\x18\x02 \x01(\fR\afailure\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12.\n" +
	"\x13provider_request_id\x18\x05 \x01(\tR\x11providerRequestId\x121\n" +
	"\x14transmission_started\x18\x06 \x01(\bR\x13transmissionStarted\"\xc9\x03\n" +
	"\x14CardExecutionCustody\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12C\n" +
	"\x1eimmutable_original_resource_id\x18\x03 \x01(\tR\x1bimmutableOriginalResourceId\x12,\n" +
	"\x12metadata_record_id\x18\x04 \x01(\tR\x10metadataRecordId\x124\n" +
	"\x16metadata_projection_id\x18\x05 \x01(\tR\x14metadataProjectionId\x129\n" +
	"\x19full_current_proof_sha256\x18\x06 \x01(\tR\x16fullCurrentProofSha256\x12B\n" +
	"\bevidence\x18\a \x03(\v2&.opentrawl.photos.card.v1.EvidenceLinkR\bevidence\x12*\n" +
	"\x11card_input_sha256\x18\b \x01(\tR\x0fcardInputSha256\x12%\n" +
	"\x0erequest_sha256\x18\t \x01(\tR\rrequestSha256\"\x89\x01\n" +
	"\fEvidenceLink\x12+\n" +
	"\x11provider_identity\x18\x01 \x01(\tR\x10providerIdentity\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12.\n" +
	"\x13raw_response_sha256\x18\x03 \x01(\tR\x11rawResponseSha256\"\x8b\x01\n" +
	"\x12ApprovedCardBundle\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12\x19\n" +
	"\bcall_cap\x18\x02 \x01(\rR\acallCap\x12@\n" +
	"\x05items\x18\x03 \x03(\v2*.opentrawl.photos.card.v1.ApprovedCardItemR\x05items\"\xa8\x04\n" +
	"\x10ApprovedCardItem\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\rR\bposition\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\"\n" +
	"\rcard_input_id\x18\x03 \x01(\tR\vcardInputId\x12\x1d\n" +
	"\n" +
	"card_input\x18\x04 \x01(\fR\tcardInput\x12\x18\n" +
	"\acustody\x18\x05 \x01(\fR\acustody\x12%\n" +
	"\x0ecustody_sha256\x18\x06 \x01(\tR\rcustodySha256\x12.\n" +
	"\x13full_current_sha256\x18\a \x01(\tR\x11fullCurrentSha256\x12#\n" +
	"\rrequest_route\x18\b \x01(\tR\frequestRoute\x12\x19\n" +
	"\bmodel_id\x18\t \x01(\tR\amodelId\x12!\n" +
	"\frequest_body\x18\n" +
	" \x01(\fR\vrequestBody\x12.\n" +
	"\x13request_body_length\x18\v \x01(\x04R\x11requestBodyLength\x12%\n" +
	"\x0erequest_sha256\x18\f \x01(\tR\rrequestSha256\x12%\n" +
	"\x0eprompt_version\x18\r \x01(\tR\rpromptVersion\x12%\n" +
	"\x0eparser_version\x18\x0e \x01(\tR\rparserVersion\x12!\n" +
	"\fexecution_id\x18\x0f \x01(\tR\vexecutionIdBXZVgithub.com/opentrawl/opentrawl/trawlers/photos/proto/opentrawl/photos/card/v1;cardwireb\x06proto3"

var (
	file_opentrawl_photos_card_v1_card_proto_rawDescOnce sync.Once
	file_opentrawl_photos_card_v1_card_proto_rawDescData []byte
)

func file_opentrawl_photos_card_v1_card_proto_rawDescGZIP() []byte {
	file_opentrawl_photos_card_v1_card_proto_rawDescOnce.Do(func() {
		file_opentrawl_photos_card_v1_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opentrawl_photos_card_v1_card_proto_rawDesc), len(file_opentrawl_photos_card_v1_card_proto_rawDesc)))
	})
	return file_opentrawl_photos_card_v1_card_proto_rawDescData
}

var file_opentrawl_photos_card_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_opentrawl_photos_card_v1_card_proto_goTypes = []any{
	(*CardInput)(nil),            // 0: opentrawl.photos.card.v1.CardInput
	(*ImmutableOriginal)(nil),    // 1: opentrawl.photos.card.v1.ImmutableOriginal
	(*Album)(nil),                // 2: opentrawl.photos.card.v1.Album
	(*Location)(nil),             // 3: opentrawl.photos.card.v1.Location
	(*Coordinate)(nil),           // 4: opentrawl.photos.card.v1.Coordinate
	(*KnownPlace)(nil),           // 5: opentrawl.photos.card.v1.KnownPlace
	(*Camera)(nil),               // 6: opentrawl.photos.card.v1.Camera
	(*Metadata)(nil),             // 7: opentrawl.photos.card.v1.Metadata
	(*FullCurrent)(nil),          // 8: opentrawl.photos.card.v1.FullCurrent
	(*PlaceProjection)(nil),      // 9: opentrawl.photos.card.v1.PlaceProjection
	(*PlaceCandidate)(nil),       // 10: opentrawl.photos.card.v1.PlaceCandidate
	(*Address)(nil),              // 11: opentrawl.photos.card.v1.Address
	(*FixtureResponse)(nil),      // 12: opentrawl.photos.card.v1.FixtureResponse
	(*CardExecutionCustody)(nil), // 13: opentrawl.photos.card.v1.CardExecutionCustody
	(*EvidenceLink)(nil),         // 14: opentrawl.photos.card.v1.EvidenceLink
	(*ApprovedCardBundle)(nil),   // 15: opentrawl.photos.card.v1.ApprovedCardBundle
	(*ApprovedCardItem)(nil),     // 16: opentrawl.photos.card.v1.ApprovedCardItem
}
var file_opentrawl_photos_card_v1_card_proto_depIdxs = []int32{
	1,  // 0: opentrawl.photos.card.v1.CardInput.immutable_original:type_name -> opentrawl.photos.card.v1.ImmutableOriginal
	2,  // 1: opentrawl.photos.card.v1.CardInput.albums:type_name -> opentrawl.photos.card.v1.Album
	3,  // 2: opentrawl.photos.card.v1.CardInput.location:type_name -> opentrawl.photos.card.v1.Location
	5,  // 3: opentrawl.photos.card.v1.CardInput.known_place:type_name -> opentrawl.photos.card.v1.KnownPlace
	6,  // 4: opentrawl.photos.card.v1.CardInput.camera:type_name -> opentrawl.photos.card.v1.Camera
	7,  // 5: opentrawl.photos.card.v1.CardInput.metadata:type_name -> opentrawl.photos.card.v1.Metadata
	8,  // 6: opentrawl.photos.card.v1.CardInput.full_current:type_name -> opentrawl.photos.card.v1.FullCurrent
	9,  // 7: opentrawl.photos.card.v1.CardInput.places:type_name -> opentrawl.photos.card.v1.PlaceProjection
	11, // 8: opentrawl.photos.card.v1.PlaceProjection.address:type_name -> opentrawl.photos.card.v1.Address
	10, // 9: opentrawl.photos.card.v1.PlaceProjection.candidates:type_name -> opentrawl.photos.card.v1.PlaceCandidate
	4,  // 10: opentrawl.photos.card.v1.PlaceCandidate.coordinate:type_name -> opentrawl.photos.card.v1.Coordinate
	11, // 11: opentrawl.photos.card.v1.PlaceCandidate.address:type_name -> opentrawl.photos.card.v1.Address
	14, // 12: opentrawl.photos.card.v1.CardExecutionCustody.evidence:type_name -> opentrawl.photos.card.v1.EvidenceLink
	16, // 13: opentrawl.photos.card.v1.ApprovedCardBundle.items:type_name -> opentrawl.photos.card.v1.ApprovedCardItem
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_opentrawl_photos_card_v1_card_proto_init() }
func file_opentrawl_photos_card_v1_card_proto_init() {
	if File_opentrawl_photos_card_v1_card_proto != nil {
		return
	}
	file_opentrawl_photos_card_v1_card_proto_msgTypes[0].OneofWrappers = []any{}
	file_opentrawl_photos_card_v1_card_proto_msgTypes[3].OneofWrappers = []any{}
	file_opentrawl_photos_card_v1_card_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opentrawl_photos_card_v1_card_proto_rawDesc), len(file_opentrawl_photos_card_v1_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opentrawl_photos_card_v1_card_proto_goTypes,
		DependencyIndexes: file_opentrawl_photos_card_v1_card_proto_depIdxs,
		MessageInfos:      file_opentrawl_photos_card_v1_card_proto_msgTypes,
	}.Build()
	File_opentrawl_photos_card_v1_card_proto = out.File
	file_opentrawl_photos_card_v1_card_proto_goTypes = nil
	file_opentrawl_photos_card_v1_card_proto_depIdxs = nil
}
