// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trawl/presentation/v1/presentation.proto

package presentationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalendarDate struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CalendarYear        int32                  `protobuf:"varint,1,opt,name=calendar_year,json=calendarYear,proto3" json:"calendar_year,omitempty"`
	CalendarMonthNumber int32                  `protobuf:"varint,2,opt,name=calendar_month_number,json=calendarMonthNumber,proto3" json:"calendar_month_number,omitempty"`
	CalendarDayOfMonth  int32                  `protobuf:"varint,3,opt,name=calendar_day_of_month,json=calendarDayOfMonth,proto3" json:"calendar_day_of_month,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CalendarDate) Reset() {
	*x = CalendarDate{}
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarDate) ProtoMessage() {}

func (x *CalendarDate) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarDate.ProtoReflect.Descriptor instead.
func (*CalendarDate) Descriptor() ([]byte, []int) {
	return file_trawl_presentation_v1_presentation_proto_rawDescGZIP(), []int{0}
}

func (x *CalendarDate) GetCalendarYear() int32 {
	if x != nil {
		return x.CalendarYear
	}
	return 0
}

func (x *CalendarDate) GetCalendarMonthNumber() int32 {
	if x != nil {
		return x.CalendarMonthNumber
	}
	return 0
}

func (x *CalendarDate) GetCalendarDayOfMonth() int32 {
	if x != nil {
		return x.CalendarDayOfMonth
	}
	return 0
}

type ArchiveRecordAssociatedTimeForDisplay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ArchiveRecordAssociatedTime:
	//
	//	*ArchiveRecordAssociatedTimeForDisplay_ExactTime
	//	*ArchiveRecordAssociatedTimeForDisplay_CalendarDate
	ArchiveRecordAssociatedTime isArchiveRecordAssociatedTimeForDisplay_ArchiveRecordAssociatedTime `protobuf_oneof:"archive_record_associated_time"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ArchiveRecordAssociatedTimeForDisplay) Reset() {
	*x = ArchiveRecordAssociatedTimeForDisplay{}
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRecordAssociatedTimeForDisplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRecordAssociatedTimeForDisplay) ProtoMessage() {}

func (x *ArchiveRecordAssociatedTimeForDisplay) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRecordAssociatedTimeForDisplay.ProtoReflect.Descriptor instead.
func (*ArchiveRecordAssociatedTimeForDisplay) Descriptor() ([]byte, []int) {
	return file_trawl_presentation_v1_presentation_proto_rawDescGZIP(), []int{1}
}

func (x *ArchiveRecordAssociatedTimeForDisplay) GetArchiveRecordAssociatedTime() isArchiveRecordAssociatedTimeForDisplay_ArchiveRecordAssociatedTime {
	if x != nil {
		return x.ArchiveRecordAssociatedTime
	}
	return nil
}

func (x *ArchiveRecordAssociatedTimeForDisplay) GetExactTime() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.ArchiveRecordAssociatedTime.(*ArchiveRecordAssociatedTimeForDisplay_ExactTime); ok {
			return x.ExactTime
		}
	}
	return nil
}

func (x *ArchiveRecordAssociatedTimeForDisplay) GetCalendarDate() *CalendarDate {
	if x != nil {
		if x, ok := x.ArchiveRecordAssociatedTime.(*ArchiveRecordAssociatedTimeForDisplay_CalendarDate); ok {
			return x.CalendarDate
		}
	}
	return nil
}

type isArchiveRecordAssociatedTimeForDisplay_ArchiveRecordAssociatedTime interface {
	isArchiveRecordAssociatedTimeForDisplay_ArchiveRecordAssociatedTime()
}

type ArchiveRecordAssociatedTimeForDisplay_ExactTime struct {
	ExactTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=exact_time,json=exactTime,proto3,oneof"`
}

type ArchiveRecordAssociatedTimeForDisplay_CalendarDate struct {
	CalendarDate *CalendarDate `protobuf:"bytes,2,opt,name=calendar_date,json=calendarDate,proto3,oneof"`
}

func (*ArchiveRecordAssociatedTimeForDisplay_ExactTime) isArchiveRecordAssociatedTimeForDisplay_ArchiveRecordAssociatedTime() {
}

func (*ArchiveRecordAssociatedTimeForDisplay_CalendarDate) isArchiveRecordAssociatedTimeForDisplay_ArchiveRecordAssociatedTime() {
}

type TrawlerSpecificCommandPresentationValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TypedValue:
	//
	//	*TrawlerSpecificCommandPresentationValue_Text
	//	*TrawlerSpecificCommandPresentationValue_UnsignedCount
	//	*TrawlerSpecificCommandPresentationValue_ArchiveRecordAssociatedTimeForDisplay
	//	*TrawlerSpecificCommandPresentationValue_CanonicalRecordReferenceForGloballyRoutableTrawlLinkAssignment
	TypedValue    isTrawlerSpecificCommandPresentationValue_TypedValue `protobuf_oneof:"typed_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrawlerSpecificCommandPresentationValue) Reset() {
	*x = TrawlerSpecificCommandPresentationValue{}
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerSpecificCommandPresentationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerSpecificCommandPresentationValue) ProtoMessage() {}

func (x *TrawlerSpecificCommandPresentationValue) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerSpecificCommandPresentationValue.ProtoReflect.Descriptor instead.
func (*TrawlerSpecificCommandPresentationValue) Descriptor() ([]byte, []int) {
	return file_trawl_presentation_v1_presentation_proto_rawDescGZIP(), []int{2}
}

func (x *TrawlerSpecificCommandPresentationValue) GetTypedValue() isTrawlerSpecificCommandPresentationValue_TypedValue {
	if x != nil {
		return x.TypedValue
	}
	return nil
}

func (x *TrawlerSpecificCommandPresentationValue) GetText() string {
	if x != nil {
		if x, ok := x.TypedValue.(*TrawlerSpecificCommandPresentationValue_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *TrawlerSpecificCommandPresentationValue) GetUnsignedCount() uint64 {
	if x != nil {
		if x, ok := x.TypedValue.(*TrawlerSpecificCommandPresentationValue_UnsignedCount); ok {
			return x.UnsignedCount
		}
	}
	return 0
}

func (x *TrawlerSpecificCommandPresentationValue) GetArchiveRecordAssociatedTimeForDisplay() *ArchiveRecordAssociatedTimeForDisplay {
	if x != nil {
		if x, ok := x.TypedValue.(*TrawlerSpecificCommandPresentationValue_ArchiveRecordAssociatedTimeForDisplay); ok {
			return x.ArchiveRecordAssociatedTimeForDisplay
		}
	}
	return nil
}

func (x *TrawlerSpecificCommandPresentationValue) GetCanonicalRecordReferenceForGloballyRoutableTrawlLinkAssignment() string {
	if x != nil {
		if x, ok := x.TypedValue.(*TrawlerSpecificCommandPresentationValue_CanonicalRecordReferenceForGloballyRoutableTrawlLinkAssignment); ok {
			return x.CanonicalRecordReferenceForGloballyRoutableTrawlLinkAssignment
		}
	}
	return ""
}

type isTrawlerSpecificCommandPresentationValue_TypedValue interface {
	isTrawlerSpecificCommandPresentationValue_TypedValue()
}

type TrawlerSpecificCommandPresentationValue_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type TrawlerSpecificCommandPresentationValue_UnsignedCount struct {
	UnsignedCount uint64 `protobuf:"varint,2,opt,name=unsigned_count,json=unsignedCount,proto3,oneof"`
}

type TrawlerSpecificCommandPresentationValue_ArchiveRecordAssociatedTimeForDisplay struct {
	ArchiveRecordAssociatedTimeForDisplay *ArchiveRecordAssociatedTimeForDisplay `protobuf:"bytes,3,opt,name=archive_record_associated_time_for_display,json=archiveRecordAssociatedTimeForDisplay,proto3,oneof"`
}

type TrawlerSpecificCommandPresentationValue_CanonicalRecordReferenceForGloballyRoutableTrawlLinkAssignment struct {
	CanonicalRecordReferenceForGloballyRoutableTrawlLinkAssignment string `protobuf:"bytes,4,opt,name=canonical_record_reference_for_globally_routable_trawl_link_assignment,json=canonicalRecordReferenceForGloballyRoutableTrawlLinkAssignment,proto3,oneof"`
}

func (*TrawlerSpecificCommandPresentationValue_Text) isTrawlerSpecificCommandPresentationValue_TypedValue() {
}

func (*TrawlerSpecificCommandPresentationValue_UnsignedCount) isTrawlerSpecificCommandPresentationValue_TypedValue() {
}

func (*TrawlerSpecificCommandPresentationValue_ArchiveRecordAssociatedTimeForDisplay) isTrawlerSpecificCommandPresentationValue_TypedValue() {
}

func (*TrawlerSpecificCommandPresentationValue_CanonicalRecordReferenceForGloballyRoutableTrawlLinkAssignment) isTrawlerSpecificCommandPresentationValue_TypedValue() {
}

type TrawlerSpecificCommandListPresentationRow struct {
	state                      protoimpl.MessageState                     `protogen:"open.v1"`
	ColumnValuesInDisplayOrder []*TrawlerSpecificCommandPresentationValue `protobuf:"bytes,1,rep,name=column_values_in_display_order,json=columnValuesInDisplayOrder,proto3" json:"column_values_in_display_order,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TrawlerSpecificCommandListPresentationRow) Reset() {
	*x = TrawlerSpecificCommandListPresentationRow{}
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerSpecificCommandListPresentationRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerSpecificCommandListPresentationRow) ProtoMessage() {}

func (x *TrawlerSpecificCommandListPresentationRow) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerSpecificCommandListPresentationRow.ProtoReflect.Descriptor instead.
func (*TrawlerSpecificCommandListPresentationRow) Descriptor() ([]byte, []int) {
	return file_trawl_presentation_v1_presentation_proto_rawDescGZIP(), []int{3}
}

func (x *TrawlerSpecificCommandListPresentationRow) GetColumnValuesInDisplayOrder() []*TrawlerSpecificCommandPresentationValue {
	if x != nil {
		return x.ColumnValuesInDisplayOrder
	}
	return nil
}

type TrawlerSpecificCommandListPresentation struct {
	state                     protoimpl.MessageState                       `protogen:"open.v1"`
	ColumnDisplayNamesInOrder []string                                     `protobuf:"bytes,1,rep,name=column_display_names_in_order,json=columnDisplayNamesInOrder,proto3" json:"column_display_names_in_order,omitempty"`
	RowsInDisplayOrder        []*TrawlerSpecificCommandListPresentationRow `protobuf:"bytes,2,rep,name=rows_in_display_order,json=rowsInDisplayOrder,proto3" json:"rows_in_display_order,omitempty"`
	// Types that are valid to be assigned to TotalRowCount:
	//
	//	*TrawlerSpecificCommandListPresentation_ExactTotalRowCount
	//	*TrawlerSpecificCommandListPresentation_LowerBoundTotalRowCount
	TotalRowCount                   isTrawlerSpecificCommandListPresentation_TotalRowCount `protobuf_oneof:"total_row_count"`
	MoreRowsExist                   bool                                                   `protobuf:"varint,5,opt,name=more_rows_exist,json=moreRowsExist,proto3" json:"more_rows_exist,omitempty"`
	ConciseTextShownWhenListIsEmpty string                                                 `protobuf:"bytes,6,opt,name=concise_text_shown_when_list_is_empty,json=conciseTextShownWhenListIsEmpty,proto3" json:"concise_text_shown_when_list_is_empty,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *TrawlerSpecificCommandListPresentation) Reset() {
	*x = TrawlerSpecificCommandListPresentation{}
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerSpecificCommandListPresentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerSpecificCommandListPresentation) ProtoMessage() {}

func (x *TrawlerSpecificCommandListPresentation) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerSpecificCommandListPresentation.ProtoReflect.Descriptor instead.
func (*TrawlerSpecificCommandListPresentation) Descriptor() ([]byte, []int) {
	return file_trawl_presentation_v1_presentation_proto_rawDescGZIP(), []int{4}
}

func (x *TrawlerSpecificCommandListPresentation) GetColumnDisplayNamesInOrder() []string {
	if x != nil {
		return x.ColumnDisplayNamesInOrder
	}
	return nil
}

func (x *TrawlerSpecificCommandListPresentation) GetRowsInDisplayOrder() []*TrawlerSpecificCommandListPresentationRow {
	if x != nil {
		return x.RowsInDisplayOrder
	}
	return nil
}

func (x *TrawlerSpecificCommandListPresentation) GetTotalRowCount() isTrawlerSpecificCommandListPresentation_TotalRowCount {
	if x != nil {
		return x.TotalRowCount
	}
	return nil
}

func (x *TrawlerSpecificCommandListPresentation) GetExactTotalRowCount() uint64 {
	if x != nil {
		if x, ok := x.TotalRowCount.(*TrawlerSpecificCommandListPresentation_ExactTotalRowCount); ok {
			return x.ExactTotalRowCount
		}
	}
	return 0
}

func (x *TrawlerSpecificCommandListPresentation) GetLowerBoundTotalRowCount() uint64 {
	if x != nil {
		if x, ok := x.TotalRowCount.(*TrawlerSpecificCommandListPresentation_LowerBoundTotalRowCount); ok {
			return x.LowerBoundTotalRowCount
		}
	}
	return 0
}

func (x *TrawlerSpecificCommandListPresentation) GetMoreRowsExist() bool {
	if x != nil {
		return x.MoreRowsExist
	}
	return false
}

func (x *TrawlerSpecificCommandListPresentation) GetConciseTextShownWhenListIsEmpty() string {
	if x != nil {
		return x.ConciseTextShownWhenListIsEmpty
	}
	return ""
}

type isTrawlerSpecificCommandListPresentation_TotalRowCount interface {
	isTrawlerSpecificCommandListPresentation_TotalRowCount()
}

type TrawlerSpecificCommandListPresentation_ExactTotalRowCount struct {
	ExactTotalRowCount uint64 `protobuf:"varint,3,opt,name=exact_total_row_count,json=exactTotalRowCount,proto3,oneof"`
}

type TrawlerSpecificCommandListPresentation_LowerBoundTotalRowCount struct {
	LowerBoundTotalRowCount uint64 `protobuf:"varint,4,opt,name=lower_bound_total_row_count,json=lowerBoundTotalRowCount,proto3,oneof"`
}

func (*TrawlerSpecificCommandListPresentation_ExactTotalRowCount) isTrawlerSpecificCommandListPresentation_TotalRowCount() {
}

func (*TrawlerSpecificCommandListPresentation_LowerBoundTotalRowCount) isTrawlerSpecificCommandListPresentation_TotalRowCount() {
}

type TrawlerSpecificCommandDetailPresentationField struct {
	state                      protoimpl.MessageState                   `protogen:"open.v1"`
	FieldDisplayName           string                                   `protobuf:"bytes,1,opt,name=field_display_name,json=fieldDisplayName,proto3" json:"field_display_name,omitempty"`
	FieldValue                 *TrawlerSpecificCommandPresentationValue `protobuf:"bytes,2,opt,name=field_value,json=fieldValue,proto3" json:"field_value,omitempty"`
	FieldFixedAnchorIdentifier *string                                  `protobuf:"bytes,3,opt,name=field_fixed_anchor_identifier,json=fieldFixedAnchorIdentifier,proto3,oneof" json:"field_fixed_anchor_identifier,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TrawlerSpecificCommandDetailPresentationField) Reset() {
	*x = TrawlerSpecificCommandDetailPresentationField{}
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerSpecificCommandDetailPresentationField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerSpecificCommandDetailPresentationField) ProtoMessage() {}

func (x *TrawlerSpecificCommandDetailPresentationField) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerSpecificCommandDetailPresentationField.ProtoReflect.Descriptor instead.
func (*TrawlerSpecificCommandDetailPresentationField) Descriptor() ([]byte, []int) {
	return file_trawl_presentation_v1_presentation_proto_rawDescGZIP(), []int{5}
}

func (x *TrawlerSpecificCommandDetailPresentationField) GetFieldDisplayName() string {
	if x != nil {
		return x.FieldDisplayName
	}
	return ""
}

func (x *TrawlerSpecificCommandDetailPresentationField) GetFieldValue() *TrawlerSpecificCommandPresentationValue {
	if x != nil {
		return x.FieldValue
	}
	return nil
}

func (x *TrawlerSpecificCommandDetailPresentationField) GetFieldFixedAnchorIdentifier() string {
	if x != nil && x.FieldFixedAnchorIdentifier != nil {
		return *x.FieldFixedAnchorIdentifier
	}
	return ""
}

type TrawlerSpecificCommandDetailPresentation struct {
	state                                  protoimpl.MessageState                           `protogen:"open.v1"`
	DetailDisplayName                      string                                           `protobuf:"bytes,1,opt,name=detail_display_name,json=detailDisplayName,proto3" json:"detail_display_name,omitempty"`
	DetailDisplayNameFixedAnchorIdentifier *string                                          `protobuf:"bytes,2,opt,name=detail_display_name_fixed_anchor_identifier,json=detailDisplayNameFixedAnchorIdentifier,proto3,oneof" json:"detail_display_name_fixed_anchor_identifier,omitempty"`
	FieldsInDisplayOrder                   []*TrawlerSpecificCommandDetailPresentationField `protobuf:"bytes,3,rep,name=fields_in_display_order,json=fieldsInDisplayOrder,proto3" json:"fields_in_display_order,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*TrawlerSpecificCommandDetailPresentation_BodyText
	//	*TrawlerSpecificCommandDetailPresentation_BodyUnavailableExplanation
	Body                      isTrawlerSpecificCommandDetailPresentation_Body `protobuf_oneof:"body"`
	BodyFixedAnchorIdentifier *string                                         `protobuf:"bytes,6,opt,name=body_fixed_anchor_identifier,json=bodyFixedAnchorIdentifier,proto3,oneof" json:"body_fixed_anchor_identifier,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TrawlerSpecificCommandDetailPresentation) Reset() {
	*x = TrawlerSpecificCommandDetailPresentation{}
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerSpecificCommandDetailPresentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerSpecificCommandDetailPresentation) ProtoMessage() {}

func (x *TrawlerSpecificCommandDetailPresentation) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_presentation_v1_presentation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerSpecificCommandDetailPresentation.ProtoReflect.Descriptor instead.
func (*TrawlerSpecificCommandDetailPresentation) Descriptor() ([]byte, []int) {
	return file_trawl_presentation_v1_presentation_proto_rawDescGZIP(), []int{6}
}

func (x *TrawlerSpecificCommandDetailPresentation) GetDetailDisplayName() string {
	if x != nil {
		return x.DetailDisplayName
	}
	return ""
}

func (x *TrawlerSpecificCommandDetailPresentation) GetDetailDisplayNameFixedAnchorIdentifier() string {
	if x != nil && x.DetailDisplayNameFixedAnchorIdentifier != nil {
		return *x.DetailDisplayNameFixedAnchorIdentifier
	}
	return ""
}

func (x *TrawlerSpecificCommandDetailPresentation) GetFieldsInDisplayOrder() []*TrawlerSpecificCommandDetailPresentationField {
	if x != nil {
		return x.FieldsInDisplayOrder
	}
	return nil
}

func (x *TrawlerSpecificCommandDetailPresentation) GetBody() isTrawlerSpecificCommandDetailPresentation_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TrawlerSpecificCommandDetailPresentation) GetBodyText() string {
	if x != nil {
		if x, ok := x.Body.(*TrawlerSpecificCommandDetailPresentation_BodyText); ok {
			return x.BodyText
		}
	}
	return ""
}

func (x *TrawlerSpecificCommandDetailPresentation) GetBodyUnavailableExplanation() string {
	if x != nil {
		if x, ok := x.Body.(*TrawlerSpecificCommandDetailPresentation_BodyUnavailableExplanation); ok {
			return x.BodyUnavailableExplanation
		}
	}
	return ""
}

func (x *TrawlerSpecificCommandDetailPresentation) GetBodyFixedAnchorIdentifier() string {
	if x != nil && x.BodyFixedAnchorIdentifier != nil {
		return *x.BodyFixedAnchorIdentifier
	}
	return ""
}

type isTrawlerSpecificCommandDetailPresentation_Body interface {
	isTrawlerSpecificCommandDetailPresentation_Body()
}

type TrawlerSpecificCommandDetailPresentation_BodyText struct {
	BodyText string `protobuf:"bytes,4,opt,name=body_text,json=bodyText,proto3,oneof"`
}

type TrawlerSpecificCommandDetailPresentation_BodyUnavailableExplanation struct {
	BodyUnavailableExplanation string `protobuf:"bytes,5,opt,name=body_unavailable_explanation,json=bodyUnavailableExplanation,proto3,oneof"`
}

func (*TrawlerSpecificCommandDetailPresentation_BodyText) isTrawlerSpecificCommandDetailPresentation_Body() {
}

func (*TrawlerSpecificCommandDetailPresentation_BodyUnavailableExplanation) isTrawlerSpecificCommandDetailPresentation_Body() {
}

var File_trawl_presentation_v1_presentation_proto protoreflect.FileDescriptor

const file_trawl_presentation_v1_presentation_proto_rawDesc = "" +
	"\n" +
	"(trawl/presentation/v1/presentation.proto\x12\x15trawl.presentation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x01\n" +
	"\fCalendarDate\x12#\n" +
	"\rcalendar_year\x18\x01 \x01(\x05R\fcalendarYear\x122\n" +
	"\x15calendar_month_number\x18\x02 \x01(\x05R\x13calendarMonthNumber\x121\n" +
	"\x15calendar_day_of_month\x18\x03 \x01(\x05R\x12calendarDayOfMonth\"\xd2\x01\n" +
	"%ArchiveRecordAssociatedTimeForDisplay\x12;\n" +
	"\n" +
	"exact_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texactTime\x12J\n" +
	"\rcalendar_date\x18\x02 \x01(\v2#.trawl.presentation.v1.CalendarDateH\x00R\fcalendarDateB \n" +
	"\x1earchive_record_associated_time\"\xa6\x03\n" +
	"'TrawlerSpecificCommandPresentationValue\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12'\n" +
	"\x0eunsigned_count\x18\x02 \x01(\x04H\x00R\runsignedCount\x12\x99\x01\n" +
	"*archive_record_associated_time_for_display\x18\x03 \x01(\v2<.trawl.presentation.v1.ArchiveRecordAssociatedTimeForDisplayH\x00R%archiveRecordAssociatedTimeForDisplay\x12\x90\x01\n" +
	"Fcanonical_record_reference_for_globally_routable_trawl_link_assignment\x18\x04 \x01(\tH\x00R>canonicalRecordReferenceForGloballyRoutableTrawlLinkAssignmentB\r\n" +
	"\vtyped_value\"\xb0\x01\n" +
	")TrawlerSpecificCommandListPresentationRow\x12\x82\x01\n" +
	"\x1ecolumn_values_in_display_order\x18\x01 \x03(\v2>.trawl.presentation.v1.TrawlerSpecificCommandPresentationValueR\x1acolumnValuesInDisplayOrder\"\xdf\x03\n" +
	"&TrawlerSpecificCommandListPresentation\x12@\n" +
	"\x1dcolumn_display_names_in_order\x18\x01 \x03(\tR\x19columnDisplayNamesInOrder\x12s\n" +
	"\x15rows_in_display_order\x18\x02 \x03(\v2@.trawl.presentation.v1.TrawlerSpecificCommandListPresentationRowR\x12rowsInDisplayOrder\x123\n" +
	"\x15exact_total_row_count\x18\x03 \x01(\x04H\x00R\x12exactTotalRowCount\x12>\n" +
	"\x1blower_bound_total_row_count\x18\x04 \x01(\x04H\x00R\x17lowerBoundTotalRowCount\x12&\n" +
	"\x0fmore_rows_exist\x18\x05 \x01(\bR\rmoreRowsExist\x12N\n" +
	"%concise_text_shown_when_list_is_empty\x18\x06 \x01(\tR\x1fconciseTextShownWhenListIsEmptyB\x11\n" +
	"\x0ftotal_row_count\"\xa8\x02\n" +
	"-TrawlerSpecificCommandDetailPresentationField\x12,\n" +
	"\x12field_display_name\x18\x01 \x01(\tR\x10fieldDisplayName\x12_\n" +
	"\vfield_value\x18\x02 \x01(\v2>.trawl.presentation.v1.TrawlerSpecificCommandPresentationValueR\n" +
	"fieldValue\x12F\n" +
	"\x1dfield_fixed_anchor_identifier\x18\x03 \x01(\tH\x00R\x1afieldFixedAnchorIdentifier\x88\x01\x01B \n" +
	"\x1e_field_fixed_anchor_identifier\"\xbb\x04\n" +
	"(TrawlerSpecificCommandDetailPresentation\x12.\n" +
	"\x13detail_display_name\x18\x01 \x01(\tR\x11detailDisplayName\x12`\n" +
	"+detail_display_name_fixed_anchor_identifier\x18\x02 \x01(\tH\x01R&detailDisplayNameFixedAnchorIdentifier\x88\x01\x01\x12{\n" +
	"\x17fields_in_display_order\x18\x03 \x03(\v2D.trawl.presentation.v1.TrawlerSpecificCommandDetailPresentationFieldR\x14fieldsInDisplayOrder\x12\x1d\n" +
	"\tbody_text\x18\x04 \x01(\tH\x00R\bbodyText\x12B\n" +
	"\x1cbody_unavailable_explanation\x18\x05 \x01(\tH\x00R\x1abodyUnavailableExplanation\x12D\n" +
	"\x1cbody_fixed_anchor_identifier\x18\x06 \x01(\tH\x02R\x19bodyFixedAnchorIdentifier\x88\x01\x01B\x06\n" +
	"\x04bodyB.\n" +
	",_detail_display_name_fixed_anchor_identifierB\x1f\n" +
	"\x1d_body_fixed_anchor_identifierBTZRgithub.com/opentrawl/opentrawl/trawlkit/proto/trawl/presentation/v1;presentationv1b\x06proto3"

var (
	file_trawl_presentation_v1_presentation_proto_rawDescOnce sync.Once
	file_trawl_presentation_v1_presentation_proto_rawDescData []byte
)

func file_trawl_presentation_v1_presentation_proto_rawDescGZIP() []byte {
	file_trawl_presentation_v1_presentation_proto_rawDescOnce.Do(func() {
		file_trawl_presentation_v1_presentation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trawl_presentation_v1_presentation_proto_rawDesc), len(file_trawl_presentation_v1_presentation_proto_rawDesc)))
	})
	return file_trawl_presentation_v1_presentation_proto_rawDescData
}

var file_trawl_presentation_v1_presentation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_trawl_presentation_v1_presentation_proto_goTypes = []any{
	(*CalendarDate)(nil),                                  // 0: trawl.presentation.v1.CalendarDate
	(*ArchiveRecordAssociatedTimeForDisplay)(nil),         // 1: trawl.presentation.v1.ArchiveRecordAssociatedTimeForDisplay
	(*TrawlerSpecificCommandPresentationValue)(nil),       // 2: trawl.presentation.v1.TrawlerSpecificCommandPresentationValue
	(*TrawlerSpecificCommandListPresentationRow)(nil),     // 3: trawl.presentation.v1.TrawlerSpecificCommandListPresentationRow
	(*TrawlerSpecificCommandListPresentation)(nil),        // 4: trawl.presentation.v1.TrawlerSpecificCommandListPresentation
	(*TrawlerSpecificCommandDetailPresentationField)(nil), // 5: trawl.presentation.v1.TrawlerSpecificCommandDetailPresentationField
	(*TrawlerSpecificCommandDetailPresentation)(nil),      // 6: trawl.presentation.v1.TrawlerSpecificCommandDetailPresentation
	(*timestamppb.Timestamp)(nil),                         // 7: google.protobuf.Timestamp
}
var file_trawl_presentation_v1_presentation_proto_depIdxs = []int32{
	7, // 0: trawl.presentation.v1.ArchiveRecordAssociatedTimeForDisplay.exact_time:type_name -> google.protobuf.Timestamp
	0, // 1: trawl.presentation.v1.ArchiveRecordAssociatedTimeForDisplay.calendar_date:type_name -> trawl.presentation.v1.CalendarDate
	1, // 2: trawl.presentation.v1.TrawlerSpecificCommandPresentationValue.archive_record_associated_time_for_display:type_name -> trawl.presentation.v1.ArchiveRecordAssociatedTimeForDisplay
	2, // 3: trawl.presentation.v1.TrawlerSpecificCommandListPresentationRow.column_values_in_display_order:type_name -> trawl.presentation.v1.TrawlerSpecificCommandPresentationValue
	3, // 4: trawl.presentation.v1.TrawlerSpecificCommandListPresentation.rows_in_display_order:type_name -> trawl.presentation.v1.TrawlerSpecificCommandListPresentationRow
	2, // 5: trawl.presentation.v1.TrawlerSpecificCommandDetailPresentationField.field_value:type_name -> trawl.presentation.v1.TrawlerSpecificCommandPresentationValue
	5, // 6: trawl.presentation.v1.TrawlerSpecificCommandDetailPresentation.fields_in_display_order:type_name -> trawl.presentation.v1.TrawlerSpecificCommandDetailPresentationField
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_trawl_presentation_v1_presentation_proto_init() }
func file_trawl_presentation_v1_presentation_proto_init() {
	if File_trawl_presentation_v1_presentation_proto != nil {
		return
	}
	file_trawl_presentation_v1_presentation_proto_msgTypes[1].OneofWrappers = []any{
		(*ArchiveRecordAssociatedTimeForDisplay_ExactTime)(nil),
		(*ArchiveRecordAssociatedTimeForDisplay_CalendarDate)(nil),
	}
	file_trawl_presentation_v1_presentation_proto_msgTypes[2].OneofWrappers = []any{
		(*TrawlerSpecificCommandPresentationValue_Text)(nil),
		(*TrawlerSpecificCommandPresentationValue_UnsignedCount)(nil),
		(*TrawlerSpecificCommandPresentationValue_ArchiveRecordAssociatedTimeForDisplay)(nil),
		(*TrawlerSpecificCommandPresentationValue_CanonicalRecordReferenceForGloballyRoutableTrawlLinkAssignment)(nil),
	}
	file_trawl_presentation_v1_presentation_proto_msgTypes[4].OneofWrappers = []any{
		(*TrawlerSpecificCommandListPresentation_ExactTotalRowCount)(nil),
		(*TrawlerSpecificCommandListPresentation_LowerBoundTotalRowCount)(nil),
	}
	file_trawl_presentation_v1_presentation_proto_msgTypes[5].OneofWrappers = []any{}
	file_trawl_presentation_v1_presentation_proto_msgTypes[6].OneofWrappers = []any{
		(*TrawlerSpecificCommandDetailPresentation_BodyText)(nil),
		(*TrawlerSpecificCommandDetailPresentation_BodyUnavailableExplanation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trawl_presentation_v1_presentation_proto_rawDesc), len(file_trawl_presentation_v1_presentation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trawl_presentation_v1_presentation_proto_goTypes,
		DependencyIndexes: file_trawl_presentation_v1_presentation_proto_depIdxs,
		MessageInfos:      file_trawl_presentation_v1_presentation_proto_msgTypes,
	}.Build()
	File_trawl_presentation_v1_presentation_proto = out.File
	file_trawl_presentation_v1_presentation_proto_goTypes = nil
	file_trawl_presentation_v1_presentation_proto_depIdxs = nil
}
