// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trawl/gmail/open/open.proto

package gmailopen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenedGmailMessageRecord struct {
	state                                 protoimpl.MessageState          `protogen:"open.v1"`
	CanonicalGmailMessageRecordReference  string                          `protobuf:"bytes,1,opt,name=canonical_gmail_message_record_reference,json=canonicalGmailMessageRecordReference,proto3" json:"canonical_gmail_message_record_reference,omitempty"`
	GmailMessageIdentifier                string                          `protobuf:"bytes,2,opt,name=gmail_message_identifier,json=gmailMessageIdentifier,proto3" json:"gmail_message_identifier,omitempty"`
	GmailThreadIdentifier                 string                          `protobuf:"bytes,3,opt,name=gmail_thread_identifier,json=gmailThreadIdentifier,proto3" json:"gmail_thread_identifier,omitempty"`
	GmailMessageRfc3339Time               string                          `protobuf:"bytes,4,opt,name=gmail_message_rfc3339_time,json=gmailMessageRfc3339Time,proto3" json:"gmail_message_rfc3339_time,omitempty"`
	GmailMessageHeaders                   *OpenedGmailMessageHeaders      `protobuf:"bytes,5,opt,name=gmail_message_headers,json=gmailMessageHeaders,proto3" json:"gmail_message_headers,omitempty"`
	GmailLabelNames                       []string                        `protobuf:"bytes,6,rep,name=gmail_label_names,json=gmailLabelNames,proto3" json:"gmail_label_names,omitempty"`
	GmailMessageIsUnread                  bool                            `protobuf:"varint,7,opt,name=gmail_message_is_unread,json=gmailMessageIsUnread,proto3" json:"gmail_message_is_unread,omitempty"`
	GmailMessageAttachments               []*OpenedGmailMessageAttachment `protobuf:"bytes,8,rep,name=gmail_message_attachments,json=gmailMessageAttachments,proto3" json:"gmail_message_attachments,omitempty"`
	GmailMessageBodyText                  string                          `protobuf:"bytes,9,opt,name=gmail_message_body_text,json=gmailMessageBodyText,proto3" json:"gmail_message_body_text,omitempty"`
	GmailMessageBodyTextIsTruncated       bool                            `protobuf:"varint,10,opt,name=gmail_message_body_text_is_truncated,json=gmailMessageBodyTextIsTruncated,proto3" json:"gmail_message_body_text_is_truncated,omitempty"`
	OmittedGmailMessageBodyCharacterCount *int64                          `protobuf:"varint,11,opt,name=omitted_gmail_message_body_character_count,json=omittedGmailMessageBodyCharacterCount,proto3,oneof" json:"omitted_gmail_message_body_character_count,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *OpenedGmailMessageRecord) Reset() {
	*x = OpenedGmailMessageRecord{}
	mi := &file_trawl_gmail_open_open_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenedGmailMessageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenedGmailMessageRecord) ProtoMessage() {}

func (x *OpenedGmailMessageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_gmail_open_open_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenedGmailMessageRecord.ProtoReflect.Descriptor instead.
func (*OpenedGmailMessageRecord) Descriptor() ([]byte, []int) {
	return file_trawl_gmail_open_open_proto_rawDescGZIP(), []int{0}
}

func (x *OpenedGmailMessageRecord) GetCanonicalGmailMessageRecordReference() string {
	if x != nil {
		return x.CanonicalGmailMessageRecordReference
	}
	return ""
}

func (x *OpenedGmailMessageRecord) GetGmailMessageIdentifier() string {
	if x != nil {
		return x.GmailMessageIdentifier
	}
	return ""
}

func (x *OpenedGmailMessageRecord) GetGmailThreadIdentifier() string {
	if x != nil {
		return x.GmailThreadIdentifier
	}
	return ""
}

func (x *OpenedGmailMessageRecord) GetGmailMessageRfc3339Time() string {
	if x != nil {
		return x.GmailMessageRfc3339Time
	}
	return ""
}

func (x *OpenedGmailMessageRecord) GetGmailMessageHeaders() *OpenedGmailMessageHeaders {
	if x != nil {
		return x.GmailMessageHeaders
	}
	return nil
}

func (x *OpenedGmailMessageRecord) GetGmailLabelNames() []string {
	if x != nil {
		return x.GmailLabelNames
	}
	return nil
}

func (x *OpenedGmailMessageRecord) GetGmailMessageIsUnread() bool {
	if x != nil {
		return x.GmailMessageIsUnread
	}
	return false
}

func (x *OpenedGmailMessageRecord) GetGmailMessageAttachments() []*OpenedGmailMessageAttachment {
	if x != nil {
		return x.GmailMessageAttachments
	}
	return nil
}

func (x *OpenedGmailMessageRecord) GetGmailMessageBodyText() string {
	if x != nil {
		return x.GmailMessageBodyText
	}
	return ""
}

func (x *OpenedGmailMessageRecord) GetGmailMessageBodyTextIsTruncated() bool {
	if x != nil {
		return x.GmailMessageBodyTextIsTruncated
	}
	return false
}

func (x *OpenedGmailMessageRecord) GetOmittedGmailMessageBodyCharacterCount() int64 {
	if x != nil && x.OmittedGmailMessageBodyCharacterCount != nil {
		return *x.OmittedGmailMessageBodyCharacterCount
	}
	return 0
}

type OpenedGmailMessageHeaders struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	SenderDisplayName             *string                `protobuf:"bytes,1,opt,name=sender_display_name,json=senderDisplayName,proto3,oneof" json:"sender_display_name,omitempty"`
	SenderEmailAddress            *string                `protobuf:"bytes,2,opt,name=sender_email_address,json=senderEmailAddress,proto3,oneof" json:"sender_email_address,omitempty"`
	RecipientEmailAddresses       string                 `protobuf:"bytes,3,opt,name=recipient_email_addresses,json=recipientEmailAddresses,proto3" json:"recipient_email_addresses,omitempty"`
	CopiedRecipientEmailAddresses *string                `protobuf:"bytes,4,opt,name=copied_recipient_email_addresses,json=copiedRecipientEmailAddresses,proto3,oneof" json:"copied_recipient_email_addresses,omitempty"`
	GmailMessageSubject           string                 `protobuf:"bytes,5,opt,name=gmail_message_subject,json=gmailMessageSubject,proto3" json:"gmail_message_subject,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *OpenedGmailMessageHeaders) Reset() {
	*x = OpenedGmailMessageHeaders{}
	mi := &file_trawl_gmail_open_open_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenedGmailMessageHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenedGmailMessageHeaders) ProtoMessage() {}

func (x *OpenedGmailMessageHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_gmail_open_open_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenedGmailMessageHeaders.ProtoReflect.Descriptor instead.
func (*OpenedGmailMessageHeaders) Descriptor() ([]byte, []int) {
	return file_trawl_gmail_open_open_proto_rawDescGZIP(), []int{1}
}

func (x *OpenedGmailMessageHeaders) GetSenderDisplayName() string {
	if x != nil && x.SenderDisplayName != nil {
		return *x.SenderDisplayName
	}
	return ""
}

func (x *OpenedGmailMessageHeaders) GetSenderEmailAddress() string {
	if x != nil && x.SenderEmailAddress != nil {
		return *x.SenderEmailAddress
	}
	return ""
}

func (x *OpenedGmailMessageHeaders) GetRecipientEmailAddresses() string {
	if x != nil {
		return x.RecipientEmailAddresses
	}
	return ""
}

func (x *OpenedGmailMessageHeaders) GetCopiedRecipientEmailAddresses() string {
	if x != nil && x.CopiedRecipientEmailAddresses != nil {
		return *x.CopiedRecipientEmailAddresses
	}
	return ""
}

func (x *OpenedGmailMessageHeaders) GetGmailMessageSubject() string {
	if x != nil {
		return x.GmailMessageSubject
	}
	return ""
}

type OpenedGmailMessageAttachment struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AttachmentFilename  string                 `protobuf:"bytes,1,opt,name=attachment_filename,json=attachmentFilename,proto3" json:"attachment_filename,omitempty"`
	AttachmentMediaType string                 `protobuf:"bytes,2,opt,name=attachment_media_type,json=attachmentMediaType,proto3" json:"attachment_media_type,omitempty"`
	AttachmentByteCount int64                  `protobuf:"varint,3,opt,name=attachment_byte_count,json=attachmentByteCount,proto3" json:"attachment_byte_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OpenedGmailMessageAttachment) Reset() {
	*x = OpenedGmailMessageAttachment{}
	mi := &file_trawl_gmail_open_open_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenedGmailMessageAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenedGmailMessageAttachment) ProtoMessage() {}

func (x *OpenedGmailMessageAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_gmail_open_open_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenedGmailMessageAttachment.ProtoReflect.Descriptor instead.
func (*OpenedGmailMessageAttachment) Descriptor() ([]byte, []int) {
	return file_trawl_gmail_open_open_proto_rawDescGZIP(), []int{2}
}

func (x *OpenedGmailMessageAttachment) GetAttachmentFilename() string {
	if x != nil {
		return x.AttachmentFilename
	}
	return ""
}

func (x *OpenedGmailMessageAttachment) GetAttachmentMediaType() string {
	if x != nil {
		return x.AttachmentMediaType
	}
	return ""
}

func (x *OpenedGmailMessageAttachment) GetAttachmentByteCount() int64 {
	if x != nil {
		return x.AttachmentByteCount
	}
	return 0
}

var File_trawl_gmail_open_open_proto protoreflect.FileDescriptor

const file_trawl_gmail_open_open_proto_rawDesc = "" +
	"\n" +
	"\x1btrawl/gmail/open/open.proto\x12\x10trawl.gmail.open\"\xe6\x06\n" +
	"\x18OpenedGmailMessageRecord\x12V\n" +
	"(canonical_gmail_message_record_reference\x18\x01 \x01(\tR$canonicalGmailMessageRecordReference\x128\n" +
	"\x18gmail_message_identifier\x18\x02 \x01(\tR\x16gmailMessageIdentifier\x126\n" +
	"\x17gmail_thread_identifier\x18\x03 \x01(\tR\x15gmailThreadIdentifier\x12;\n" +
	"\x1agmail_message_rfc3339_time\x18\x04 \x01(\tR\x17gmailMessageRfc3339Time\x12_\n" +
	"\x15gmail_message_headers\x18\x05 \x01(\v2+.trawl.gmail.open.OpenedGmailMessageHeadersR\x13gmailMessageHeaders\x12*\n" +
	"\x11gmail_label_names\x18\x06 \x03(\tR\x0fgmailLabelNames\x125\n" +
	"\x17gmail_message_is_unread\x18\a \x01(\bR\x14gmailMessageIsUnread\x12j\n" +
	"\x19gmail_message_attachments\x18\b \x03(\v2..trawl.gmail.open.OpenedGmailMessageAttachmentR\x17gmailMessageAttachments\x125\n" +
	"\x17gmail_message_body_text\x18\t \x01(\tR\x14gmailMessageBodyText\x12M\n" +
	"$gmail_message_body_text_is_truncated\x18\n" +
	" \x01(\bR\x1fgmailMessageBodyTextIsTruncated\x12^\n" +
	"*omitted_gmail_message_body_character_count\x18\v \x01(\x03H\x00R%omittedGmailMessageBodyCharacterCount\x88\x01\x01B-\n" +
	"+_omitted_gmail_message_body_character_count\"\x9b\x03\n" +
	"\x19OpenedGmailMessageHeaders\x123\n" +
	"\x13sender_display_name\x18\x01 \x01(\tH\x00R\x11senderDisplayName\x88\x01\x01\x125\n" +
	"\x14sender_email_address\x18\x02 \x01(\tH\x01R\x12senderEmailAddress\x88\x01\x01\x12:\n" +
	"\x19recipient_email_addresses\x18\x03 \x01(\tR\x17recipientEmailAddresses\x12L\n" +
	" copied_recipient_email_addresses\x18\x04 \x01(\tH\x02R\x1dcopiedRecipientEmailAddresses\x88\x01\x01\x122\n" +
	"\x15gmail_message_subject\x18\x05 \x01(\tR\x13gmailMessageSubjectB\x16\n" +
	"\x14_sender_display_nameB\x17\n" +
	"\x15_sender_email_addressB#\n" +
	"!_copied_recipient_email_addresses\"\xb7\x01\n" +
	"\x1cOpenedGmailMessageAttachment\x12/\n" +
	"\x13attachment_filename\x18\x01 \x01(\tR\x12attachmentFilename\x122\n" +
	"\x15attachment_media_type\x18\x02 \x01(\tR\x13attachmentMediaType\x122\n" +
	"\x15attachment_byte_count\x18\x03 \x01(\x03R\x13attachmentByteCountBGZEgithub.com/opentrawl/opentrawl/gmail/proto/trawl/gmail/open;gmailopenb\x06proto3"

var (
	file_trawl_gmail_open_open_proto_rawDescOnce sync.Once
	file_trawl_gmail_open_open_proto_rawDescData []byte
)

func file_trawl_gmail_open_open_proto_rawDescGZIP() []byte {
	file_trawl_gmail_open_open_proto_rawDescOnce.Do(func() {
		file_trawl_gmail_open_open_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trawl_gmail_open_open_proto_rawDesc), len(file_trawl_gmail_open_open_proto_rawDesc)))
	})
	return file_trawl_gmail_open_open_proto_rawDescData
}

var file_trawl_gmail_open_open_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trawl_gmail_open_open_proto_goTypes = []any{
	(*OpenedGmailMessageRecord)(nil),     // 0: trawl.gmail.open.OpenedGmailMessageRecord
	(*OpenedGmailMessageHeaders)(nil),    // 1: trawl.gmail.open.OpenedGmailMessageHeaders
	(*OpenedGmailMessageAttachment)(nil), // 2: trawl.gmail.open.OpenedGmailMessageAttachment
}
var file_trawl_gmail_open_open_proto_depIdxs = []int32{
	1, // 0: trawl.gmail.open.OpenedGmailMessageRecord.gmail_message_headers:type_name -> trawl.gmail.open.OpenedGmailMessageHeaders
	2, // 1: trawl.gmail.open.OpenedGmailMessageRecord.gmail_message_attachments:type_name -> trawl.gmail.open.OpenedGmailMessageAttachment
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trawl_gmail_open_open_proto_init() }
func file_trawl_gmail_open_open_proto_init() {
	if File_trawl_gmail_open_open_proto != nil {
		return
	}
	file_trawl_gmail_open_open_proto_msgTypes[0].OneofWrappers = []any{}
	file_trawl_gmail_open_open_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trawl_gmail_open_open_proto_rawDesc), len(file_trawl_gmail_open_open_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trawl_gmail_open_open_proto_goTypes,
		DependencyIndexes: file_trawl_gmail_open_open_proto_depIdxs,
		MessageInfos:      file_trawl_gmail_open_open_proto_msgTypes,
	}.Build()
	File_trawl_gmail_open_open_proto = out.File
	file_trawl_gmail_open_open_proto_goTypes = nil
	file_trawl_gmail_open_open_proto_depIdxs = nil
}
