syntax = "proto3";

package trawl.note;

import "google/protobuf/timestamp.proto";
import "trawl/identity/identity.proto";

option go_package = "github.com/opentrawl/opentrawl/trawlkit/proto/trawl/note;note";

message NoteRecord {
  trawl.identity.CanonicalArchiveRecordReference canonical_record_reference = 1;
  string note_display_name = 2;
  string note_folder_display_name = 3;
  google.protobuf.Timestamp note_modified_time = 4;
}

message NoteListResponse {
  repeated NoteRecord note_records_newest_first = 1;
  uint64 total_matching_note_count = 2;
  bool more_matching_notes_exist = 3;
}

message NoteFolderRecord {
  string note_folder_display_name = 1;
  uint64 note_count = 2;
  google.protobuf.Timestamp most_recent_note_modified_time = 3;
}

message NoteFolderListResponse {
  repeated NoteFolderRecord note_folder_records_in_display_order = 1;
}

message RecoveredNoteVersionRecord {
  trawl.identity.CanonicalArchiveRecordReference canonical_record_reference = 1;
  google.protobuf.Timestamp recovered_note_version_time = 2;
  uint64 number_of_more_recent_recovered_note_versions = 3;
}

message RecoveredNoteVersionListResponse {
  repeated RecoveredNoteVersionRecord recovered_note_version_records_newest_first = 1;
  uint64 total_recovered_note_version_count = 2;
  bool more_recovered_note_versions_exist = 3;
  google.protobuf.Timestamp requested_note_version_at_or_before_time = 4;
}

message AvailableNoteBody {
  string note_body_text = 1;
}

message OpenedNoteBody {
  oneof body_availability {
    AvailableNoteBody available_note_body = 1;
    string unavailable_note_body_explanation = 2;
  }
}

message OpenedNoteRecord {
  trawl.identity.CanonicalArchiveRecordReference canonical_note_record_reference = 1;
  trawl.identity.CanonicalArchiveRecordReference canonical_opened_note_version_record_reference = 2;
  string note_display_name = 3;
  string note_folder_display_name = 4;
  google.protobuf.Timestamp note_created_time = 5;
  google.protobuf.Timestamp note_modified_time = 6;
  google.protobuf.Timestamp opened_note_version_time = 7;
  uint64 recovered_note_version_count = 8;
  OpenedNoteBody opened_note_body = 9;
  bool specific_recovered_note_version_was_opened = 10;
  trawl.identity.RecordAnchorIdentifier note_display_name_anchor = 11;
  trawl.identity.RecordAnchorIdentifier opened_note_body_anchor = 12;
}
