syntax = "proto3";

package trawl.federation;

import "google/protobuf/timestamp.proto";
import "trawl/conversation/conversation.proto";
import "trawl/identity/identity.proto";
import "trawl/person/person.proto";
import "trawl/search/search.proto";
import "trawl/status/status.proto";
import "trawl/update/update.proto";

option go_package = "github.com/opentrawl/opentrawl/trawlkit/proto/trawl/federation;federation";

enum OperationOutcome {
  OPERATION_OUTCOME_UNSPECIFIED = 0;
  OPERATION_OUTCOME_COMPLETE = 1;
  OPERATION_OUTCOME_PARTIAL = 2;
  OPERATION_OUTCOME_FAILED = 3;
}

enum FailureCode {
  FAILURE_CODE_UNSPECIFIED = 0;
  FAILURE_CODE_UNAVAILABLE = 1;
  FAILURE_CODE_PERMISSION = 2;
  FAILURE_CODE_AUTHENTICATION = 3;
  FAILURE_CODE_INVALID_INPUT = 4;
  FAILURE_CODE_NOT_FOUND = 5;
  FAILURE_CODE_TIMEOUT = 6;
  FAILURE_CODE_INTERNAL = 7;
  FAILURE_CODE_CANCELLED = 8;
  FAILURE_CODE_ALREADY_UPDATING = 9;
}

enum SharedTrawlerOperation {
  SHARED_TRAWLER_OPERATION_UNSPECIFIED = 0;
  SHARED_TRAWLER_OPERATION_METADATA = 1;
  SHARED_TRAWLER_OPERATION_STATUS = 2;
  SHARED_TRAWLER_OPERATION_UPDATE = 3;
  SHARED_TRAWLER_OPERATION_SEARCH = 4;
  SHARED_TRAWLER_OPERATION_OPEN = 5;
  SHARED_TRAWLER_OPERATION_WHO = 6;
  SHARED_TRAWLER_OPERATION_CONVERSATIONS = 7;
  SHARED_TRAWLER_OPERATION_MESSAGES = 8;
}

message TrawlerOperationFailure {
  trawl.identity.RegisteredTrawlerIdentity failed_trawler = 1;
  string registered_trawler_display_name = 2;
  FailureCode failure_code = 3;
  string failure_message = 4;
}

message TrawlerSkippedFromOperation {
  trawl.identity.RegisteredTrawlerIdentity skipped_trawler = 1;
  string registered_trawler_display_name = 2;
  string skip_reason = 3;
}

message TrawlerBranding {
  string symbol_name = 1;
  string accent_color = 2;
  string icon_path = 3;
  string bundle_identifier = 4;
  string artwork_bundle_identifier = 5;
}

message TrawlerPrivacyBoundary {
  string archive_content_read_by_trawler = 1;
  string archive_content_that_leaves_machine = 2;
  string network_requests_made_by_trawler = 3;
}

enum RegisteredTrawlerCommandDiscoveryPlacement {
  REGISTERED_TRAWLER_COMMAND_DISCOVERY_PLACEMENT_UNSPECIFIED = 0;
  REGISTERED_TRAWLER_COMMAND_DISCOVERY_PLACEMENT_SHOWN_IN_BARE_TRAWL_OVERVIEW_AND_TRAWLER_NAMESPACE_HELP = 1;
  REGISTERED_TRAWLER_COMMAND_DISCOVERY_PLACEMENT_SHOWN_ONLY_IN_TRAWLER_NAMESPACE_HELP = 2;
  REGISTERED_TRAWLER_COMMAND_DISCOVERY_PLACEMENT_ROUTED_ONLY_BY_ROOT_SHARED_COMMAND = 3;
}

message RegisteredTrawlerCommandFlagDeclaration {
  string trawler_command_flag_name = 1;
  string trawler_command_flag_help_description = 2;
  string trawler_command_flag_default_value = 3;
}

message RegisteredTrawlerCommandDeclaration {
  oneof registered_trawler_command {
    SharedTrawlerOperation shared_trawler_operation = 1;
    string bespoke_trawler_command_name = 2;
  }
  string trawler_command_help_description = 3;
  repeated string trawler_command_positional_argument_names = 4;
  repeated RegisteredTrawlerCommandFlagDeclaration trawler_command_flag_declarations = 5;
  RegisteredTrawlerCommandDiscoveryPlacement trawler_command_discovery_placement = 6;
}

message RegisteredTrawlerManifest {
  trawl.identity.RegisteredTrawlerIdentity registered_trawler = 1;
  string registered_trawler_command_name = 2;
  string registered_trawler_display_name = 3;
  TrawlerBranding trawler_branding = 4;
  repeated string registered_trawler_aliases = 7;
  TrawlerPrivacyBoundary registered_trawler_privacy_boundary = 8;
  repeated RegisteredTrawlerCommandDeclaration registered_trawler_command_declarations = 9;
}

enum RegisteredTrawlerReleaseState {
  REGISTERED_TRAWLER_RELEASE_STATE_UNSPECIFIED = 0;
  REGISTERED_TRAWLER_RELEASE_STATE_AVAILABLE = 1;
  REGISTERED_TRAWLER_RELEASE_STATE_COMING_SOON = 2;
}

message RegisteredTrawlerCatalogEntry {
  RegisteredTrawlerManifest registered_trawler_manifest = 1;
  RegisteredTrawlerReleaseState registered_trawler_release_state = 2;
  bool registered_trawler_is_enabled = 3;
}

message TrawlerStatusResult {
  trawl.identity.RegisteredTrawlerIdentity registered_trawler = 1;
  string registered_trawler_command_name = 2;
  string registered_trawler_display_name = 3;
  trawl.status.TrawlerStatusResponse trawler_status_response = 4;
}

message SearchPersonFilterResolution {
  string person_filter_text = 1;
  repeated trawl.person.ExactPersonFilterIdentifier resolved_exact_person_filter_identifiers = 2;
}

message FederatedSearchMatch {
  trawl.identity.RecordAnchorIdentifier record_anchor = 1;
  trawl.search.SearchMatchPresentation search_match_presentation = 2;
  trawl.identity.GloballyRoutableTrawlLink trawl_link = 3;
}

message TrawlerSearchResult {
  trawl.identity.RegisteredTrawlerIdentity registered_trawler = 1;
  string registered_trawler_display_name = 2;
  SearchPersonFilterResolution search_person_filter_resolution = 3;
  repeated FederatedSearchMatch search_matches_from_trawler_in_display_order = 4;
  uint64 total_search_matches = 5;
  bool more_search_matches_exist = 6;
  bool total_search_matches_is_lower_bound = 7;
}

message FederatedTrawlerStatusOperation {
  OperationOutcome outcome = 1;
  repeated TrawlerStatusResult trawler_status_results = 2;
  repeated TrawlerOperationFailure operation_failures = 3;
  repeated TrawlerSkippedFromOperation trawlers_skipped_from_operation = 4;
  repeated RegisteredTrawlerCatalogEntry registered_trawler_catalog = 5;
}

message FederatedTrawlerSearchOperation {
  OperationOutcome outcome = 1;
  repeated TrawlerSearchResult trawler_search_results = 2;
  repeated FederatedSearchMatch search_matches_in_display_order = 3;
  repeated TrawlerOperationFailure operation_failures = 4;
  repeated TrawlerSkippedFromOperation trawlers_skipped_from_operation = 5;
  uint32 result_limit = 6;
  bool more_search_matches_exist = 7;
}

message TrawlerArchiveUpdateResult {
  trawl.identity.RegisteredTrawlerIdentity registered_trawler = 1;
  string registered_trawler_display_name = 2;
  trawl.update.TrawlerArchiveUpdateReport trawler_archive_update_report = 3;
}

message PeopleArchiveUpdateFailureAfterTrawlerArchiveUpdate {
  trawl.identity.RegisteredTrawlerIdentity successfully_updated_trawler = 1;
  string successfully_updated_trawler_display_name = 2;
}

message FederatedTrawlerArchiveUpdateOperation {
  OperationOutcome outcome = 1;
  repeated TrawlerArchiveUpdateResult trawler_archive_update_results = 2;
  repeated TrawlerOperationFailure operation_failures = 3;
  repeated TrawlerSkippedFromOperation trawlers_skipped_from_operation = 4;
  repeated PeopleArchiveUpdateFailureAfterTrawlerArchiveUpdate people_archive_update_failures_after_trawler_archive_update = 5;
}

message TrawlerConversationListResult {
  trawl.identity.RegisteredTrawlerIdentity registered_trawler = 1;
  string registered_trawler_display_name = 2;
  trawl.conversation.ConversationListResponse conversation_list_response = 3;
}

message FederatedConversationRecord {
  trawl.conversation.ConversationRecord conversation_record = 1;
  trawl.identity.GloballyRoutableTrawlLink trawl_link = 2;
}

message FederatedTrawlerConversationListOperation {
  OperationOutcome outcome = 1;
  repeated TrawlerConversationListResult trawler_conversation_list_results = 2;
  repeated FederatedConversationRecord conversation_records_newest_first = 3;
  repeated TrawlerOperationFailure operation_failures = 4;
  repeated TrawlerSkippedFromOperation trawlers_skipped_from_operation = 5;
  uint32 result_limit = 6;
  bool more_conversation_records_exist = 7;
  string person_display_name_resolved_across_trawler_archives_for_conversation_filter = 8;
}

message FederatedPersonMatchCandidate {
  string person_display_name = 1;
  repeated string alternative_person_display_names = 2;
  string person_name_or_human_readable_contact_value_that_matched_query = 3;
  google.protobuf.Timestamp latest_matching_archive_record_time = 4;
  uint64 message_count_involving_person_across_trawlers = 5;
  repeated trawl.person.PersonMatchFactsFromTrawler person_match_facts_from_trawlers = 6;
  trawl.identity.GloballyRoutableTrawlLink person_trawl_link = 7;
  repeated trawl.person.PersonMessageCountFromTrawlerArchive person_message_counts_from_trawler_archives = 8;
}

message FederatedTrawlerPersonMatchOperation {
  OperationOutcome outcome = 1;
  repeated FederatedPersonMatchCandidate person_match_candidates = 2;
  repeated TrawlerOperationFailure operation_failures = 3;
  repeated TrawlerSkippedFromOperation trawlers_skipped_from_operation = 4;
  string person_query_used_to_find_candidates = 5;
}
