// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trawl/person/v1/person.proto

package personv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonContactMethodKind int32

const (
	PersonContactMethodKind_PERSON_CONTACT_METHOD_KIND_UNSPECIFIED        PersonContactMethodKind = 0
	PersonContactMethodKind_PERSON_CONTACT_METHOD_KIND_EMAIL_ADDRESS      PersonContactMethodKind = 1
	PersonContactMethodKind_PERSON_CONTACT_METHOD_KIND_PHONE_NUMBER       PersonContactMethodKind = 2
	PersonContactMethodKind_PERSON_CONTACT_METHOD_KIND_POSTAL_ADDRESS     PersonContactMethodKind = 3
	PersonContactMethodKind_PERSON_CONTACT_METHOD_KIND_ACCOUNT_IDENTIFIER PersonContactMethodKind = 4
)

// Enum value maps for PersonContactMethodKind.
var (
	PersonContactMethodKind_name = map[int32]string{
		0: "PERSON_CONTACT_METHOD_KIND_UNSPECIFIED",
		1: "PERSON_CONTACT_METHOD_KIND_EMAIL_ADDRESS",
		2: "PERSON_CONTACT_METHOD_KIND_PHONE_NUMBER",
		3: "PERSON_CONTACT_METHOD_KIND_POSTAL_ADDRESS",
		4: "PERSON_CONTACT_METHOD_KIND_ACCOUNT_IDENTIFIER",
	}
	PersonContactMethodKind_value = map[string]int32{
		"PERSON_CONTACT_METHOD_KIND_UNSPECIFIED":        0,
		"PERSON_CONTACT_METHOD_KIND_EMAIL_ADDRESS":      1,
		"PERSON_CONTACT_METHOD_KIND_PHONE_NUMBER":       2,
		"PERSON_CONTACT_METHOD_KIND_POSTAL_ADDRESS":     3,
		"PERSON_CONTACT_METHOD_KIND_ACCOUNT_IDENTIFIER": 4,
	}
)

func (x PersonContactMethodKind) Enum() *PersonContactMethodKind {
	p := new(PersonContactMethodKind)
	*p = x
	return p
}

func (x PersonContactMethodKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonContactMethodKind) Descriptor() protoreflect.EnumDescriptor {
	return file_trawl_person_v1_person_proto_enumTypes[0].Descriptor()
}

func (PersonContactMethodKind) Type() protoreflect.EnumType {
	return &file_trawl_person_v1_person_proto_enumTypes[0]
}

func (x PersonContactMethodKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonContactMethodKind.Descriptor instead.
func (PersonContactMethodKind) EnumDescriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{0}
}

type PersonRoleInArchiveRecord int32

const (
	PersonRoleInArchiveRecord_PERSON_ROLE_IN_ARCHIVE_RECORD_UNSPECIFIED PersonRoleInArchiveRecord = 0
	PersonRoleInArchiveRecord_PERSON_ROLE_IN_ARCHIVE_RECORD_SENDER      PersonRoleInArchiveRecord = 1
	PersonRoleInArchiveRecord_PERSON_ROLE_IN_ARCHIVE_RECORD_RECIPIENT   PersonRoleInArchiveRecord = 2
	PersonRoleInArchiveRecord_PERSON_ROLE_IN_ARCHIVE_RECORD_AUTHOR      PersonRoleInArchiveRecord = 3
	PersonRoleInArchiveRecord_PERSON_ROLE_IN_ARCHIVE_RECORD_ORGANIZER   PersonRoleInArchiveRecord = 4
	PersonRoleInArchiveRecord_PERSON_ROLE_IN_ARCHIVE_RECORD_ATTENDEE    PersonRoleInArchiveRecord = 5
	PersonRoleInArchiveRecord_PERSON_ROLE_IN_ARCHIVE_RECORD_PARTICIPANT PersonRoleInArchiveRecord = 6
)

// Enum value maps for PersonRoleInArchiveRecord.
var (
	PersonRoleInArchiveRecord_name = map[int32]string{
		0: "PERSON_ROLE_IN_ARCHIVE_RECORD_UNSPECIFIED",
		1: "PERSON_ROLE_IN_ARCHIVE_RECORD_SENDER",
		2: "PERSON_ROLE_IN_ARCHIVE_RECORD_RECIPIENT",
		3: "PERSON_ROLE_IN_ARCHIVE_RECORD_AUTHOR",
		4: "PERSON_ROLE_IN_ARCHIVE_RECORD_ORGANIZER",
		5: "PERSON_ROLE_IN_ARCHIVE_RECORD_ATTENDEE",
		6: "PERSON_ROLE_IN_ARCHIVE_RECORD_PARTICIPANT",
	}
	PersonRoleInArchiveRecord_value = map[string]int32{
		"PERSON_ROLE_IN_ARCHIVE_RECORD_UNSPECIFIED": 0,
		"PERSON_ROLE_IN_ARCHIVE_RECORD_SENDER":      1,
		"PERSON_ROLE_IN_ARCHIVE_RECORD_RECIPIENT":   2,
		"PERSON_ROLE_IN_ARCHIVE_RECORD_AUTHOR":      3,
		"PERSON_ROLE_IN_ARCHIVE_RECORD_ORGANIZER":   4,
		"PERSON_ROLE_IN_ARCHIVE_RECORD_ATTENDEE":    5,
		"PERSON_ROLE_IN_ARCHIVE_RECORD_PARTICIPANT": 6,
	}
)

func (x PersonRoleInArchiveRecord) Enum() *PersonRoleInArchiveRecord {
	p := new(PersonRoleInArchiveRecord)
	*p = x
	return p
}

func (x PersonRoleInArchiveRecord) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonRoleInArchiveRecord) Descriptor() protoreflect.EnumDescriptor {
	return file_trawl_person_v1_person_proto_enumTypes[1].Descriptor()
}

func (PersonRoleInArchiveRecord) Type() protoreflect.EnumType {
	return &file_trawl_person_v1_person_proto_enumTypes[1]
}

func (x PersonRoleInArchiveRecord) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonRoleInArchiveRecord.Descriptor instead.
func (PersonRoleInArchiveRecord) EnumDescriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{1}
}

type PersonRelatedToArchiveRecord struct {
	state                     protoimpl.MessageState    `protogen:"open.v1"`
	PersonDisplayName         string                    `protobuf:"bytes,1,opt,name=person_display_name,json=personDisplayName,proto3" json:"person_display_name,omitempty"`
	PersonRoleInArchiveRecord PersonRoleInArchiveRecord `protobuf:"varint,2,opt,name=person_role_in_archive_record,json=personRoleInArchiveRecord,proto3,enum=trawl.person.v1.PersonRoleInArchiveRecord" json:"person_role_in_archive_record,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PersonRelatedToArchiveRecord) Reset() {
	*x = PersonRelatedToArchiveRecord{}
	mi := &file_trawl_person_v1_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonRelatedToArchiveRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonRelatedToArchiveRecord) ProtoMessage() {}

func (x *PersonRelatedToArchiveRecord) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_person_v1_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonRelatedToArchiveRecord.ProtoReflect.Descriptor instead.
func (*PersonRelatedToArchiveRecord) Descriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{0}
}

func (x *PersonRelatedToArchiveRecord) GetPersonDisplayName() string {
	if x != nil {
		return x.PersonDisplayName
	}
	return ""
}

func (x *PersonRelatedToArchiveRecord) GetPersonRoleInArchiveRecord() PersonRoleInArchiveRecord {
	if x != nil {
		return x.PersonRoleInArchiveRecord
	}
	return PersonRoleInArchiveRecord_PERSON_ROLE_IN_ARCHIVE_RECORD_UNSPECIFIED
}

type PersonContactMethod struct {
	state                           protoimpl.MessageState  `protogen:"open.v1"`
	PersonContactMethodKind         PersonContactMethodKind `protobuf:"varint,1,opt,name=person_contact_method_kind,json=personContactMethodKind,proto3,enum=trawl.person.v1.PersonContactMethodKind" json:"person_contact_method_kind,omitempty"`
	PersonContactMethodLabel        string                  `protobuf:"bytes,2,opt,name=person_contact_method_label,json=personContactMethodLabel,proto3" json:"person_contact_method_label,omitempty"`
	PersonContactMethodDisplayValue string                  `protobuf:"bytes,3,opt,name=person_contact_method_display_value,json=personContactMethodDisplayValue,proto3" json:"person_contact_method_display_value,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *PersonContactMethod) Reset() {
	*x = PersonContactMethod{}
	mi := &file_trawl_person_v1_person_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonContactMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonContactMethod) ProtoMessage() {}

func (x *PersonContactMethod) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_person_v1_person_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonContactMethod.ProtoReflect.Descriptor instead.
func (*PersonContactMethod) Descriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{1}
}

func (x *PersonContactMethod) GetPersonContactMethodKind() PersonContactMethodKind {
	if x != nil {
		return x.PersonContactMethodKind
	}
	return PersonContactMethodKind_PERSON_CONTACT_METHOD_KIND_UNSPECIFIED
}

func (x *PersonContactMethod) GetPersonContactMethodLabel() string {
	if x != nil {
		return x.PersonContactMethodLabel
	}
	return ""
}

func (x *PersonContactMethod) GetPersonContactMethodDisplayValue() string {
	if x != nil {
		return x.PersonContactMethodDisplayValue
	}
	return ""
}

type PersonRecord struct {
	state                                                                protoimpl.MessageState `protogen:"open.v1"`
	CanonicalPersonRecordReferenceForGloballyRoutableTrawlLinkAssignment string                 `protobuf:"bytes,1,opt,name=canonical_person_record_reference_for_globally_routable_trawl_link_assignment,json=canonicalPersonRecordReferenceForGloballyRoutableTrawlLinkAssignment,proto3" json:"canonical_person_record_reference_for_globally_routable_trawl_link_assignment,omitempty"`
	PersonDisplayName                                                    string                 `protobuf:"bytes,2,opt,name=person_display_name,json=personDisplayName,proto3" json:"person_display_name,omitempty"`
	AlternativePersonDisplayNames                                        []string               `protobuf:"bytes,3,rep,name=alternative_person_display_names,json=alternativePersonDisplayNames,proto3" json:"alternative_person_display_names,omitempty"`
	PersonContactMethodsInDisplayOrder                                   []*PersonContactMethod `protobuf:"bytes,4,rep,name=person_contact_methods_in_display_order,json=personContactMethodsInDisplayOrder,proto3" json:"person_contact_methods_in_display_order,omitempty"`
	PersonFactContributingTrawlerDisplayNames                            []string               `protobuf:"bytes,5,rep,name=person_fact_contributing_trawler_display_names,json=personFactContributingTrawlerDisplayNames,proto3" json:"person_fact_contributing_trawler_display_names,omitempty"`
	unknownFields                                                        protoimpl.UnknownFields
	sizeCache                                                            protoimpl.SizeCache
}

func (x *PersonRecord) Reset() {
	*x = PersonRecord{}
	mi := &file_trawl_person_v1_person_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonRecord) ProtoMessage() {}

func (x *PersonRecord) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_person_v1_person_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonRecord.ProtoReflect.Descriptor instead.
func (*PersonRecord) Descriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{2}
}

func (x *PersonRecord) GetCanonicalPersonRecordReferenceForGloballyRoutableTrawlLinkAssignment() string {
	if x != nil {
		return x.CanonicalPersonRecordReferenceForGloballyRoutableTrawlLinkAssignment
	}
	return ""
}

func (x *PersonRecord) GetPersonDisplayName() string {
	if x != nil {
		return x.PersonDisplayName
	}
	return ""
}

func (x *PersonRecord) GetAlternativePersonDisplayNames() []string {
	if x != nil {
		return x.AlternativePersonDisplayNames
	}
	return nil
}

func (x *PersonRecord) GetPersonContactMethodsInDisplayOrder() []*PersonContactMethod {
	if x != nil {
		return x.PersonContactMethodsInDisplayOrder
	}
	return nil
}

func (x *PersonRecord) GetPersonFactContributingTrawlerDisplayNames() []string {
	if x != nil {
		return x.PersonFactContributingTrawlerDisplayNames
	}
	return nil
}

type PersonListResponse struct {
	state                                protoimpl.MessageState `protogen:"open.v1"`
	PersonRecordsInDisplayOrder          []*PersonRecord        `protobuf:"bytes,1,rep,name=person_records_in_display_order,json=personRecordsInDisplayOrder,proto3" json:"person_records_in_display_order,omitempty"`
	TotalMatchingPersonCount             uint64                 `protobuf:"varint,2,opt,name=total_matching_person_count,json=totalMatchingPersonCount,proto3" json:"total_matching_person_count,omitempty"`
	TotalMatchingPersonCountIsLowerBound bool                   `protobuf:"varint,3,opt,name=total_matching_person_count_is_lower_bound,json=totalMatchingPersonCountIsLowerBound,proto3" json:"total_matching_person_count_is_lower_bound,omitempty"`
	MoreMatchingPeopleExist              bool                   `protobuf:"varint,4,opt,name=more_matching_people_exist,json=moreMatchingPeopleExist,proto3" json:"more_matching_people_exist,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *PersonListResponse) Reset() {
	*x = PersonListResponse{}
	mi := &file_trawl_person_v1_person_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonListResponse) ProtoMessage() {}

func (x *PersonListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_person_v1_person_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonListResponse.ProtoReflect.Descriptor instead.
func (*PersonListResponse) Descriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{3}
}

func (x *PersonListResponse) GetPersonRecordsInDisplayOrder() []*PersonRecord {
	if x != nil {
		return x.PersonRecordsInDisplayOrder
	}
	return nil
}

func (x *PersonListResponse) GetTotalMatchingPersonCount() uint64 {
	if x != nil {
		return x.TotalMatchingPersonCount
	}
	return 0
}

func (x *PersonListResponse) GetTotalMatchingPersonCountIsLowerBound() bool {
	if x != nil {
		return x.TotalMatchingPersonCountIsLowerBound
	}
	return false
}

func (x *PersonListResponse) GetMoreMatchingPeopleExist() bool {
	if x != nil {
		return x.MoreMatchingPeopleExist
	}
	return false
}

type TrawlerPeopleSnapshot struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	TrawlerPersonIdentities []*TrawlerPersonIdentity `protobuf:"bytes,1,rep,name=trawler_person_identities,json=trawlerPersonIdentities,proto3" json:"trawler_person_identities,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TrawlerPeopleSnapshot) Reset() {
	*x = TrawlerPeopleSnapshot{}
	mi := &file_trawl_person_v1_person_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerPeopleSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerPeopleSnapshot) ProtoMessage() {}

func (x *TrawlerPeopleSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_person_v1_person_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerPeopleSnapshot.ProtoReflect.Descriptor instead.
func (*TrawlerPeopleSnapshot) Descriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{4}
}

func (x *TrawlerPeopleSnapshot) GetTrawlerPersonIdentities() []*TrawlerPersonIdentity {
	if x != nil {
		return x.TrawlerPersonIdentities
	}
	return nil
}

type TrawlerPersonIdentity struct {
	state                                                  protoimpl.MessageState                      `protogen:"open.v1"`
	PersonIdentifierWithinTrawlerArchive                   string                                      `protobuf:"bytes,1,opt,name=person_identifier_within_trawler_archive,json=personIdentifierWithinTrawlerArchive,proto3" json:"person_identifier_within_trawler_archive,omitempty"`
	PersonDisplayName                                      string                                      `protobuf:"bytes,2,opt,name=person_display_name,json=personDisplayName,proto3" json:"person_display_name,omitempty"`
	PersonEmailAddresses                                   []string                                    `protobuf:"bytes,3,rep,name=person_email_addresses,json=personEmailAddresses,proto3" json:"person_email_addresses,omitempty"`
	PersonPhoneNumbers                                     []string                                    `protobuf:"bytes,4,rep,name=person_phone_numbers,json=personPhoneNumbers,proto3" json:"person_phone_numbers,omitempty"`
	PersonAccountIdentifiersByServiceName                  map[string]*TrawlerPersonAccountIdentifiers `protobuf:"bytes,5,rep,name=person_account_identifiers_by_service_name,json=personAccountIdentifiersByServiceName,proto3" json:"person_account_identifiers_by_service_name,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LatestArchiveRecordTimeInvolvingPersonInTrawlerArchive *timestamppb.Timestamp                      `protobuf:"bytes,6,opt,name=latest_archive_record_time_involving_person_in_trawler_archive,json=latestArchiveRecordTimeInvolvingPersonInTrawlerArchive,proto3" json:"latest_archive_record_time_involving_person_in_trawler_archive,omitempty"`
	MessageCountInvolvingPersonInTrawlerArchive            uint64                                      `protobuf:"varint,7,opt,name=message_count_involving_person_in_trawler_archive,json=messageCountInvolvingPersonInTrawlerArchive,proto3" json:"message_count_involving_person_in_trawler_archive,omitempty"`
	unknownFields                                          protoimpl.UnknownFields
	sizeCache                                              protoimpl.SizeCache
}

func (x *TrawlerPersonIdentity) Reset() {
	*x = TrawlerPersonIdentity{}
	mi := &file_trawl_person_v1_person_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerPersonIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerPersonIdentity) ProtoMessage() {}

func (x *TrawlerPersonIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_person_v1_person_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerPersonIdentity.ProtoReflect.Descriptor instead.
func (*TrawlerPersonIdentity) Descriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{5}
}

func (x *TrawlerPersonIdentity) GetPersonIdentifierWithinTrawlerArchive() string {
	if x != nil {
		return x.PersonIdentifierWithinTrawlerArchive
	}
	return ""
}

func (x *TrawlerPersonIdentity) GetPersonDisplayName() string {
	if x != nil {
		return x.PersonDisplayName
	}
	return ""
}

func (x *TrawlerPersonIdentity) GetPersonEmailAddresses() []string {
	if x != nil {
		return x.PersonEmailAddresses
	}
	return nil
}

func (x *TrawlerPersonIdentity) GetPersonPhoneNumbers() []string {
	if x != nil {
		return x.PersonPhoneNumbers
	}
	return nil
}

func (x *TrawlerPersonIdentity) GetPersonAccountIdentifiersByServiceName() map[string]*TrawlerPersonAccountIdentifiers {
	if x != nil {
		return x.PersonAccountIdentifiersByServiceName
	}
	return nil
}

func (x *TrawlerPersonIdentity) GetLatestArchiveRecordTimeInvolvingPersonInTrawlerArchive() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestArchiveRecordTimeInvolvingPersonInTrawlerArchive
	}
	return nil
}

func (x *TrawlerPersonIdentity) GetMessageCountInvolvingPersonInTrawlerArchive() uint64 {
	if x != nil {
		return x.MessageCountInvolvingPersonInTrawlerArchive
	}
	return 0
}

type TrawlerPersonAccountIdentifiers struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	PersonAccountIdentifiers []string               `protobuf:"bytes,1,rep,name=person_account_identifiers,json=personAccountIdentifiers,proto3" json:"person_account_identifiers,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TrawlerPersonAccountIdentifiers) Reset() {
	*x = TrawlerPersonAccountIdentifiers{}
	mi := &file_trawl_person_v1_person_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerPersonAccountIdentifiers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerPersonAccountIdentifiers) ProtoMessage() {}

func (x *TrawlerPersonAccountIdentifiers) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_person_v1_person_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerPersonAccountIdentifiers.ProtoReflect.Descriptor instead.
func (*TrawlerPersonAccountIdentifiers) Descriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{6}
}

func (x *TrawlerPersonAccountIdentifiers) GetPersonAccountIdentifiers() []string {
	if x != nil {
		return x.PersonAccountIdentifiers
	}
	return nil
}

type TrawlerPersonMatchCandidate struct {
	state                                                                protoimpl.MessageState         `protogen:"open.v1"`
	PersonDisplayName                                                    string                         `protobuf:"bytes,1,opt,name=person_display_name,json=personDisplayName,proto3" json:"person_display_name,omitempty"`
	AlternativePersonDisplayNames                                        []string                       `protobuf:"bytes,2,rep,name=alternative_person_display_names,json=alternativePersonDisplayNames,proto3" json:"alternative_person_display_names,omitempty"`
	PersonNameOrHumanReadableContactValueThatMatchedQuery                string                         `protobuf:"bytes,3,opt,name=person_name_or_human_readable_contact_value_that_matched_query,json=personNameOrHumanReadableContactValueThatMatchedQuery,proto3" json:"person_name_or_human_readable_contact_value_that_matched_query,omitempty"`
	PersonMatchFactsFromTrawlers                                         []*PersonMatchFactsFromTrawler `protobuf:"bytes,4,rep,name=person_match_facts_from_trawlers,json=personMatchFactsFromTrawlers,proto3" json:"person_match_facts_from_trawlers,omitempty"`
	LatestMatchingArchiveRecordTime                                      *timestamppb.Timestamp         `protobuf:"bytes,5,opt,name=latest_matching_archive_record_time,json=latestMatchingArchiveRecordTime,proto3" json:"latest_matching_archive_record_time,omitempty"`
	MessageCountInvolvingPerson                                          uint64                         `protobuf:"varint,6,opt,name=message_count_involving_person,json=messageCountInvolvingPerson,proto3" json:"message_count_involving_person,omitempty"`
	CanonicalPersonRecordReferenceForGloballyRoutableTrawlLinkAssignment string                         `protobuf:"bytes,7,opt,name=canonical_person_record_reference_for_globally_routable_trawl_link_assignment,json=canonicalPersonRecordReferenceForGloballyRoutableTrawlLinkAssignment,proto3" json:"canonical_person_record_reference_for_globally_routable_trawl_link_assignment,omitempty"`
	GloballyRoutableTrawlLinkForPerson                                   string                         `protobuf:"bytes,8,opt,name=globally_routable_trawl_link_for_person,json=globallyRoutableTrawlLinkForPerson,proto3" json:"globally_routable_trawl_link_for_person,omitempty"`
	unknownFields                                                        protoimpl.UnknownFields
	sizeCache                                                            protoimpl.SizeCache
}

func (x *TrawlerPersonMatchCandidate) Reset() {
	*x = TrawlerPersonMatchCandidate{}
	mi := &file_trawl_person_v1_person_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerPersonMatchCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerPersonMatchCandidate) ProtoMessage() {}

func (x *TrawlerPersonMatchCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_person_v1_person_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerPersonMatchCandidate.ProtoReflect.Descriptor instead.
func (*TrawlerPersonMatchCandidate) Descriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{7}
}

func (x *TrawlerPersonMatchCandidate) GetPersonDisplayName() string {
	if x != nil {
		return x.PersonDisplayName
	}
	return ""
}

func (x *TrawlerPersonMatchCandidate) GetAlternativePersonDisplayNames() []string {
	if x != nil {
		return x.AlternativePersonDisplayNames
	}
	return nil
}

func (x *TrawlerPersonMatchCandidate) GetPersonNameOrHumanReadableContactValueThatMatchedQuery() string {
	if x != nil {
		return x.PersonNameOrHumanReadableContactValueThatMatchedQuery
	}
	return ""
}

func (x *TrawlerPersonMatchCandidate) GetPersonMatchFactsFromTrawlers() []*PersonMatchFactsFromTrawler {
	if x != nil {
		return x.PersonMatchFactsFromTrawlers
	}
	return nil
}

func (x *TrawlerPersonMatchCandidate) GetLatestMatchingArchiveRecordTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestMatchingArchiveRecordTime
	}
	return nil
}

func (x *TrawlerPersonMatchCandidate) GetMessageCountInvolvingPerson() uint64 {
	if x != nil {
		return x.MessageCountInvolvingPerson
	}
	return 0
}

func (x *TrawlerPersonMatchCandidate) GetCanonicalPersonRecordReferenceForGloballyRoutableTrawlLinkAssignment() string {
	if x != nil {
		return x.CanonicalPersonRecordReferenceForGloballyRoutableTrawlLinkAssignment
	}
	return ""
}

func (x *TrawlerPersonMatchCandidate) GetGloballyRoutableTrawlLinkForPerson() string {
	if x != nil {
		return x.GloballyRoutableTrawlLinkForPerson
	}
	return ""
}

type PersonMatchFactsFromTrawler struct {
	state                                                protoimpl.MessageState `protogen:"open.v1"`
	RegisteredTrawlerManifestIdentity                    string                 `protobuf:"bytes,1,opt,name=registered_trawler_manifest_identity,json=registeredTrawlerManifestIdentity,proto3" json:"registered_trawler_manifest_identity,omitempty"`
	ExactPersonFilterIdentifiersObservedByTrawlerArchive []string               `protobuf:"bytes,2,rep,name=exact_person_filter_identifiers_observed_by_trawler_archive,json=exactPersonFilterIdentifiersObservedByTrawlerArchive,proto3" json:"exact_person_filter_identifiers_observed_by_trawler_archive,omitempty"`
	PersonDisplayNamesObservedByTrawlerArchive           []string               `protobuf:"bytes,3,rep,name=person_display_names_observed_by_trawler_archive,json=personDisplayNamesObservedByTrawlerArchive,proto3" json:"person_display_names_observed_by_trawler_archive,omitempty"`
	unknownFields                                        protoimpl.UnknownFields
	sizeCache                                            protoimpl.SizeCache
}

func (x *PersonMatchFactsFromTrawler) Reset() {
	*x = PersonMatchFactsFromTrawler{}
	mi := &file_trawl_person_v1_person_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonMatchFactsFromTrawler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonMatchFactsFromTrawler) ProtoMessage() {}

func (x *PersonMatchFactsFromTrawler) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_person_v1_person_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonMatchFactsFromTrawler.ProtoReflect.Descriptor instead.
func (*PersonMatchFactsFromTrawler) Descriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{8}
}

func (x *PersonMatchFactsFromTrawler) GetRegisteredTrawlerManifestIdentity() string {
	if x != nil {
		return x.RegisteredTrawlerManifestIdentity
	}
	return ""
}

func (x *PersonMatchFactsFromTrawler) GetExactPersonFilterIdentifiersObservedByTrawlerArchive() []string {
	if x != nil {
		return x.ExactPersonFilterIdentifiersObservedByTrawlerArchive
	}
	return nil
}

func (x *PersonMatchFactsFromTrawler) GetPersonDisplayNamesObservedByTrawlerArchive() []string {
	if x != nil {
		return x.PersonDisplayNamesObservedByTrawlerArchive
	}
	return nil
}

type TrawlerPersonMatchResponse struct {
	state                 protoimpl.MessageState         `protogen:"open.v1"`
	PersonMatchCandidates []*TrawlerPersonMatchCandidate `protobuf:"bytes,1,rep,name=person_match_candidates,json=personMatchCandidates,proto3" json:"person_match_candidates,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TrawlerPersonMatchResponse) Reset() {
	*x = TrawlerPersonMatchResponse{}
	mi := &file_trawl_person_v1_person_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerPersonMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerPersonMatchResponse) ProtoMessage() {}

func (x *TrawlerPersonMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_person_v1_person_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerPersonMatchResponse.ProtoReflect.Descriptor instead.
func (*TrawlerPersonMatchResponse) Descriptor() ([]byte, []int) {
	return file_trawl_person_v1_person_proto_rawDescGZIP(), []int{9}
}

func (x *TrawlerPersonMatchResponse) GetPersonMatchCandidates() []*TrawlerPersonMatchCandidate {
	if x != nil {
		return x.PersonMatchCandidates
	}
	return nil
}

var File_trawl_person_v1_person_proto protoreflect.FileDescriptor

const file_trawl_person_v1_person_proto_rawDesc = "" +
	"\n" +
	"\x1ctrawl/person/v1/person.proto\x12\x0ftrawl.person.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x01\n" +
	"\x1cPersonRelatedToArchiveRecord\x12.\n" +
	"\x13person_display_name\x18\x01 \x01(\tR\x11personDisplayName\x12l\n" +
	"\x1dperson_role_in_archive_record\x18\x02 \x01(\x0e2*.trawl.person.v1.PersonRoleInArchiveRecordR\x19personRoleInArchiveRecord\"\x89\x02\n" +
	"\x13PersonContactMethod\x12e\n" +
	"\x1aperson_contact_method_kind\x18\x01 \x01(\x0e2(.trawl.person.v1.PersonContactMethodKindR\x17personContactMethodKind\x12=\n" +
	"\x1bperson_contact_method_label\x18\x02 \x01(\tR\x18personContactMethodLabel\x12L\n" +
	"#person_contact_method_display_value\x18\x03 \x01(\tR\x1fpersonContactMethodDisplayValue\"\x83\x04\n" +
	"\fPersonRecord\x12\x9b\x01\n" +
	"Mcanonical_person_record_reference_for_globally_routable_trawl_link_assignment\x18\x01 \x01(\tRDcanonicalPersonRecordReferenceForGloballyRoutableTrawlLinkAssignment\x12.\n" +
	"\x13person_display_name\x18\x02 \x01(\tR\x11personDisplayName\x12G\n" +
	" alternative_person_display_names\x18\x03 \x03(\tR\x1dalternativePersonDisplayNames\x12y\n" +
	"'person_contact_methods_in_display_order\x18\x04 \x03(\v2$.trawl.person.v1.PersonContactMethodR\"personContactMethodsInDisplayOrder\x12a\n" +
	".person_fact_contributing_trawler_display_names\x18\x05 \x03(\tR)personFactContributingTrawlerDisplayNames\"\xcf\x02\n" +
	"\x12PersonListResponse\x12c\n" +
	"\x1fperson_records_in_display_order\x18\x01 \x03(\v2\x1d.trawl.person.v1.PersonRecordR\x1bpersonRecordsInDisplayOrder\x12=\n" +
	"\x1btotal_matching_person_count\x18\x02 \x01(\x04R\x18totalMatchingPersonCount\x12X\n" +
	"*total_matching_person_count_is_lower_bound\x18\x03 \x01(\bR$totalMatchingPersonCountIsLowerBound\x12;\n" +
	"\x1amore_matching_people_exist\x18\x04 \x01(\bR\x17moreMatchingPeopleExist\"{\n" +
	"\x15TrawlerPeopleSnapshot\x12b\n" +
	"\x19trawler_person_identities\x18\x01 \x03(\v2&.trawl.person.v1.TrawlerPersonIdentityR\x17trawlerPersonIdentities\"\xc8\x06\n" +
	"\x15TrawlerPersonIdentity\x12V\n" +
	"(person_identifier_within_trawler_archive\x18\x01 \x01(\tR$personIdentifierWithinTrawlerArchive\x12.\n" +
	"\x13person_display_name\x18\x02 \x01(\tR\x11personDisplayName\x124\n" +
	"\x16person_email_addresses\x18\x03 \x03(\tR\x14personEmailAddresses\x120\n" +
	"\x14person_phone_numbers\x18\x04 \x03(\tR\x12personPhoneNumbers\x12\xac\x01\n" +
	"*person_account_identifiers_by_service_name\x18\x05 \x03(\v2Q.trawl.person.v1.TrawlerPersonIdentity.PersonAccountIdentifiersByServiceNameEntryR%personAccountIdentifiersByServiceName\x12\x9a\x01\n" +
	">latest_archive_record_time_involving_person_in_trawler_archive\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR6latestArchiveRecordTimeInvolvingPersonInTrawlerArchive\x12f\n" +
	"1message_count_involving_person_in_trawler_archive\x18\a \x01(\x04R+messageCountInvolvingPersonInTrawlerArchive\x1a\x8a\x01\n" +
	"*PersonAccountIdentifiersByServiceNameEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12F\n" +
	"\x05value\x18\x02 \x01(\v20.trawl.person.v1.TrawlerPersonAccountIdentifiersR\x05value:\x028\x01\"_\n" +
	"\x1fTrawlerPersonAccountIdentifiers\x12<\n" +
	"\x1aperson_account_identifiers\x18\x01 \x03(\tR\x18personAccountIdentifiers\"\xad\x06\n" +
	"\x1bTrawlerPersonMatchCandidate\x12.\n" +
	"\x13person_display_name\x18\x01 \x01(\tR\x11personDisplayName\x12G\n" +
	" alternative_person_display_names\x18\x02 \x03(\tR\x1dalternativePersonDisplayNames\x12}\n" +
	">person_name_or_human_readable_contact_value_that_matched_query\x18\x03 \x01(\tR5personNameOrHumanReadableContactValueThatMatchedQuery\x12t\n" +
	" person_match_facts_from_trawlers\x18\x04 \x03(\v2,.trawl.person.v1.PersonMatchFactsFromTrawlerR\x1cpersonMatchFactsFromTrawlers\x12h\n" +
	"#latest_matching_archive_record_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x1flatestMatchingArchiveRecordTime\x12C\n" +
	"\x1emessage_count_involving_person\x18\x06 \x01(\x04R\x1bmessageCountInvolvingPerson\x12\x9b\x01\n" +
	"Mcanonical_person_record_reference_for_globally_routable_trawl_link_assignment\x18\a \x01(\tRDcanonicalPersonRecordReferenceForGloballyRoutableTrawlLinkAssignment\x12S\n" +
	"'globally_routable_trawl_link_for_person\x18\b \x01(\tR\"globallyRoutableTrawlLinkForPerson\"\xcf\x02\n" +
	"\x1bPersonMatchFactsFromTrawler\x12O\n" +
	"$registered_trawler_manifest_identity\x18\x01 \x01(\tR!registeredTrawlerManifestIdentity\x12y\n" +
	";exact_person_filter_identifiers_observed_by_trawler_archive\x18\x02 \x03(\tR4exactPersonFilterIdentifiersObservedByTrawlerArchive\x12d\n" +
	"0person_display_names_observed_by_trawler_archive\x18\x03 \x03(\tR*personDisplayNamesObservedByTrawlerArchive\"\x82\x01\n" +
	"\x1aTrawlerPersonMatchResponse\x12d\n" +
	"\x17person_match_candidates\x18\x01 \x03(\v2,.trawl.person.v1.TrawlerPersonMatchCandidateR\x15personMatchCandidates*\x82\x02\n" +
	"\x17PersonContactMethodKind\x12*\n" +
	"&PERSON_CONTACT_METHOD_KIND_UNSPECIFIED\x10\x00\x12,\n" +
	"(PERSON_CONTACT_METHOD_KIND_EMAIL_ADDRESS\x10\x01\x12+\n" +
	"'PERSON_CONTACT_METHOD_KIND_PHONE_NUMBER\x10\x02\x12-\n" +
	")PERSON_CONTACT_METHOD_KIND_POSTAL_ADDRESS\x10\x03\x121\n" +
	"-PERSON_CONTACT_METHOD_KIND_ACCOUNT_IDENTIFIER\x10\x04*\xd3\x02\n" +
	"\x19PersonRoleInArchiveRecord\x12-\n" +
	")PERSON_ROLE_IN_ARCHIVE_RECORD_UNSPECIFIED\x10\x00\x12(\n" +
	"$PERSON_ROLE_IN_ARCHIVE_RECORD_SENDER\x10\x01\x12+\n" +
	"'PERSON_ROLE_IN_ARCHIVE_RECORD_RECIPIENT\x10\x02\x12(\n" +
	"$PERSON_ROLE_IN_ARCHIVE_RECORD_AUTHOR\x10\x03\x12+\n" +
	"'PERSON_ROLE_IN_ARCHIVE_RECORD_ORGANIZER\x10\x04\x12*\n" +
	"&PERSON_ROLE_IN_ARCHIVE_RECORD_ATTENDEE\x10\x05\x12-\n" +
	")PERSON_ROLE_IN_ARCHIVE_RECORD_PARTICIPANT\x10\x06BHZFgithub.com/opentrawl/opentrawl/trawlkit/proto/trawl/person/v1;personv1b\x06proto3"

var (
	file_trawl_person_v1_person_proto_rawDescOnce sync.Once
	file_trawl_person_v1_person_proto_rawDescData []byte
)

func file_trawl_person_v1_person_proto_rawDescGZIP() []byte {
	file_trawl_person_v1_person_proto_rawDescOnce.Do(func() {
		file_trawl_person_v1_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trawl_person_v1_person_proto_rawDesc), len(file_trawl_person_v1_person_proto_rawDesc)))
	})
	return file_trawl_person_v1_person_proto_rawDescData
}

var file_trawl_person_v1_person_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_trawl_person_v1_person_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_trawl_person_v1_person_proto_goTypes = []any{
	(PersonContactMethodKind)(0),            // 0: trawl.person.v1.PersonContactMethodKind
	(PersonRoleInArchiveRecord)(0),          // 1: trawl.person.v1.PersonRoleInArchiveRecord
	(*PersonRelatedToArchiveRecord)(nil),    // 2: trawl.person.v1.PersonRelatedToArchiveRecord
	(*PersonContactMethod)(nil),             // 3: trawl.person.v1.PersonContactMethod
	(*PersonRecord)(nil),                    // 4: trawl.person.v1.PersonRecord
	(*PersonListResponse)(nil),              // 5: trawl.person.v1.PersonListResponse
	(*TrawlerPeopleSnapshot)(nil),           // 6: trawl.person.v1.TrawlerPeopleSnapshot
	(*TrawlerPersonIdentity)(nil),           // 7: trawl.person.v1.TrawlerPersonIdentity
	(*TrawlerPersonAccountIdentifiers)(nil), // 8: trawl.person.v1.TrawlerPersonAccountIdentifiers
	(*TrawlerPersonMatchCandidate)(nil),     // 9: trawl.person.v1.TrawlerPersonMatchCandidate
	(*PersonMatchFactsFromTrawler)(nil),     // 10: trawl.person.v1.PersonMatchFactsFromTrawler
	(*TrawlerPersonMatchResponse)(nil),      // 11: trawl.person.v1.TrawlerPersonMatchResponse
	nil,                                     // 12: trawl.person.v1.TrawlerPersonIdentity.PersonAccountIdentifiersByServiceNameEntry
	(*timestamppb.Timestamp)(nil),           // 13: google.protobuf.Timestamp
}
var file_trawl_person_v1_person_proto_depIdxs = []int32{
	1,  // 0: trawl.person.v1.PersonRelatedToArchiveRecord.person_role_in_archive_record:type_name -> trawl.person.v1.PersonRoleInArchiveRecord
	0,  // 1: trawl.person.v1.PersonContactMethod.person_contact_method_kind:type_name -> trawl.person.v1.PersonContactMethodKind
	3,  // 2: trawl.person.v1.PersonRecord.person_contact_methods_in_display_order:type_name -> trawl.person.v1.PersonContactMethod
	4,  // 3: trawl.person.v1.PersonListResponse.person_records_in_display_order:type_name -> trawl.person.v1.PersonRecord
	7,  // 4: trawl.person.v1.TrawlerPeopleSnapshot.trawler_person_identities:type_name -> trawl.person.v1.TrawlerPersonIdentity
	12, // 5: trawl.person.v1.TrawlerPersonIdentity.person_account_identifiers_by_service_name:type_name -> trawl.person.v1.TrawlerPersonIdentity.PersonAccountIdentifiersByServiceNameEntry
	13, // 6: trawl.person.v1.TrawlerPersonIdentity.latest_archive_record_time_involving_person_in_trawler_archive:type_name -> google.protobuf.Timestamp
	10, // 7: trawl.person.v1.TrawlerPersonMatchCandidate.person_match_facts_from_trawlers:type_name -> trawl.person.v1.PersonMatchFactsFromTrawler
	13, // 8: trawl.person.v1.TrawlerPersonMatchCandidate.latest_matching_archive_record_time:type_name -> google.protobuf.Timestamp
	9,  // 9: trawl.person.v1.TrawlerPersonMatchResponse.person_match_candidates:type_name -> trawl.person.v1.TrawlerPersonMatchCandidate
	8,  // 10: trawl.person.v1.TrawlerPersonIdentity.PersonAccountIdentifiersByServiceNameEntry.value:type_name -> trawl.person.v1.TrawlerPersonAccountIdentifiers
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_trawl_person_v1_person_proto_init() }
func file_trawl_person_v1_person_proto_init() {
	if File_trawl_person_v1_person_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trawl_person_v1_person_proto_rawDesc), len(file_trawl_person_v1_person_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trawl_person_v1_person_proto_goTypes,
		DependencyIndexes: file_trawl_person_v1_person_proto_depIdxs,
		EnumInfos:         file_trawl_person_v1_person_proto_enumTypes,
		MessageInfos:      file_trawl_person_v1_person_proto_msgTypes,
	}.Build()
	File_trawl_person_v1_person_proto = out.File
	file_trawl_person_v1_person_proto_goTypes = nil
	file_trawl_person_v1_person_proto_depIdxs = nil
}
