// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package storedb

import (
	"context"
	"database/sql"
)

const countChats = `-- name: CountChats :one
select count(*) from chats
`

func (q *Queries) CountChats(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChats)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContacts = `-- name: CountContacts :one
select count(*) from contacts
`

func (q *Queries) CountContacts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroups = `-- name: CountGroups :one
select count(*) from groups
`

func (q *Queries) CountGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMediaMessages = `-- name: CountMediaMessages :one
select count(*) from messages where media_type <> '' or media_path <> '' or media_url <> ''
`

func (q *Queries) CountMediaMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessages = `-- name: CountMessages :one
select count(*) from messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countParticipants = `-- name: CountParticipants :one
select count(*) from group_participants
`

func (q *Queries) CountParticipants(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countParticipants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadChats = `-- name: CountUnreadChats :one
select count(*) from chats where unread_count > 0
`

func (q *Queries) CountUnreadChats(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadChats)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadMessages = `-- name: CountUnreadMessages :one
select cast(coalesce(sum(unread_count), 0) as integer) as unread_messages from chats
`

func (q *Queries) CountUnreadMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadMessages)
	var unread_messages int64
	err := row.Scan(&unread_messages)
	return unread_messages, err
}

const deleteChats = `-- name: DeleteChats :exec
delete from chats
`

func (q *Queries) DeleteChats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteChats)
	return err
}

const deleteContacts = `-- name: DeleteContacts :exec
delete from contacts
`

func (q *Queries) DeleteContacts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteContacts)
	return err
}

const deleteGroupParticipants = `-- name: DeleteGroupParticipants :exec
delete from group_participants
`

func (q *Queries) DeleteGroupParticipants(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteGroupParticipants)
	return err
}

const deleteGroups = `-- name: DeleteGroups :exec
delete from groups
`

func (q *Queries) DeleteGroups(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteGroups)
	return err
}

const deleteMessages = `-- name: DeleteMessages :exec
delete from messages
`

func (q *Queries) DeleteMessages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMessages)
	return err
}

const deleteMessagesFTS = `-- name: DeleteMessagesFTS :exec
delete from messages_fts
`

func (q *Queries) DeleteMessagesFTS(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesFTS)
	return err
}

const deleteSyncState = `-- name: DeleteSyncState :exec
delete from sync_state
`

func (q *Queries) DeleteSyncState(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSyncState)
	return err
}

const exportChats = `-- name: ExportChats :many
select
	jid,
	kind,
	coalesce(name, '') as name,
	coalesce(last_message_at, 0) as last_message_at,
	unread_count,
	archived,
	removed,
	hidden,
	raw_session_type
from chats
order by jid
`

type ExportChatsRow struct {
	Jid            string
	Kind           string
	Name           string
	LastMessageAt  int64
	UnreadCount    int64
	Archived       int64
	Removed        int64
	Hidden         int64
	RawSessionType int64
}

func (q *Queries) ExportChats(ctx context.Context) ([]ExportChatsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportChatsRow
	for rows.Next() {
		var i ExportChatsRow
		if err := rows.Scan(
			&i.Jid,
			&i.Kind,
			&i.Name,
			&i.LastMessageAt,
			&i.UnreadCount,
			&i.Archived,
			&i.Removed,
			&i.Hidden,
			&i.RawSessionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportContacts = `-- name: ExportContacts :many
select
	jid,
	coalesce(phone, '') as phone,
	coalesce(full_name, '') as full_name,
	coalesce(first_name, '') as first_name,
	coalesce(last_name, '') as last_name,
	coalesce(business_name, '') as business_name,
	coalesce(username, '') as username,
	coalesce(lid, '') as lid,
	coalesce(about_text, '') as about_text,
	coalesce(updated_at, 0) as updated_at
from contacts
order by jid
`

type ExportContactsRow struct {
	Jid          string
	Phone        string
	FullName     string
	FirstName    string
	LastName     string
	BusinessName string
	Username     string
	Lid          string
	AboutText    string
	UpdatedAt    int64
}

func (q *Queries) ExportContacts(ctx context.Context) ([]ExportContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportContactsRow
	for rows.Next() {
		var i ExportContactsRow
		if err := rows.Scan(
			&i.Jid,
			&i.Phone,
			&i.FullName,
			&i.FirstName,
			&i.LastName,
			&i.BusinessName,
			&i.Username,
			&i.Lid,
			&i.AboutText,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportGroups = `-- name: ExportGroups :many
select
	jid,
	coalesce(name, '') as name,
	coalesce(owner_jid, '') as owner_jid,
	coalesce(created_at, 0) as created_at
from groups
order by jid
`

type ExportGroupsRow struct {
	Jid       string
	Name      string
	OwnerJid  string
	CreatedAt int64
}

func (q *Queries) ExportGroups(ctx context.Context) ([]ExportGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportGroupsRow
	for rows.Next() {
		var i ExportGroupsRow
		if err := rows.Scan(
			&i.Jid,
			&i.Name,
			&i.OwnerJid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportParticipants = `-- name: ExportParticipants :many
select
	group_jid,
	user_jid,
	coalesce(contact_name, '') as contact_name,
	coalesce(first_name, '') as first_name,
	is_admin,
	is_active
from group_participants
order by group_jid, user_jid
`

type ExportParticipantsRow struct {
	GroupJid    string
	UserJid     string
	ContactName string
	FirstName   string
	IsAdmin     int64
	IsActive    int64
}

func (q *Queries) ExportParticipants(ctx context.Context) ([]ExportParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportParticipants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportParticipantsRow
	for rows.Next() {
		var i ExportParticipantsRow
		if err := rows.Scan(
			&i.GroupJid,
			&i.UserJid,
			&i.ContactName,
			&i.FirstName,
			&i.IsAdmin,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageTimeBounds = `-- name: GetMessageTimeBounds :one
select
	cast(coalesce(min(case when ts > 0 and ts <= 253402300799 then ts end), 0) as integer) as oldest_ts,
	cast(coalesce(max(case when ts > 0 and ts <= 253402300799 then ts end), 0) as integer) as newest_ts
from messages
`

type GetMessageTimeBoundsRow struct {
	OldestTs int64
	NewestTs int64
}

func (q *Queries) GetMessageTimeBounds(ctx context.Context) (GetMessageTimeBoundsRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageTimeBounds)
	var i GetMessageTimeBoundsRow
	err := row.Scan(&i.OldestTs, &i.NewestTs)
	return i, err
}

const getSyncState = `-- name: GetSyncState :one
select value from sync_state where key = ?1
`

func (q *Queries) GetSyncState(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSyncState, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertChat = `-- name: InsertChat :exec
insert into chats(jid, kind, name, last_message_at, unread_count, archived, removed, hidden, raw_session_type)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertChatParams struct {
	Jid            string
	Kind           string
	Name           sql.NullString
	LastMessageAt  sql.NullInt64
	UnreadCount    int64
	Archived       int64
	Removed        int64
	Hidden         int64
	RawSessionType int64
}

func (q *Queries) InsertChat(ctx context.Context, arg InsertChatParams) error {
	_, err := q.db.ExecContext(ctx, insertChat,
		arg.Jid,
		arg.Kind,
		arg.Name,
		arg.LastMessageAt,
		arg.UnreadCount,
		arg.Archived,
		arg.Removed,
		arg.Hidden,
		arg.RawSessionType,
	)
	return err
}

const insertContact = `-- name: InsertContact :exec
insert into contacts(jid, phone, full_name, first_name, last_name, business_name, username, lid, about_text, updated_at)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
`

type InsertContactParams struct {
	Jid          string
	Phone        sql.NullString
	FullName     sql.NullString
	FirstName    sql.NullString
	LastName     sql.NullString
	BusinessName sql.NullString
	Username     sql.NullString
	Lid          sql.NullString
	AboutText    sql.NullString
	UpdatedAt    sql.NullInt64
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) error {
	_, err := q.db.ExecContext(ctx, insertContact,
		arg.Jid,
		arg.Phone,
		arg.FullName,
		arg.FirstName,
		arg.LastName,
		arg.BusinessName,
		arg.Username,
		arg.Lid,
		arg.AboutText,
		arg.UpdatedAt,
	)
	return err
}

const insertGroup = `-- name: InsertGroup :exec
insert into groups(jid, name, owner_jid, created_at)
values(?1, ?2, ?3, ?4)
`

type InsertGroupParams struct {
	Jid       string
	Name      sql.NullString
	OwnerJid  sql.NullString
	CreatedAt sql.NullInt64
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertGroup,
		arg.Jid,
		arg.Name,
		arg.OwnerJid,
		arg.CreatedAt,
	)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
insert into messages(source_pk, chat_jid, chat_name, msg_id, sender_jid, sender_name, ts, from_me, text, raw_type, message_type, media_type, media_title, media_path, media_url, media_size, starred)
values(?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17)
`

type InsertMessageParams struct {
	SourcePk    int64
	ChatJid     string
	ChatName    sql.NullString
	MsgID       string
	SenderJid   sql.NullString
	SenderName  sql.NullString
	Ts          int64
	FromMe      int64
	Text        sql.NullString
	RawType     int64
	MessageType sql.NullString
	MediaType   sql.NullString
	MediaTitle  sql.NullString
	MediaPath   sql.NullString
	MediaUrl    sql.NullString
	MediaSize   sql.NullInt64
	Starred     int64
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.SourcePk,
		arg.ChatJid,
		arg.ChatName,
		arg.MsgID,
		arg.SenderJid,
		arg.SenderName,
		arg.Ts,
		arg.FromMe,
		arg.Text,
		arg.RawType,
		arg.MessageType,
		arg.MediaType,
		arg.MediaTitle,
		arg.MediaPath,
		arg.MediaUrl,
		arg.MediaSize,
		arg.Starred,
	)
	return err
}

const insertMessageFTS = `-- name: InsertMessageFTS :exec
insert into messages_fts(rowid, text, chat, sender, media)
values((select rowid from messages where source_pk = ?1), ?2, ?3, ?4, ?5)
`

type InsertMessageFTSParams struct {
	SourcePk int64
	Text     sql.NullString
	Chat     sql.NullString
	Sender   sql.NullString
	Media    sql.NullString
}

func (q *Queries) InsertMessageFTS(ctx context.Context, arg InsertMessageFTSParams) error {
	_, err := q.db.ExecContext(ctx, insertMessageFTS,
		arg.SourcePk,
		arg.Text,
		arg.Chat,
		arg.Sender,
		arg.Media,
	)
	return err
}

const insertParticipant = `-- name: InsertParticipant :exec
insert into group_participants(group_jid, user_jid, contact_name, first_name, is_admin, is_active)
values(?1, ?2, ?3, ?4, ?5, ?6)
`

type InsertParticipantParams struct {
	GroupJid    string
	UserJid     string
	ContactName sql.NullString
	FirstName   sql.NullString
	IsAdmin     int64
	IsActive    int64
}

func (q *Queries) InsertParticipant(ctx context.Context, arg InsertParticipantParams) error {
	_, err := q.db.ExecContext(ctx, insertParticipant,
		arg.GroupJid,
		arg.UserJid,
		arg.ContactName,
		arg.FirstName,
		arg.IsAdmin,
		arg.IsActive,
	)
	return err
}

const insertSyncState = `-- name: InsertSyncState :exec
insert into sync_state(key, value, updated_at)
values(?1, ?2, ?3)
`

type InsertSyncStateParams struct {
	Key       string
	Value     string
	UpdatedAt int64
}

func (q *Queries) InsertSyncState(ctx context.Context, arg InsertSyncStateParams) error {
	_, err := q.db.ExecContext(ctx, insertSyncState, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}

const listChats = `-- name: ListChats :many
select
	c.jid,
	c.kind,
	coalesce(c.name, '') as name,
	coalesce(c.last_message_at, 0) as last_message_at,
	c.unread_count,
	c.archived,
	c.removed,
	c.hidden,
	c.raw_session_type,
	count(m.rowid) as message_count
from chats c
left join messages m on m.chat_jid = c.jid
group by c.jid, c.kind, c.name, c.last_message_at, c.unread_count, c.archived, c.removed, c.hidden, c.raw_session_type
order by case when c.last_message_at > 0 and c.last_message_at <= 253402300799 then c.last_message_at else 0 end desc
limit ?1
`

type ListChatsRow struct {
	Jid            string
	Kind           string
	Name           string
	LastMessageAt  int64
	UnreadCount    int64
	Archived       int64
	Removed        int64
	Hidden         int64
	RawSessionType int64
	MessageCount   int64
}

func (q *Queries) ListChats(ctx context.Context, limit int64) ([]ListChatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChats, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatsRow
	for rows.Next() {
		var i ListChatsRow
		if err := rows.Scan(
			&i.Jid,
			&i.Kind,
			&i.Name,
			&i.LastMessageAt,
			&i.UnreadCount,
			&i.Archived,
			&i.Removed,
			&i.Hidden,
			&i.RawSessionType,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadChats = `-- name: ListUnreadChats :many
select
	c.jid,
	c.kind,
	coalesce(c.name, '') as name,
	coalesce(c.last_message_at, 0) as last_message_at,
	c.unread_count,
	c.archived,
	c.removed,
	c.hidden,
	c.raw_session_type,
	count(m.rowid) as message_count
from chats c
left join messages m on m.chat_jid = c.jid
where c.unread_count > 0
group by c.jid, c.kind, c.name, c.last_message_at, c.unread_count, c.archived, c.removed, c.hidden, c.raw_session_type
order by case when c.last_message_at > 0 and c.last_message_at <= 253402300799 then c.last_message_at else 0 end desc
limit ?1
`

type ListUnreadChatsRow struct {
	Jid            string
	Kind           string
	Name           string
	LastMessageAt  int64
	UnreadCount    int64
	Archived       int64
	Removed        int64
	Hidden         int64
	RawSessionType int64
	MessageCount   int64
}

func (q *Queries) ListUnreadChats(ctx context.Context, limit int64) ([]ListUnreadChatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadChats, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnreadChatsRow
	for rows.Next() {
		var i ListUnreadChatsRow
		if err := rows.Scan(
			&i.Jid,
			&i.Kind,
			&i.Name,
			&i.LastMessageAt,
			&i.UnreadCount,
			&i.Archived,
			&i.Removed,
			&i.Hidden,
			&i.RawSessionType,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
