// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trawl/twitter/open/open.proto

package twitteropen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenedTwitterPostRecord struct {
	state                                  protoimpl.MessageState `protogen:"open.v1"`
	CanonicalTwitterPostRecordReference    string                 `protobuf:"bytes,1,opt,name=canonical_twitter_post_record_reference,json=canonicalTwitterPostRecordReference,proto3" json:"canonical_twitter_post_record_reference,omitempty"`
	OpenedTwitterPost                      *OpenedTwitterPost     `protobuf:"bytes,2,opt,name=opened_twitter_post,json=openedTwitterPost,proto3" json:"opened_twitter_post,omitempty"`
	AncestorTwitterPostsInOldestFirstOrder []*OpenedTwitterPost   `protobuf:"bytes,3,rep,name=ancestor_twitter_posts_in_oldest_first_order,json=ancestorTwitterPostsInOldestFirstOrder,proto3" json:"ancestor_twitter_posts_in_oldest_first_order,omitempty"`
	ReplyTwitterPostsInOldestFirstOrder    []*OpenedTwitterPost   `protobuf:"bytes,4,rep,name=reply_twitter_posts_in_oldest_first_order,json=replyTwitterPostsInOldestFirstOrder,proto3" json:"reply_twitter_posts_in_oldest_first_order,omitempty"`
	EarlierAncestorTwitterPostsAreOmitted  bool                   `protobuf:"varint,5,opt,name=earlier_ancestor_twitter_posts_are_omitted,json=earlierAncestorTwitterPostsAreOmitted,proto3" json:"earlier_ancestor_twitter_posts_are_omitted,omitempty"`
	LaterReplyTwitterPostsAreOmitted       bool                   `protobuf:"varint,6,opt,name=later_reply_twitter_posts_are_omitted,json=laterReplyTwitterPostsAreOmitted,proto3" json:"later_reply_twitter_posts_are_omitted,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *OpenedTwitterPostRecord) Reset() {
	*x = OpenedTwitterPostRecord{}
	mi := &file_trawl_twitter_open_open_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenedTwitterPostRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenedTwitterPostRecord) ProtoMessage() {}

func (x *OpenedTwitterPostRecord) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_twitter_open_open_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenedTwitterPostRecord.ProtoReflect.Descriptor instead.
func (*OpenedTwitterPostRecord) Descriptor() ([]byte, []int) {
	return file_trawl_twitter_open_open_proto_rawDescGZIP(), []int{0}
}

func (x *OpenedTwitterPostRecord) GetCanonicalTwitterPostRecordReference() string {
	if x != nil {
		return x.CanonicalTwitterPostRecordReference
	}
	return ""
}

func (x *OpenedTwitterPostRecord) GetOpenedTwitterPost() *OpenedTwitterPost {
	if x != nil {
		return x.OpenedTwitterPost
	}
	return nil
}

func (x *OpenedTwitterPostRecord) GetAncestorTwitterPostsInOldestFirstOrder() []*OpenedTwitterPost {
	if x != nil {
		return x.AncestorTwitterPostsInOldestFirstOrder
	}
	return nil
}

func (x *OpenedTwitterPostRecord) GetReplyTwitterPostsInOldestFirstOrder() []*OpenedTwitterPost {
	if x != nil {
		return x.ReplyTwitterPostsInOldestFirstOrder
	}
	return nil
}

func (x *OpenedTwitterPostRecord) GetEarlierAncestorTwitterPostsAreOmitted() bool {
	if x != nil {
		return x.EarlierAncestorTwitterPostsAreOmitted
	}
	return false
}

func (x *OpenedTwitterPostRecord) GetLaterReplyTwitterPostsAreOmitted() bool {
	if x != nil {
		return x.LaterReplyTwitterPostsAreOmitted
	}
	return false
}

type OpenedTwitterPost struct {
	state                                protoimpl.MessageState `protogen:"open.v1"`
	CanonicalTwitterPostRecordReference  string                 `protobuf:"bytes,1,opt,name=canonical_twitter_post_record_reference,json=canonicalTwitterPostRecordReference,proto3" json:"canonical_twitter_post_record_reference,omitempty"`
	TwitterPostCreatedRfc3339Time        *string                `protobuf:"bytes,2,opt,name=twitter_post_created_rfc3339_time,json=twitterPostCreatedRfc3339Time,proto3,oneof" json:"twitter_post_created_rfc3339_time,omitempty"`
	TwitterPostAuthorDisplayName         *string                `protobuf:"bytes,3,opt,name=twitter_post_author_display_name,json=twitterPostAuthorDisplayName,proto3,oneof" json:"twitter_post_author_display_name,omitempty"`
	TwitterPostText                      string                 `protobuf:"bytes,4,opt,name=twitter_post_text,json=twitterPostText,proto3" json:"twitter_post_text,omitempty"`
	RepliedToTwitterPostRecordReference  *string                `protobuf:"bytes,5,opt,name=replied_to_twitter_post_record_reference,json=repliedToTwitterPostRecordReference,proto3,oneof" json:"replied_to_twitter_post_record_reference,omitempty"`
	TwitterPostLikeCount                 *int64                 `protobuf:"varint,6,opt,name=twitter_post_like_count,json=twitterPostLikeCount,proto3,oneof" json:"twitter_post_like_count,omitempty"`
	TwitterPostRepostCount               *int64                 `protobuf:"varint,7,opt,name=twitter_post_repost_count,json=twitterPostRepostCount,proto3,oneof" json:"twitter_post_repost_count,omitempty"`
	TwitterPostReplyCount                *int64                 `protobuf:"varint,8,opt,name=twitter_post_reply_count,json=twitterPostReplyCount,proto3,oneof" json:"twitter_post_reply_count,omitempty"`
	TwitterPostCountsObservedRfc3339Time *string                `protobuf:"bytes,9,opt,name=twitter_post_counts_observed_rfc3339_time,json=twitterPostCountsObservedRfc3339Time,proto3,oneof" json:"twitter_post_counts_observed_rfc3339_time,omitempty"`
	TwitterPostAvailabilityNote          *string                `protobuf:"bytes,10,opt,name=twitter_post_availability_note,json=twitterPostAvailabilityNote,proto3,oneof" json:"twitter_post_availability_note,omitempty"`
	TwitterPostIsUnavailable             *bool                  `protobuf:"varint,11,opt,name=twitter_post_is_unavailable,json=twitterPostIsUnavailable,proto3,oneof" json:"twitter_post_is_unavailable,omitempty"`
	TwitterConversationIdentifier        *string                `protobuf:"bytes,12,opt,name=twitter_conversation_identifier,json=twitterConversationIdentifier,proto3,oneof" json:"twitter_conversation_identifier,omitempty"`
	QuotedTwitterPostIdentifier          *string                `protobuf:"bytes,13,opt,name=quoted_twitter_post_identifier,json=quotedTwitterPostIdentifier,proto3,oneof" json:"quoted_twitter_post_identifier,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *OpenedTwitterPost) Reset() {
	*x = OpenedTwitterPost{}
	mi := &file_trawl_twitter_open_open_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenedTwitterPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenedTwitterPost) ProtoMessage() {}

func (x *OpenedTwitterPost) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_twitter_open_open_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenedTwitterPost.ProtoReflect.Descriptor instead.
func (*OpenedTwitterPost) Descriptor() ([]byte, []int) {
	return file_trawl_twitter_open_open_proto_rawDescGZIP(), []int{1}
}

func (x *OpenedTwitterPost) GetCanonicalTwitterPostRecordReference() string {
	if x != nil {
		return x.CanonicalTwitterPostRecordReference
	}
	return ""
}

func (x *OpenedTwitterPost) GetTwitterPostCreatedRfc3339Time() string {
	if x != nil && x.TwitterPostCreatedRfc3339Time != nil {
		return *x.TwitterPostCreatedRfc3339Time
	}
	return ""
}

func (x *OpenedTwitterPost) GetTwitterPostAuthorDisplayName() string {
	if x != nil && x.TwitterPostAuthorDisplayName != nil {
		return *x.TwitterPostAuthorDisplayName
	}
	return ""
}

func (x *OpenedTwitterPost) GetTwitterPostText() string {
	if x != nil {
		return x.TwitterPostText
	}
	return ""
}

func (x *OpenedTwitterPost) GetRepliedToTwitterPostRecordReference() string {
	if x != nil && x.RepliedToTwitterPostRecordReference != nil {
		return *x.RepliedToTwitterPostRecordReference
	}
	return ""
}

func (x *OpenedTwitterPost) GetTwitterPostLikeCount() int64 {
	if x != nil && x.TwitterPostLikeCount != nil {
		return *x.TwitterPostLikeCount
	}
	return 0
}

func (x *OpenedTwitterPost) GetTwitterPostRepostCount() int64 {
	if x != nil && x.TwitterPostRepostCount != nil {
		return *x.TwitterPostRepostCount
	}
	return 0
}

func (x *OpenedTwitterPost) GetTwitterPostReplyCount() int64 {
	if x != nil && x.TwitterPostReplyCount != nil {
		return *x.TwitterPostReplyCount
	}
	return 0
}

func (x *OpenedTwitterPost) GetTwitterPostCountsObservedRfc3339Time() string {
	if x != nil && x.TwitterPostCountsObservedRfc3339Time != nil {
		return *x.TwitterPostCountsObservedRfc3339Time
	}
	return ""
}

func (x *OpenedTwitterPost) GetTwitterPostAvailabilityNote() string {
	if x != nil && x.TwitterPostAvailabilityNote != nil {
		return *x.TwitterPostAvailabilityNote
	}
	return ""
}

func (x *OpenedTwitterPost) GetTwitterPostIsUnavailable() bool {
	if x != nil && x.TwitterPostIsUnavailable != nil {
		return *x.TwitterPostIsUnavailable
	}
	return false
}

func (x *OpenedTwitterPost) GetTwitterConversationIdentifier() string {
	if x != nil && x.TwitterConversationIdentifier != nil {
		return *x.TwitterConversationIdentifier
	}
	return ""
}

func (x *OpenedTwitterPost) GetQuotedTwitterPostIdentifier() string {
	if x != nil && x.QuotedTwitterPostIdentifier != nil {
		return *x.QuotedTwitterPostIdentifier
	}
	return ""
}

var File_trawl_twitter_open_open_proto protoreflect.FileDescriptor

const file_trawl_twitter_open_open_proto_rawDesc = "" +
	"\n" +
	"\x1dtrawl/twitter/open/open.proto\x12\x12trawl.twitter.open\"\xf7\x04\n" +
	"\x17OpenedTwitterPostRecord\x12T\n" +
	"'canonical_twitter_post_record_reference\x18\x01 \x01(\tR#canonicalTwitterPostRecordReference\x12U\n" +
	"\x13opened_twitter_post\x18\x02 \x01(\v2%.trawl.twitter.open.OpenedTwitterPostR\x11openedTwitterPost\x12\x83\x01\n" +
	",ancestor_twitter_posts_in_oldest_first_order\x18\x03 \x03(\v2%.trawl.twitter.open.OpenedTwitterPostR&ancestorTwitterPostsInOldestFirstOrder\x12}\n" +
	")reply_twitter_posts_in_oldest_first_order\x18\x04 \x03(\v2%.trawl.twitter.open.OpenedTwitterPostR#replyTwitterPostsInOldestFirstOrder\x12Y\n" +
	"*earlier_ancestor_twitter_posts_are_omitted\x18\x05 \x01(\bR%earlierAncestorTwitterPostsAreOmitted\x12O\n" +
	"%later_reply_twitter_posts_are_omitted\x18\x06 \x01(\bR laterReplyTwitterPostsAreOmitted\"\xd1\n" +
	"\n" +
	"\x11OpenedTwitterPost\x12T\n" +
	"'canonical_twitter_post_record_reference\x18\x01 \x01(\tR#canonicalTwitterPostRecordReference\x12M\n" +
	"!twitter_post_created_rfc3339_time\x18\x02 \x01(\tH\x00R\x1dtwitterPostCreatedRfc3339Time\x88\x01\x01\x12K\n" +
	" twitter_post_author_display_name\x18\x03 \x01(\tH\x01R\x1ctwitterPostAuthorDisplayName\x88\x01\x01\x12*\n" +
	"\x11twitter_post_text\x18\x04 \x01(\tR\x0ftwitterPostText\x12Z\n" +
	"(replied_to_twitter_post_record_reference\x18\x05 \x01(\tH\x02R#repliedToTwitterPostRecordReference\x88\x01\x01\x12:\n" +
	"\x17twitter_post_like_count\x18\x06 \x01(\x03H\x03R\x14twitterPostLikeCount\x88\x01\x01\x12>\n" +
	"\x19twitter_post_repost_count\x18\a \x01(\x03H\x04R\x16twitterPostRepostCount\x88\x01\x01\x12<\n" +
	"\x18twitter_post_reply_count\x18\b \x01(\x03H\x05R\x15twitterPostReplyCount\x88\x01\x01\x12\\\n" +
	")twitter_post_counts_observed_rfc3339_time\x18\t \x01(\tH\x06R$twitterPostCountsObservedRfc3339Time\x88\x01\x01\x12H\n" +
	"\x1etwitter_post_availability_note\x18\n" +
	" \x01(\tH\aR\x1btwitterPostAvailabilityNote\x88\x01\x01\x12B\n" +
	"\x1btwitter_post_is_unavailable\x18\v \x01(\bH\bR\x18twitterPostIsUnavailable\x88\x01\x01\x12K\n" +
	"\x1ftwitter_conversation_identifier\x18\f \x01(\tH\tR\x1dtwitterConversationIdentifier\x88\x01\x01\x12H\n" +
	"\x1equoted_twitter_post_identifier\x18\r \x01(\tH\n" +
	"R\x1bquotedTwitterPostIdentifier\x88\x01\x01B$\n" +
	"\"_twitter_post_created_rfc3339_timeB#\n" +
	"!_twitter_post_author_display_nameB+\n" +
	")_replied_to_twitter_post_record_referenceB\x1a\n" +
	"\x18_twitter_post_like_countB\x1c\n" +
	"\x1a_twitter_post_repost_countB\x1b\n" +
	"\x19_twitter_post_reply_countB,\n" +
	"*_twitter_post_counts_observed_rfc3339_timeB!\n" +
	"\x1f_twitter_post_availability_noteB\x1e\n" +
	"\x1c_twitter_post_is_unavailableB\"\n" +
	" _twitter_conversation_identifierB!\n" +
	"\x1f_quoted_twitter_post_identifierBMZKgithub.com/opentrawl/opentrawl/twitter/proto/trawl/twitter/open;twitteropenb\x06proto3"

var (
	file_trawl_twitter_open_open_proto_rawDescOnce sync.Once
	file_trawl_twitter_open_open_proto_rawDescData []byte
)

func file_trawl_twitter_open_open_proto_rawDescGZIP() []byte {
	file_trawl_twitter_open_open_proto_rawDescOnce.Do(func() {
		file_trawl_twitter_open_open_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trawl_twitter_open_open_proto_rawDesc), len(file_trawl_twitter_open_open_proto_rawDesc)))
	})
	return file_trawl_twitter_open_open_proto_rawDescData
}

var file_trawl_twitter_open_open_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trawl_twitter_open_open_proto_goTypes = []any{
	(*OpenedTwitterPostRecord)(nil), // 0: trawl.twitter.open.OpenedTwitterPostRecord
	(*OpenedTwitterPost)(nil),       // 1: trawl.twitter.open.OpenedTwitterPost
}
var file_trawl_twitter_open_open_proto_depIdxs = []int32{
	1, // 0: trawl.twitter.open.OpenedTwitterPostRecord.opened_twitter_post:type_name -> trawl.twitter.open.OpenedTwitterPost
	1, // 1: trawl.twitter.open.OpenedTwitterPostRecord.ancestor_twitter_posts_in_oldest_first_order:type_name -> trawl.twitter.open.OpenedTwitterPost
	1, // 2: trawl.twitter.open.OpenedTwitterPostRecord.reply_twitter_posts_in_oldest_first_order:type_name -> trawl.twitter.open.OpenedTwitterPost
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_trawl_twitter_open_open_proto_init() }
func file_trawl_twitter_open_open_proto_init() {
	if File_trawl_twitter_open_open_proto != nil {
		return
	}
	file_trawl_twitter_open_open_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trawl_twitter_open_open_proto_rawDesc), len(file_trawl_twitter_open_open_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trawl_twitter_open_open_proto_goTypes,
		DependencyIndexes: file_trawl_twitter_open_open_proto_depIdxs,
		MessageInfos:      file_trawl_twitter_open_open_proto_msgTypes,
	}.Build()
	File_trawl_twitter_open_open_proto = out.File
	file_trawl_twitter_open_open_proto_goTypes = nil
	file_trawl_twitter_open_open_proto_depIdxs = nil
}
