// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trawl/command/v1/command.proto

package commandv1

import (
	v14 "github.com/opentrawl/opentrawl/trawlkit/proto/trawl/calendar_event/v1"
	v12 "github.com/opentrawl/opentrawl/trawlkit/proto/trawl/conversation/v1"
	v11 "github.com/opentrawl/opentrawl/trawlkit/proto/trawl/message/v1"
	v13 "github.com/opentrawl/opentrawl/trawlkit/proto/trawl/person/v1"
	v1 "github.com/opentrawl/opentrawl/trawlkit/proto/trawl/presentation/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrawlerSpecificCommandResponse struct {
	state                               protoimpl.MessageState `protogen:"open.v1"`
	TypedTrawlerSpecificCommandResponse *anypb.Any             `protobuf:"bytes,1,opt,name=typed_trawler_specific_command_response,json=typedTrawlerSpecificCommandResponse,proto3" json:"typed_trawler_specific_command_response,omitempty"`
	// Types that are valid to be assigned to TrawlerSpecificCommandPresentation:
	//
	//	*TrawlerSpecificCommandResponse_TrawlerSpecificCommandListPresentation
	//	*TrawlerSpecificCommandResponse_TrawlerSpecificCommandDetailPresentation
	TrawlerSpecificCommandPresentation isTrawlerSpecificCommandResponse_TrawlerSpecificCommandPresentation `protobuf_oneof:"trawler_specific_command_presentation"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *TrawlerSpecificCommandResponse) Reset() {
	*x = TrawlerSpecificCommandResponse{}
	mi := &file_trawl_command_v1_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerSpecificCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerSpecificCommandResponse) ProtoMessage() {}

func (x *TrawlerSpecificCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_command_v1_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerSpecificCommandResponse.ProtoReflect.Descriptor instead.
func (*TrawlerSpecificCommandResponse) Descriptor() ([]byte, []int) {
	return file_trawl_command_v1_command_proto_rawDescGZIP(), []int{0}
}

func (x *TrawlerSpecificCommandResponse) GetTypedTrawlerSpecificCommandResponse() *anypb.Any {
	if x != nil {
		return x.TypedTrawlerSpecificCommandResponse
	}
	return nil
}

func (x *TrawlerSpecificCommandResponse) GetTrawlerSpecificCommandPresentation() isTrawlerSpecificCommandResponse_TrawlerSpecificCommandPresentation {
	if x != nil {
		return x.TrawlerSpecificCommandPresentation
	}
	return nil
}

func (x *TrawlerSpecificCommandResponse) GetTrawlerSpecificCommandListPresentation() *v1.TrawlerSpecificCommandListPresentation {
	if x != nil {
		if x, ok := x.TrawlerSpecificCommandPresentation.(*TrawlerSpecificCommandResponse_TrawlerSpecificCommandListPresentation); ok {
			return x.TrawlerSpecificCommandListPresentation
		}
	}
	return nil
}

func (x *TrawlerSpecificCommandResponse) GetTrawlerSpecificCommandDetailPresentation() *v1.TrawlerSpecificCommandDetailPresentation {
	if x != nil {
		if x, ok := x.TrawlerSpecificCommandPresentation.(*TrawlerSpecificCommandResponse_TrawlerSpecificCommandDetailPresentation); ok {
			return x.TrawlerSpecificCommandDetailPresentation
		}
	}
	return nil
}

type isTrawlerSpecificCommandResponse_TrawlerSpecificCommandPresentation interface {
	isTrawlerSpecificCommandResponse_TrawlerSpecificCommandPresentation()
}

type TrawlerSpecificCommandResponse_TrawlerSpecificCommandListPresentation struct {
	TrawlerSpecificCommandListPresentation *v1.TrawlerSpecificCommandListPresentation `protobuf:"bytes,2,opt,name=trawler_specific_command_list_presentation,json=trawlerSpecificCommandListPresentation,proto3,oneof"`
}

type TrawlerSpecificCommandResponse_TrawlerSpecificCommandDetailPresentation struct {
	TrawlerSpecificCommandDetailPresentation *v1.TrawlerSpecificCommandDetailPresentation `protobuf:"bytes,3,opt,name=trawler_specific_command_detail_presentation,json=trawlerSpecificCommandDetailPresentation,proto3,oneof"`
}

func (*TrawlerSpecificCommandResponse_TrawlerSpecificCommandListPresentation) isTrawlerSpecificCommandResponse_TrawlerSpecificCommandPresentation() {
}

func (*TrawlerSpecificCommandResponse_TrawlerSpecificCommandDetailPresentation) isTrawlerSpecificCommandResponse_TrawlerSpecificCommandPresentation() {
}

type TrawlerCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TypedTrawlerCommandResponse:
	//
	//	*TrawlerCommandResponse_MessageListResponse
	//	*TrawlerCommandResponse_ConversationListResponse
	//	*TrawlerCommandResponse_PersonListResponse
	//	*TrawlerCommandResponse_PersonRecord
	//	*TrawlerCommandResponse_CalendarEventListResponse
	//	*TrawlerCommandResponse_TrawlerSpecificCommandResponse
	TypedTrawlerCommandResponse isTrawlerCommandResponse_TypedTrawlerCommandResponse `protobuf_oneof:"typed_trawler_command_response"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *TrawlerCommandResponse) Reset() {
	*x = TrawlerCommandResponse{}
	mi := &file_trawl_command_v1_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerCommandResponse) ProtoMessage() {}

func (x *TrawlerCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_command_v1_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerCommandResponse.ProtoReflect.Descriptor instead.
func (*TrawlerCommandResponse) Descriptor() ([]byte, []int) {
	return file_trawl_command_v1_command_proto_rawDescGZIP(), []int{1}
}

func (x *TrawlerCommandResponse) GetTypedTrawlerCommandResponse() isTrawlerCommandResponse_TypedTrawlerCommandResponse {
	if x != nil {
		return x.TypedTrawlerCommandResponse
	}
	return nil
}

func (x *TrawlerCommandResponse) GetMessageListResponse() *v11.MessageListResponse {
	if x != nil {
		if x, ok := x.TypedTrawlerCommandResponse.(*TrawlerCommandResponse_MessageListResponse); ok {
			return x.MessageListResponse
		}
	}
	return nil
}

func (x *TrawlerCommandResponse) GetConversationListResponse() *v12.ConversationListResponse {
	if x != nil {
		if x, ok := x.TypedTrawlerCommandResponse.(*TrawlerCommandResponse_ConversationListResponse); ok {
			return x.ConversationListResponse
		}
	}
	return nil
}

func (x *TrawlerCommandResponse) GetPersonListResponse() *v13.PersonListResponse {
	if x != nil {
		if x, ok := x.TypedTrawlerCommandResponse.(*TrawlerCommandResponse_PersonListResponse); ok {
			return x.PersonListResponse
		}
	}
	return nil
}

func (x *TrawlerCommandResponse) GetPersonRecord() *v13.PersonRecord {
	if x != nil {
		if x, ok := x.TypedTrawlerCommandResponse.(*TrawlerCommandResponse_PersonRecord); ok {
			return x.PersonRecord
		}
	}
	return nil
}

func (x *TrawlerCommandResponse) GetCalendarEventListResponse() *v14.CalendarEventListResponse {
	if x != nil {
		if x, ok := x.TypedTrawlerCommandResponse.(*TrawlerCommandResponse_CalendarEventListResponse); ok {
			return x.CalendarEventListResponse
		}
	}
	return nil
}

func (x *TrawlerCommandResponse) GetTrawlerSpecificCommandResponse() *TrawlerSpecificCommandResponse {
	if x != nil {
		if x, ok := x.TypedTrawlerCommandResponse.(*TrawlerCommandResponse_TrawlerSpecificCommandResponse); ok {
			return x.TrawlerSpecificCommandResponse
		}
	}
	return nil
}

type isTrawlerCommandResponse_TypedTrawlerCommandResponse interface {
	isTrawlerCommandResponse_TypedTrawlerCommandResponse()
}

type TrawlerCommandResponse_MessageListResponse struct {
	MessageListResponse *v11.MessageListResponse `protobuf:"bytes,1,opt,name=message_list_response,json=messageListResponse,proto3,oneof"`
}

type TrawlerCommandResponse_ConversationListResponse struct {
	ConversationListResponse *v12.ConversationListResponse `protobuf:"bytes,2,opt,name=conversation_list_response,json=conversationListResponse,proto3,oneof"`
}

type TrawlerCommandResponse_PersonListResponse struct {
	PersonListResponse *v13.PersonListResponse `protobuf:"bytes,3,opt,name=person_list_response,json=personListResponse,proto3,oneof"`
}

type TrawlerCommandResponse_PersonRecord struct {
	PersonRecord *v13.PersonRecord `protobuf:"bytes,4,opt,name=person_record,json=personRecord,proto3,oneof"`
}

type TrawlerCommandResponse_CalendarEventListResponse struct {
	CalendarEventListResponse *v14.CalendarEventListResponse `protobuf:"bytes,5,opt,name=calendar_event_list_response,json=calendarEventListResponse,proto3,oneof"`
}

type TrawlerCommandResponse_TrawlerSpecificCommandResponse struct {
	TrawlerSpecificCommandResponse *TrawlerSpecificCommandResponse `protobuf:"bytes,6,opt,name=trawler_specific_command_response,json=trawlerSpecificCommandResponse,proto3,oneof"`
}

func (*TrawlerCommandResponse_MessageListResponse) isTrawlerCommandResponse_TypedTrawlerCommandResponse() {
}

func (*TrawlerCommandResponse_ConversationListResponse) isTrawlerCommandResponse_TypedTrawlerCommandResponse() {
}

func (*TrawlerCommandResponse_PersonListResponse) isTrawlerCommandResponse_TypedTrawlerCommandResponse() {
}

func (*TrawlerCommandResponse_PersonRecord) isTrawlerCommandResponse_TypedTrawlerCommandResponse() {}

func (*TrawlerCommandResponse_CalendarEventListResponse) isTrawlerCommandResponse_TypedTrawlerCommandResponse() {
}

func (*TrawlerCommandResponse_TrawlerSpecificCommandResponse) isTrawlerCommandResponse_TypedTrawlerCommandResponse() {
}

var File_trawl_command_v1_command_proto protoreflect.FileDescriptor

const file_trawl_command_v1_command_proto_rawDesc = "" +
	"\n" +
	"\x1etrawl/command/v1/command.proto\x12\x10trawl.command.v1\x1a\x19google/protobuf/any.proto\x1a,trawl/calendar_event/v1/calendar_event.proto\x1a(trawl/conversation/v1/conversation.proto\x1a\x1etrawl/message/v1/message.proto\x1a\x1ctrawl/person/v1/person.proto\x1a(trawl/presentation/v1/presentation.proto\"\xf7\x03\n" +
	"\x1eTrawlerSpecificCommandResponse\x12j\n" +
	"'typed_trawler_specific_command_response\x18\x01 \x01(\v2\x14.google.protobuf.AnyR#typedTrawlerSpecificCommandResponse\x12\x9b\x01\n" +
	"*trawler_specific_command_list_presentation\x18\x02 \x01(\v2=.trawl.presentation.v1.TrawlerSpecificCommandListPresentationH\x00R&trawlerSpecificCommandListPresentation\x12\xa1\x01\n" +
	",trawler_specific_command_detail_presentation\x18\x03 \x01(\v2?.trawl.presentation.v1.TrawlerSpecificCommandDetailPresentationH\x00R(trawlerSpecificCommandDetailPresentationB'\n" +
	"%trawler_specific_command_presentation\"\x9d\x05\n" +
	"\x16TrawlerCommandResponse\x12[\n" +
	"\x15message_list_response\x18\x01 \x01(\v2%.trawl.message.v1.MessageListResponseH\x00R\x13messageListResponse\x12o\n" +
	"\x1aconversation_list_response\x18\x02 \x01(\v2/.trawl.conversation.v1.ConversationListResponseH\x00R\x18conversationListResponse\x12W\n" +
	"\x14person_list_response\x18\x03 \x01(\v2#.trawl.person.v1.PersonListResponseH\x00R\x12personListResponse\x12D\n" +
	"\rperson_record\x18\x04 \x01(\v2\x1d.trawl.person.v1.PersonRecordH\x00R\fpersonRecord\x12u\n" +
	"\x1ccalendar_event_list_response\x18\x05 \x01(\v22.trawl.calendar_event.v1.CalendarEventListResponseH\x00R\x19calendarEventListResponse\x12}\n" +
	"!trawler_specific_command_response\x18\x06 \x01(\v20.trawl.command.v1.TrawlerSpecificCommandResponseH\x00R\x1etrawlerSpecificCommandResponseB \n" +
	"\x1etyped_trawler_command_responseBJZHgithub.com/opentrawl/opentrawl/trawlkit/proto/trawl/command/v1;commandv1b\x06proto3"

var (
	file_trawl_command_v1_command_proto_rawDescOnce sync.Once
	file_trawl_command_v1_command_proto_rawDescData []byte
)

func file_trawl_command_v1_command_proto_rawDescGZIP() []byte {
	file_trawl_command_v1_command_proto_rawDescOnce.Do(func() {
		file_trawl_command_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trawl_command_v1_command_proto_rawDesc), len(file_trawl_command_v1_command_proto_rawDesc)))
	})
	return file_trawl_command_v1_command_proto_rawDescData
}

var file_trawl_command_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trawl_command_v1_command_proto_goTypes = []any{
	(*TrawlerSpecificCommandResponse)(nil),              // 0: trawl.command.v1.TrawlerSpecificCommandResponse
	(*TrawlerCommandResponse)(nil),                      // 1: trawl.command.v1.TrawlerCommandResponse
	(*anypb.Any)(nil),                                   // 2: google.protobuf.Any
	(*v1.TrawlerSpecificCommandListPresentation)(nil),   // 3: trawl.presentation.v1.TrawlerSpecificCommandListPresentation
	(*v1.TrawlerSpecificCommandDetailPresentation)(nil), // 4: trawl.presentation.v1.TrawlerSpecificCommandDetailPresentation
	(*v11.MessageListResponse)(nil),                     // 5: trawl.message.v1.MessageListResponse
	(*v12.ConversationListResponse)(nil),                // 6: trawl.conversation.v1.ConversationListResponse
	(*v13.PersonListResponse)(nil),                      // 7: trawl.person.v1.PersonListResponse
	(*v13.PersonRecord)(nil),                            // 8: trawl.person.v1.PersonRecord
	(*v14.CalendarEventListResponse)(nil),               // 9: trawl.calendar_event.v1.CalendarEventListResponse
}
var file_trawl_command_v1_command_proto_depIdxs = []int32{
	2, // 0: trawl.command.v1.TrawlerSpecificCommandResponse.typed_trawler_specific_command_response:type_name -> google.protobuf.Any
	3, // 1: trawl.command.v1.TrawlerSpecificCommandResponse.trawler_specific_command_list_presentation:type_name -> trawl.presentation.v1.TrawlerSpecificCommandListPresentation
	4, // 2: trawl.command.v1.TrawlerSpecificCommandResponse.trawler_specific_command_detail_presentation:type_name -> trawl.presentation.v1.TrawlerSpecificCommandDetailPresentation
	5, // 3: trawl.command.v1.TrawlerCommandResponse.message_list_response:type_name -> trawl.message.v1.MessageListResponse
	6, // 4: trawl.command.v1.TrawlerCommandResponse.conversation_list_response:type_name -> trawl.conversation.v1.ConversationListResponse
	7, // 5: trawl.command.v1.TrawlerCommandResponse.person_list_response:type_name -> trawl.person.v1.PersonListResponse
	8, // 6: trawl.command.v1.TrawlerCommandResponse.person_record:type_name -> trawl.person.v1.PersonRecord
	9, // 7: trawl.command.v1.TrawlerCommandResponse.calendar_event_list_response:type_name -> trawl.calendar_event.v1.CalendarEventListResponse
	0, // 8: trawl.command.v1.TrawlerCommandResponse.trawler_specific_command_response:type_name -> trawl.command.v1.TrawlerSpecificCommandResponse
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_trawl_command_v1_command_proto_init() }
func file_trawl_command_v1_command_proto_init() {
	if File_trawl_command_v1_command_proto != nil {
		return
	}
	file_trawl_command_v1_command_proto_msgTypes[0].OneofWrappers = []any{
		(*TrawlerSpecificCommandResponse_TrawlerSpecificCommandListPresentation)(nil),
		(*TrawlerSpecificCommandResponse_TrawlerSpecificCommandDetailPresentation)(nil),
	}
	file_trawl_command_v1_command_proto_msgTypes[1].OneofWrappers = []any{
		(*TrawlerCommandResponse_MessageListResponse)(nil),
		(*TrawlerCommandResponse_ConversationListResponse)(nil),
		(*TrawlerCommandResponse_PersonListResponse)(nil),
		(*TrawlerCommandResponse_PersonRecord)(nil),
		(*TrawlerCommandResponse_CalendarEventListResponse)(nil),
		(*TrawlerCommandResponse_TrawlerSpecificCommandResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trawl_command_v1_command_proto_rawDesc), len(file_trawl_command_v1_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trawl_command_v1_command_proto_goTypes,
		DependencyIndexes: file_trawl_command_v1_command_proto_depIdxs,
		MessageInfos:      file_trawl_command_v1_command_proto_msgTypes,
	}.Build()
	File_trawl_command_v1_command_proto = out.File
	file_trawl_command_v1_command_proto_goTypes = nil
	file_trawl_command_v1_command_proto_depIdxs = nil
}
