// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trawl/search/v1/search.proto

package searchv1

import (
	v12 "github.com/opentrawl/opentrawl/trawlkit/proto/trawl/identity/v1"
	v11 "github.com/opentrawl/opentrawl/trawlkit/proto/trawl/person/v1"
	v1 "github.com/opentrawl/opentrawl/trawlkit/proto/trawl/presentation/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchMatchTextFragment struct {
	state                                     protoimpl.MessageState `protogen:"open.v1"`
	SearchMatchTextFragmentContent            string                 `protobuf:"bytes,1,opt,name=search_match_text_fragment_content,json=searchMatchTextFragmentContent,proto3" json:"search_match_text_fragment_content,omitempty"`
	SearchMatchTextFragmentMatchesSearchQuery bool                   `protobuf:"varint,2,opt,name=search_match_text_fragment_matches_search_query,json=searchMatchTextFragmentMatchesSearchQuery,proto3" json:"search_match_text_fragment_matches_search_query,omitempty"`
	unknownFields                             protoimpl.UnknownFields
	sizeCache                                 protoimpl.SizeCache
}

func (x *SearchMatchTextFragment) Reset() {
	*x = SearchMatchTextFragment{}
	mi := &file_trawl_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMatchTextFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMatchTextFragment) ProtoMessage() {}

func (x *SearchMatchTextFragment) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMatchTextFragment.ProtoReflect.Descriptor instead.
func (*SearchMatchTextFragment) Descriptor() ([]byte, []int) {
	return file_trawl_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchMatchTextFragment) GetSearchMatchTextFragmentContent() string {
	if x != nil {
		return x.SearchMatchTextFragmentContent
	}
	return ""
}

func (x *SearchMatchTextFragment) GetSearchMatchTextFragmentMatchesSearchQuery() bool {
	if x != nil {
		return x.SearchMatchTextFragmentMatchesSearchQuery
	}
	return false
}

type SearchMatchTextField struct {
	state                                  protoimpl.MessageState     `protogen:"open.v1"`
	SearchMatchTextFieldName               string                     `protobuf:"bytes,1,opt,name=search_match_text_field_name,json=searchMatchTextFieldName,proto3" json:"search_match_text_field_name,omitempty"`
	SearchMatchTextFragmentsInDisplayOrder []*SearchMatchTextFragment `protobuf:"bytes,2,rep,name=search_match_text_fragments_in_display_order,json=searchMatchTextFragmentsInDisplayOrder,proto3" json:"search_match_text_fragments_in_display_order,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *SearchMatchTextField) Reset() {
	*x = SearchMatchTextField{}
	mi := &file_trawl_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMatchTextField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMatchTextField) ProtoMessage() {}

func (x *SearchMatchTextField) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMatchTextField.ProtoReflect.Descriptor instead.
func (*SearchMatchTextField) Descriptor() ([]byte, []int) {
	return file_trawl_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchMatchTextField) GetSearchMatchTextFieldName() string {
	if x != nil {
		return x.SearchMatchTextFieldName
	}
	return ""
}

func (x *SearchMatchTextField) GetSearchMatchTextFragmentsInDisplayOrder() []*SearchMatchTextFragment {
	if x != nil {
		return x.SearchMatchTextFragmentsInDisplayOrder
	}
	return nil
}

type SearchMatchPresentation struct {
	state                                  protoimpl.MessageState                    `protogen:"open.v1"`
	MatchingRecordAssociatedTime           *v1.ArchiveRecordAssociatedTimeForDisplay `protobuf:"bytes,1,opt,name=matching_record_associated_time,json=matchingRecordAssociatedTime,proto3" json:"matching_record_associated_time,omitempty"`
	RegisteredTrawlerDisplayName           string                                    `protobuf:"bytes,2,opt,name=registered_trawler_display_name,json=registeredTrawlerDisplayName,proto3" json:"registered_trawler_display_name,omitempty"`
	MatchingRecordDisplayName              string                                    `protobuf:"bytes,3,opt,name=matching_record_display_name,json=matchingRecordDisplayName,proto3" json:"matching_record_display_name,omitempty"`
	PeopleRelatedToMatchingRecord          []*v11.PersonRelatedToArchiveRecord       `protobuf:"bytes,4,rep,name=people_related_to_matching_record,json=peopleRelatedToMatchingRecord,proto3" json:"people_related_to_matching_record,omitempty"`
	DigitalContainerNamesNearestToBroadest []string                                  `protobuf:"bytes,5,rep,name=digital_container_names_nearest_to_broadest,json=digitalContainerNamesNearestToBroadest,proto3" json:"digital_container_names_nearest_to_broadest,omitempty"`
	PhysicalPlaceNamesSpecificToBroadest   []string                                  `protobuf:"bytes,6,rep,name=physical_place_names_specific_to_broadest,json=physicalPlaceNamesSpecificToBroadest,proto3" json:"physical_place_names_specific_to_broadest,omitempty"`
	SearchMatchTextFieldsInDisplayOrder    []*SearchMatchTextField                   `protobuf:"bytes,7,rep,name=search_match_text_fields_in_display_order,json=searchMatchTextFieldsInDisplayOrder,proto3" json:"search_match_text_fields_in_display_order,omitempty"`
	MatchingRecordKindDisplayName          string                                    `protobuf:"bytes,8,opt,name=matching_record_kind_display_name,json=matchingRecordKindDisplayName,proto3" json:"matching_record_kind_display_name,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *SearchMatchPresentation) Reset() {
	*x = SearchMatchPresentation{}
	mi := &file_trawl_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMatchPresentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMatchPresentation) ProtoMessage() {}

func (x *SearchMatchPresentation) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMatchPresentation.ProtoReflect.Descriptor instead.
func (*SearchMatchPresentation) Descriptor() ([]byte, []int) {
	return file_trawl_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMatchPresentation) GetMatchingRecordAssociatedTime() *v1.ArchiveRecordAssociatedTimeForDisplay {
	if x != nil {
		return x.MatchingRecordAssociatedTime
	}
	return nil
}

func (x *SearchMatchPresentation) GetRegisteredTrawlerDisplayName() string {
	if x != nil {
		return x.RegisteredTrawlerDisplayName
	}
	return ""
}

func (x *SearchMatchPresentation) GetMatchingRecordDisplayName() string {
	if x != nil {
		return x.MatchingRecordDisplayName
	}
	return ""
}

func (x *SearchMatchPresentation) GetPeopleRelatedToMatchingRecord() []*v11.PersonRelatedToArchiveRecord {
	if x != nil {
		return x.PeopleRelatedToMatchingRecord
	}
	return nil
}

func (x *SearchMatchPresentation) GetDigitalContainerNamesNearestToBroadest() []string {
	if x != nil {
		return x.DigitalContainerNamesNearestToBroadest
	}
	return nil
}

func (x *SearchMatchPresentation) GetPhysicalPlaceNamesSpecificToBroadest() []string {
	if x != nil {
		return x.PhysicalPlaceNamesSpecificToBroadest
	}
	return nil
}

func (x *SearchMatchPresentation) GetSearchMatchTextFieldsInDisplayOrder() []*SearchMatchTextField {
	if x != nil {
		return x.SearchMatchTextFieldsInDisplayOrder
	}
	return nil
}

func (x *SearchMatchPresentation) GetMatchingRecordKindDisplayName() string {
	if x != nil {
		return x.MatchingRecordKindDisplayName
	}
	return ""
}

type TrawlerSearchMatch struct {
	state                    protoimpl.MessageState               `protogen:"open.v1"`
	CanonicalRecordReference *v12.CanonicalArchiveRecordReference `protobuf:"bytes,1,opt,name=canonical_record_reference,json=canonicalRecordReference,proto3" json:"canonical_record_reference,omitempty"`
	RecordAnchor             *v12.RecordAnchorIdentifier          `protobuf:"bytes,2,opt,name=record_anchor,json=recordAnchor,proto3" json:"record_anchor,omitempty"`
	SearchMatchPresentation  *SearchMatchPresentation             `protobuf:"bytes,3,opt,name=search_match_presentation,json=searchMatchPresentation,proto3" json:"search_match_presentation,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TrawlerSearchMatch) Reset() {
	*x = TrawlerSearchMatch{}
	mi := &file_trawl_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerSearchMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerSearchMatch) ProtoMessage() {}

func (x *TrawlerSearchMatch) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerSearchMatch.ProtoReflect.Descriptor instead.
func (*TrawlerSearchMatch) Descriptor() ([]byte, []int) {
	return file_trawl_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *TrawlerSearchMatch) GetCanonicalRecordReference() *v12.CanonicalArchiveRecordReference {
	if x != nil {
		return x.CanonicalRecordReference
	}
	return nil
}

func (x *TrawlerSearchMatch) GetRecordAnchor() *v12.RecordAnchorIdentifier {
	if x != nil {
		return x.RecordAnchor
	}
	return nil
}

func (x *TrawlerSearchMatch) GetSearchMatchPresentation() *SearchMatchPresentation {
	if x != nil {
		return x.SearchMatchPresentation
	}
	return nil
}

type TrawlerSearchResponse struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	TrawlerSearchMatchesInDisplayOrder []*TrawlerSearchMatch  `protobuf:"bytes,1,rep,name=trawler_search_matches_in_display_order,json=trawlerSearchMatchesInDisplayOrder,proto3" json:"trawler_search_matches_in_display_order,omitempty"`
	TotalSearchMatches                 uint64                 `protobuf:"varint,2,opt,name=total_search_matches,json=totalSearchMatches,proto3" json:"total_search_matches,omitempty"`
	TotalSearchMatchesIsLowerBound     bool                   `protobuf:"varint,3,opt,name=total_search_matches_is_lower_bound,json=totalSearchMatchesIsLowerBound,proto3" json:"total_search_matches_is_lower_bound,omitempty"`
	MoreSearchMatchesExist             bool                   `protobuf:"varint,4,opt,name=more_search_matches_exist,json=moreSearchMatchesExist,proto3" json:"more_search_matches_exist,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *TrawlerSearchResponse) Reset() {
	*x = TrawlerSearchResponse{}
	mi := &file_trawl_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrawlerSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrawlerSearchResponse) ProtoMessage() {}

func (x *TrawlerSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trawl_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrawlerSearchResponse.ProtoReflect.Descriptor instead.
func (*TrawlerSearchResponse) Descriptor() ([]byte, []int) {
	return file_trawl_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *TrawlerSearchResponse) GetTrawlerSearchMatchesInDisplayOrder() []*TrawlerSearchMatch {
	if x != nil {
		return x.TrawlerSearchMatchesInDisplayOrder
	}
	return nil
}

func (x *TrawlerSearchResponse) GetTotalSearchMatches() uint64 {
	if x != nil {
		return x.TotalSearchMatches
	}
	return 0
}

func (x *TrawlerSearchResponse) GetTotalSearchMatchesIsLowerBound() bool {
	if x != nil {
		return x.TotalSearchMatchesIsLowerBound
	}
	return false
}

func (x *TrawlerSearchResponse) GetMoreSearchMatchesExist() bool {
	if x != nil {
		return x.MoreSearchMatchesExist
	}
	return false
}

var File_trawl_search_v1_search_proto protoreflect.FileDescriptor

const file_trawl_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x1ctrawl/search/v1/search.proto\x12\x0ftrawl.search.v1\x1a\x1ctrawl/person/v1/person.proto\x1a(trawl/presentation/v1/presentation.proto\x1a trawl/identity/v1/identity.proto\"\xc9\x01\n" +
	"\x17SearchMatchTextFragment\x12J\n" +
	"\"search_match_text_fragment_content\x18\x01 \x01(\tR\x1esearchMatchTextFragmentContent\x12b\n" +
	"/search_match_text_fragment_matches_search_query\x18\x02 \x01(\bR)searchMatchTextFragmentMatchesSearchQuery\"\xdf\x01\n" +
	"\x14SearchMatchTextField\x12>\n" +
	"\x1csearch_match_text_field_name\x18\x01 \x01(\tR\x18searchMatchTextFieldName\x12\x86\x01\n" +
	",search_match_text_fragments_in_display_order\x18\x02 \x03(\v2(.trawl.search.v1.SearchMatchTextFragmentR&searchMatchTextFragmentsInDisplayOrder\"\x9f\x06\n" +
	"\x17SearchMatchPresentation\x12\x83\x01\n" +
	"\x1fmatching_record_associated_time\x18\x01 \x01(\v2<.trawl.presentation.v1.ArchiveRecordAssociatedTimeForDisplayR\x1cmatchingRecordAssociatedTime\x12E\n" +
	"\x1fregistered_trawler_display_name\x18\x02 \x01(\tR\x1cregisteredTrawlerDisplayName\x12?\n" +
	"\x1cmatching_record_display_name\x18\x03 \x01(\tR\x19matchingRecordDisplayName\x12w\n" +
	"!people_related_to_matching_record\x18\x04 \x03(\v2-.trawl.person.v1.PersonRelatedToArchiveRecordR\x1dpeopleRelatedToMatchingRecord\x12[\n" +
	"+digital_container_names_nearest_to_broadest\x18\x05 \x03(\tR&digitalContainerNamesNearestToBroadest\x12W\n" +
	")physical_place_names_specific_to_broadest\x18\x06 \x03(\tR$physicalPlaceNamesSpecificToBroadest\x12}\n" +
	")search_match_text_fields_in_display_order\x18\a \x03(\v2%.trawl.search.v1.SearchMatchTextFieldR#searchMatchTextFieldsInDisplayOrder\x12H\n" +
	"!matching_record_kind_display_name\x18\b \x01(\tR\x1dmatchingRecordKindDisplayName\"\xbc\x02\n" +
	"\x12TrawlerSearchMatch\x12p\n" +
	"\x1acanonical_record_reference\x18\x01 \x01(\v22.trawl.identity.v1.CanonicalArchiveRecordReferenceR\x18canonicalRecordReference\x12N\n" +
	"\rrecord_anchor\x18\x02 \x01(\v2).trawl.identity.v1.RecordAnchorIdentifierR\frecordAnchor\x12d\n" +
	"\x19search_match_presentation\x18\x03 \x01(\v2(.trawl.search.v1.SearchMatchPresentationR\x17searchMatchPresentation\"\xcb\x02\n" +
	"\x15TrawlerSearchResponse\x12x\n" +
	"'trawler_search_matches_in_display_order\x18\x01 \x03(\v2#.trawl.search.v1.TrawlerSearchMatchR\"trawlerSearchMatchesInDisplayOrder\x120\n" +
	"\x14total_search_matches\x18\x02 \x01(\x04R\x12totalSearchMatches\x12K\n" +
	"#total_search_matches_is_lower_bound\x18\x03 \x01(\bR\x1etotalSearchMatchesIsLowerBound\x129\n" +
	"\x19more_search_matches_exist\x18\x04 \x01(\bR\x16moreSearchMatchesExistBHZFgithub.com/opentrawl/opentrawl/trawlkit/proto/trawl/search/v1;searchv1b\x06proto3"

var (
	file_trawl_search_v1_search_proto_rawDescOnce sync.Once
	file_trawl_search_v1_search_proto_rawDescData []byte
)

func file_trawl_search_v1_search_proto_rawDescGZIP() []byte {
	file_trawl_search_v1_search_proto_rawDescOnce.Do(func() {
		file_trawl_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trawl_search_v1_search_proto_rawDesc), len(file_trawl_search_v1_search_proto_rawDesc)))
	})
	return file_trawl_search_v1_search_proto_rawDescData
}

var file_trawl_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_trawl_search_v1_search_proto_goTypes = []any{
	(*SearchMatchTextFragment)(nil),                  // 0: trawl.search.v1.SearchMatchTextFragment
	(*SearchMatchTextField)(nil),                     // 1: trawl.search.v1.SearchMatchTextField
	(*SearchMatchPresentation)(nil),                  // 2: trawl.search.v1.SearchMatchPresentation
	(*TrawlerSearchMatch)(nil),                       // 3: trawl.search.v1.TrawlerSearchMatch
	(*TrawlerSearchResponse)(nil),                    // 4: trawl.search.v1.TrawlerSearchResponse
	(*v1.ArchiveRecordAssociatedTimeForDisplay)(nil), // 5: trawl.presentation.v1.ArchiveRecordAssociatedTimeForDisplay
	(*v11.PersonRelatedToArchiveRecord)(nil),         // 6: trawl.person.v1.PersonRelatedToArchiveRecord
	(*v12.CanonicalArchiveRecordReference)(nil),      // 7: trawl.identity.v1.CanonicalArchiveRecordReference
	(*v12.RecordAnchorIdentifier)(nil),               // 8: trawl.identity.v1.RecordAnchorIdentifier
}
var file_trawl_search_v1_search_proto_depIdxs = []int32{
	0, // 0: trawl.search.v1.SearchMatchTextField.search_match_text_fragments_in_display_order:type_name -> trawl.search.v1.SearchMatchTextFragment
	5, // 1: trawl.search.v1.SearchMatchPresentation.matching_record_associated_time:type_name -> trawl.presentation.v1.ArchiveRecordAssociatedTimeForDisplay
	6, // 2: trawl.search.v1.SearchMatchPresentation.people_related_to_matching_record:type_name -> trawl.person.v1.PersonRelatedToArchiveRecord
	1, // 3: trawl.search.v1.SearchMatchPresentation.search_match_text_fields_in_display_order:type_name -> trawl.search.v1.SearchMatchTextField
	7, // 4: trawl.search.v1.TrawlerSearchMatch.canonical_record_reference:type_name -> trawl.identity.v1.CanonicalArchiveRecordReference
	8, // 5: trawl.search.v1.TrawlerSearchMatch.record_anchor:type_name -> trawl.identity.v1.RecordAnchorIdentifier
	2, // 6: trawl.search.v1.TrawlerSearchMatch.search_match_presentation:type_name -> trawl.search.v1.SearchMatchPresentation
	3, // 7: trawl.search.v1.TrawlerSearchResponse.trawler_search_matches_in_display_order:type_name -> trawl.search.v1.TrawlerSearchMatch
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_trawl_search_v1_search_proto_init() }
func file_trawl_search_v1_search_proto_init() {
	if File_trawl_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trawl_search_v1_search_proto_rawDesc), len(file_trawl_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trawl_search_v1_search_proto_goTypes,
		DependencyIndexes: file_trawl_search_v1_search_proto_depIdxs,
		MessageInfos:      file_trawl_search_v1_search_proto_msgTypes,
	}.Build()
	File_trawl_search_v1_search_proto = out.File
	file_trawl_search_v1_search_proto_goTypes = nil
	file_trawl_search_v1_search_proto_depIdxs = nil
}
